import { KAMINO_FARMS_PROGRAM_ADDRESS, KAMINO_LENDING_PROGRAM_ADDRESS } from "../../programIds.js";
/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { ACCRUE_PROGRAM_ADDRESS } from "../programs/index.js";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared/index.js";

export const ADD_COLLATERAL_DISCRIMINATOR = new Uint8Array([
  127, 82, 121, 42, 161, 176, 249, 206,
]);

export function getAddCollateralDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    ADD_COLLATERAL_DISCRIMINATOR,
  );
}

export type AddCollateralInstruction<
  TProgram extends string = typeof ACCRUE_PROGRAM_ADDRESS,
  TAccountOwner extends string | AccountMeta<string> = string,
  TAccountPosition extends string | AccountMeta<string> = string,
  TAccountCollateralMint extends string | AccountMeta<string> = string,
  TAccountPositionCollateralAccount extends string | AccountMeta<string> =
    string,
  TAccountPositionUsdcAccount extends string | AccountMeta<string> = string,
  TAccountPositionDestinationAccount extends string | AccountMeta<string> =
    string,
  TAccountOwnerCollateralAccount extends string | AccountMeta<string> = string,
  TAccountObligation extends string | AccountMeta<string> = string,
  TAccountLendingMarket extends string | AccountMeta<string> = string,
  TAccountLendingMarketAuthority extends string | AccountMeta<string> = string,
  TAccountCollateralReserve extends string | AccountMeta<string> = string,
  TAccountCollateralReserveLiquiditySupply extends
    string | AccountMeta<string> = string,
  TAccountCollateralReserveCollateralMint extends string | AccountMeta<string> =
    string,
  TAccountCollateralReserveCollateralSupply extends
    string | AccountMeta<string> = string,
  TAccountBorrowReserve extends string | AccountMeta<string> = string,
  TAccountCollateralReserveFarmState extends string | AccountMeta<string> =
    string,
  TAccountCollateralObligationFarmState extends string | AccountMeta<string> =
    string,
  TAccountScopePrices extends string | AccountMeta<string> = string,
  TAccountBorrowScopePrices extends string | AccountMeta<string> = string,
  TAccountFarmsProgram extends string | AccountMeta<string> =
    "FarmsPZpWu9i7Kky8tPN37rs2TpmMrAZrC7S7vJa91Hr",
  TAccountKaminoProgram extends string | AccountMeta<string> =
    "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD",
  TAccountInstructionSysvar extends string | AccountMeta<string> =
    "Sysvar1nstructions1111111111111111111111111",
  TAccountKaminoCollateralTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountCollateralTokenProgram extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountOwner extends string
        ? WritableSignerAccount<TAccountOwner> &
            AccountSignerMeta<TAccountOwner>
        : TAccountOwner,
      TAccountPosition extends string
        ? WritableAccount<TAccountPosition>
        : TAccountPosition,
      TAccountCollateralMint extends string
        ? ReadonlyAccount<TAccountCollateralMint>
        : TAccountCollateralMint,
      TAccountPositionCollateralAccount extends string
        ? WritableAccount<TAccountPositionCollateralAccount>
        : TAccountPositionCollateralAccount,
      TAccountPositionUsdcAccount extends string
        ? WritableAccount<TAccountPositionUsdcAccount>
        : TAccountPositionUsdcAccount,
      TAccountPositionDestinationAccount extends string
        ? WritableAccount<TAccountPositionDestinationAccount>
        : TAccountPositionDestinationAccount,
      TAccountOwnerCollateralAccount extends string
        ? WritableAccount<TAccountOwnerCollateralAccount>
        : TAccountOwnerCollateralAccount,
      TAccountObligation extends string
        ? WritableAccount<TAccountObligation>
        : TAccountObligation,
      TAccountLendingMarket extends string
        ? WritableAccount<TAccountLendingMarket>
        : TAccountLendingMarket,
      TAccountLendingMarketAuthority extends string
        ? ReadonlyAccount<TAccountLendingMarketAuthority>
        : TAccountLendingMarketAuthority,
      TAccountCollateralReserve extends string
        ? WritableAccount<TAccountCollateralReserve>
        : TAccountCollateralReserve,
      TAccountCollateralReserveLiquiditySupply extends string
        ? WritableAccount<TAccountCollateralReserveLiquiditySupply>
        : TAccountCollateralReserveLiquiditySupply,
      TAccountCollateralReserveCollateralMint extends string
        ? WritableAccount<TAccountCollateralReserveCollateralMint>
        : TAccountCollateralReserveCollateralMint,
      TAccountCollateralReserveCollateralSupply extends string
        ? WritableAccount<TAccountCollateralReserveCollateralSupply>
        : TAccountCollateralReserveCollateralSupply,
      TAccountBorrowReserve extends string
        ? WritableAccount<TAccountBorrowReserve>
        : TAccountBorrowReserve,
      TAccountCollateralReserveFarmState extends string
        ? WritableAccount<TAccountCollateralReserveFarmState>
        : TAccountCollateralReserveFarmState,
      TAccountCollateralObligationFarmState extends string
        ? WritableAccount<TAccountCollateralObligationFarmState>
        : TAccountCollateralObligationFarmState,
      TAccountScopePrices extends string
        ? ReadonlyAccount<TAccountScopePrices>
        : TAccountScopePrices,
      TAccountBorrowScopePrices extends string
        ? ReadonlyAccount<TAccountBorrowScopePrices>
        : TAccountBorrowScopePrices,
      TAccountFarmsProgram extends string
        ? ReadonlyAccount<TAccountFarmsProgram>
        : TAccountFarmsProgram,
      TAccountKaminoProgram extends string
        ? ReadonlyAccount<TAccountKaminoProgram>
        : TAccountKaminoProgram,
      TAccountInstructionSysvar extends string
        ? ReadonlyAccount<TAccountInstructionSysvar>
        : TAccountInstructionSysvar,
      TAccountKaminoCollateralTokenProgram extends string
        ? ReadonlyAccount<TAccountKaminoCollateralTokenProgram>
        : TAccountKaminoCollateralTokenProgram,
      TAccountCollateralTokenProgram extends string
        ? ReadonlyAccount<TAccountCollateralTokenProgram>
        : TAccountCollateralTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type AddCollateralInstructionData = {
  discriminator: ReadonlyUint8Array;
  collateralAmount: bigint;
};

export type AddCollateralInstructionDataArgs = {
  collateralAmount: number | bigint;
};

export function getAddCollateralInstructionDataEncoder(): FixedSizeEncoder<AddCollateralInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["collateralAmount", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: ADD_COLLATERAL_DISCRIMINATOR }),
  );
}

export function getAddCollateralInstructionDataDecoder(): FixedSizeDecoder<AddCollateralInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["collateralAmount", getU64Decoder()],
  ]);
}

export function getAddCollateralInstructionDataCodec(): FixedSizeCodec<
  AddCollateralInstructionDataArgs,
  AddCollateralInstructionData
> {
  return combineCodec(
    getAddCollateralInstructionDataEncoder(),
    getAddCollateralInstructionDataDecoder(),
  );
}

export type AddCollateralAsyncInput<
  TAccountOwner extends string = string,
  TAccountPosition extends string = string,
  TAccountCollateralMint extends string = string,
  TAccountPositionCollateralAccount extends string = string,
  TAccountPositionUsdcAccount extends string = string,
  TAccountPositionDestinationAccount extends string = string,
  TAccountOwnerCollateralAccount extends string = string,
  TAccountObligation extends string = string,
  TAccountLendingMarket extends string = string,
  TAccountLendingMarketAuthority extends string = string,
  TAccountCollateralReserve extends string = string,
  TAccountCollateralReserveLiquiditySupply extends string = string,
  TAccountCollateralReserveCollateralMint extends string = string,
  TAccountCollateralReserveCollateralSupply extends string = string,
  TAccountBorrowReserve extends string = string,
  TAccountCollateralReserveFarmState extends string = string,
  TAccountCollateralObligationFarmState extends string = string,
  TAccountScopePrices extends string = string,
  TAccountBorrowScopePrices extends string = string,
  TAccountFarmsProgram extends string = string,
  TAccountKaminoProgram extends string = string,
  TAccountInstructionSysvar extends string = string,
  TAccountKaminoCollateralTokenProgram extends string = string,
  TAccountCollateralTokenProgram extends string = string,
> = {
  owner: TransactionSigner<TAccountOwner>;
  position: Address<TAccountPosition>;
  collateralMint: Address<TAccountCollateralMint>;
  positionCollateralAccount: Address<TAccountPositionCollateralAccount>;
  positionUsdcAccount: Address<TAccountPositionUsdcAccount>;
  positionDestinationAccount: Address<TAccountPositionDestinationAccount>;
  ownerCollateralAccount?: Address<TAccountOwnerCollateralAccount>;
  obligation: Address<TAccountObligation>;
  lendingMarket: Address<TAccountLendingMarket>;
  lendingMarketAuthority: Address<TAccountLendingMarketAuthority>;
  collateralReserve: Address<TAccountCollateralReserve>;
  collateralReserveLiquiditySupply: Address<TAccountCollateralReserveLiquiditySupply>;
  collateralReserveCollateralMint: Address<TAccountCollateralReserveCollateralMint>;
  collateralReserveCollateralSupply: Address<TAccountCollateralReserveCollateralSupply>;
  borrowReserve: Address<TAccountBorrowReserve>;
  collateralReserveFarmState?: Address<TAccountCollateralReserveFarmState>;
  collateralObligationFarmState?: Address<TAccountCollateralObligationFarmState>;
  scopePrices: Address<TAccountScopePrices>;
  borrowScopePrices: Address<TAccountBorrowScopePrices>;
  farmsProgram?: Address<TAccountFarmsProgram>;
  kaminoProgram?: Address<TAccountKaminoProgram>;
  instructionSysvar?: Address<TAccountInstructionSysvar>;
  kaminoCollateralTokenProgram?: Address<TAccountKaminoCollateralTokenProgram>;
  collateralTokenProgram: Address<TAccountCollateralTokenProgram>;
  collateralAmount: AddCollateralInstructionDataArgs["collateralAmount"];
};

export async function getAddCollateralInstructionAsync<
  TAccountOwner extends string,
  TAccountPosition extends string,
  TAccountCollateralMint extends string,
  TAccountPositionCollateralAccount extends string,
  TAccountPositionUsdcAccount extends string,
  TAccountPositionDestinationAccount extends string,
  TAccountOwnerCollateralAccount extends string,
  TAccountObligation extends string,
  TAccountLendingMarket extends string,
  TAccountLendingMarketAuthority extends string,
  TAccountCollateralReserve extends string,
  TAccountCollateralReserveLiquiditySupply extends string,
  TAccountCollateralReserveCollateralMint extends string,
  TAccountCollateralReserveCollateralSupply extends string,
  TAccountBorrowReserve extends string,
  TAccountCollateralReserveFarmState extends string,
  TAccountCollateralObligationFarmState extends string,
  TAccountScopePrices extends string,
  TAccountBorrowScopePrices extends string,
  TAccountFarmsProgram extends string,
  TAccountKaminoProgram extends string,
  TAccountInstructionSysvar extends string,
  TAccountKaminoCollateralTokenProgram extends string,
  TAccountCollateralTokenProgram extends string,
  TProgramAddress extends Address = typeof ACCRUE_PROGRAM_ADDRESS,
>(
  input: AddCollateralAsyncInput<
    TAccountOwner,
    TAccountPosition,
    TAccountCollateralMint,
    TAccountPositionCollateralAccount,
    TAccountPositionUsdcAccount,
    TAccountPositionDestinationAccount,
    TAccountOwnerCollateralAccount,
    TAccountObligation,
    TAccountLendingMarket,
    TAccountLendingMarketAuthority,
    TAccountCollateralReserve,
    TAccountCollateralReserveLiquiditySupply,
    TAccountCollateralReserveCollateralMint,
    TAccountCollateralReserveCollateralSupply,
    TAccountBorrowReserve,
    TAccountCollateralReserveFarmState,
    TAccountCollateralObligationFarmState,
    TAccountScopePrices,
    TAccountBorrowScopePrices,
    TAccountFarmsProgram,
    TAccountKaminoProgram,
    TAccountInstructionSysvar,
    TAccountKaminoCollateralTokenProgram,
    TAccountCollateralTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  AddCollateralInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountPosition,
    TAccountCollateralMint,
    TAccountPositionCollateralAccount,
    TAccountPositionUsdcAccount,
    TAccountPositionDestinationAccount,
    TAccountOwnerCollateralAccount,
    TAccountObligation,
    TAccountLendingMarket,
    TAccountLendingMarketAuthority,
    TAccountCollateralReserve,
    TAccountCollateralReserveLiquiditySupply,
    TAccountCollateralReserveCollateralMint,
    TAccountCollateralReserveCollateralSupply,
    TAccountBorrowReserve,
    TAccountCollateralReserveFarmState,
    TAccountCollateralObligationFarmState,
    TAccountScopePrices,
    TAccountBorrowScopePrices,
    TAccountFarmsProgram,
    TAccountKaminoProgram,
    TAccountInstructionSysvar,
    TAccountKaminoCollateralTokenProgram,
    TAccountCollateralTokenProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ACCRUE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    owner: { value: input.owner ?? null, isWritable: true },
    position: { value: input.position ?? null, isWritable: true },
    collateralMint: { value: input.collateralMint ?? null, isWritable: false },
    positionCollateralAccount: {
      value: input.positionCollateralAccount ?? null,
      isWritable: true,
    },
    positionUsdcAccount: {
      value: input.positionUsdcAccount ?? null,
      isWritable: true,
    },
    positionDestinationAccount: {
      value: input.positionDestinationAccount ?? null,
      isWritable: true,
    },
    ownerCollateralAccount: {
      value: input.ownerCollateralAccount ?? null,
      isWritable: true,
    },
    obligation: { value: input.obligation ?? null, isWritable: true },
    lendingMarket: { value: input.lendingMarket ?? null, isWritable: true },
    lendingMarketAuthority: {
      value: input.lendingMarketAuthority ?? null,
      isWritable: false,
    },
    collateralReserve: {
      value: input.collateralReserve ?? null,
      isWritable: true,
    },
    collateralReserveLiquiditySupply: {
      value: input.collateralReserveLiquiditySupply ?? null,
      isWritable: true,
    },
    collateralReserveCollateralMint: {
      value: input.collateralReserveCollateralMint ?? null,
      isWritable: true,
    },
    collateralReserveCollateralSupply: {
      value: input.collateralReserveCollateralSupply ?? null,
      isWritable: true,
    },
    borrowReserve: { value: input.borrowReserve ?? null, isWritable: true },
    collateralReserveFarmState: {
      value: input.collateralReserveFarmState ?? null,
      isWritable: true,
    },
    collateralObligationFarmState: {
      value: input.collateralObligationFarmState ?? null,
      isWritable: true,
    },
    scopePrices: { value: input.scopePrices ?? null, isWritable: false },
    borrowScopePrices: {
      value: input.borrowScopePrices ?? null,
      isWritable: false,
    },
    farmsProgram: { value: input.farmsProgram ?? null, isWritable: false },
    kaminoProgram: { value: input.kaminoProgram ?? null, isWritable: false },
    instructionSysvar: {
      value: input.instructionSysvar ?? null,
      isWritable: false,
    },
    kaminoCollateralTokenProgram: {
      value: input.kaminoCollateralTokenProgram ?? null,
      isWritable: false,
    },
    collateralTokenProgram: {
      value: input.collateralTokenProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.ownerCollateralAccount.value) {
    accounts.ownerCollateralAccount.value = await getProgramDerivedAddress({
      programAddress:
        "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.owner.value)),
        getAddressEncoder().encode(
          expectAddress(accounts.collateralTokenProgram.value),
        ),
        getAddressEncoder().encode(
          expectAddress(accounts.collateralMint.value),
        ),
      ],
    });
  }
  if (!accounts.farmsProgram.value) {
    accounts.farmsProgram.value =
      (KAMINO_FARMS_PROGRAM_ADDRESS as Address<"FarmsPZpWu9i7Kky8tPN37rs2TpmMrAZrC7S7vJa91Hr">);
  }
  if (!accounts.kaminoProgram.value) {
    accounts.kaminoProgram.value =
      (KAMINO_LENDING_PROGRAM_ADDRESS as Address<"KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD">);
  }
  if (!accounts.instructionSysvar.value) {
    accounts.instructionSysvar.value =
      "Sysvar1nstructions1111111111111111111111111" as Address<"Sysvar1nstructions1111111111111111111111111">;
  }
  if (!accounts.kaminoCollateralTokenProgram.value) {
    accounts.kaminoCollateralTokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.owner),
      getAccountMeta(accounts.position),
      getAccountMeta(accounts.collateralMint),
      getAccountMeta(accounts.positionCollateralAccount),
      getAccountMeta(accounts.positionUsdcAccount),
      getAccountMeta(accounts.positionDestinationAccount),
      getAccountMeta(accounts.ownerCollateralAccount),
      getAccountMeta(accounts.obligation),
      getAccountMeta(accounts.lendingMarket),
      getAccountMeta(accounts.lendingMarketAuthority),
      getAccountMeta(accounts.collateralReserve),
      getAccountMeta(accounts.collateralReserveLiquiditySupply),
      getAccountMeta(accounts.collateralReserveCollateralMint),
      getAccountMeta(accounts.collateralReserveCollateralSupply),
      getAccountMeta(accounts.borrowReserve),
      getAccountMeta(accounts.collateralReserveFarmState),
      getAccountMeta(accounts.collateralObligationFarmState),
      getAccountMeta(accounts.scopePrices),
      getAccountMeta(accounts.borrowScopePrices),
      getAccountMeta(accounts.farmsProgram),
      getAccountMeta(accounts.kaminoProgram),
      getAccountMeta(accounts.instructionSysvar),
      getAccountMeta(accounts.kaminoCollateralTokenProgram),
      getAccountMeta(accounts.collateralTokenProgram),
    ],
    data: getAddCollateralInstructionDataEncoder().encode(
      args as AddCollateralInstructionDataArgs,
    ),
    programAddress,
  } as AddCollateralInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountPosition,
    TAccountCollateralMint,
    TAccountPositionCollateralAccount,
    TAccountPositionUsdcAccount,
    TAccountPositionDestinationAccount,
    TAccountOwnerCollateralAccount,
    TAccountObligation,
    TAccountLendingMarket,
    TAccountLendingMarketAuthority,
    TAccountCollateralReserve,
    TAccountCollateralReserveLiquiditySupply,
    TAccountCollateralReserveCollateralMint,
    TAccountCollateralReserveCollateralSupply,
    TAccountBorrowReserve,
    TAccountCollateralReserveFarmState,
    TAccountCollateralObligationFarmState,
    TAccountScopePrices,
    TAccountBorrowScopePrices,
    TAccountFarmsProgram,
    TAccountKaminoProgram,
    TAccountInstructionSysvar,
    TAccountKaminoCollateralTokenProgram,
    TAccountCollateralTokenProgram
  >);
}

export type AddCollateralInput<
  TAccountOwner extends string = string,
  TAccountPosition extends string = string,
  TAccountCollateralMint extends string = string,
  TAccountPositionCollateralAccount extends string = string,
  TAccountPositionUsdcAccount extends string = string,
  TAccountPositionDestinationAccount extends string = string,
  TAccountOwnerCollateralAccount extends string = string,
  TAccountObligation extends string = string,
  TAccountLendingMarket extends string = string,
  TAccountLendingMarketAuthority extends string = string,
  TAccountCollateralReserve extends string = string,
  TAccountCollateralReserveLiquiditySupply extends string = string,
  TAccountCollateralReserveCollateralMint extends string = string,
  TAccountCollateralReserveCollateralSupply extends string = string,
  TAccountBorrowReserve extends string = string,
  TAccountCollateralReserveFarmState extends string = string,
  TAccountCollateralObligationFarmState extends string = string,
  TAccountScopePrices extends string = string,
  TAccountBorrowScopePrices extends string = string,
  TAccountFarmsProgram extends string = string,
  TAccountKaminoProgram extends string = string,
  TAccountInstructionSysvar extends string = string,
  TAccountKaminoCollateralTokenProgram extends string = string,
  TAccountCollateralTokenProgram extends string = string,
> = {
  owner: TransactionSigner<TAccountOwner>;
  position: Address<TAccountPosition>;
  collateralMint: Address<TAccountCollateralMint>;
  positionCollateralAccount: Address<TAccountPositionCollateralAccount>;
  positionUsdcAccount: Address<TAccountPositionUsdcAccount>;
  positionDestinationAccount: Address<TAccountPositionDestinationAccount>;
  ownerCollateralAccount: Address<TAccountOwnerCollateralAccount>;
  obligation: Address<TAccountObligation>;
  lendingMarket: Address<TAccountLendingMarket>;
  lendingMarketAuthority: Address<TAccountLendingMarketAuthority>;
  collateralReserve: Address<TAccountCollateralReserve>;
  collateralReserveLiquiditySupply: Address<TAccountCollateralReserveLiquiditySupply>;
  collateralReserveCollateralMint: Address<TAccountCollateralReserveCollateralMint>;
  collateralReserveCollateralSupply: Address<TAccountCollateralReserveCollateralSupply>;
  borrowReserve: Address<TAccountBorrowReserve>;
  collateralReserveFarmState?: Address<TAccountCollateralReserveFarmState>;
  collateralObligationFarmState?: Address<TAccountCollateralObligationFarmState>;
  scopePrices: Address<TAccountScopePrices>;
  borrowScopePrices: Address<TAccountBorrowScopePrices>;
  farmsProgram?: Address<TAccountFarmsProgram>;
  kaminoProgram?: Address<TAccountKaminoProgram>;
  instructionSysvar?: Address<TAccountInstructionSysvar>;
  kaminoCollateralTokenProgram?: Address<TAccountKaminoCollateralTokenProgram>;
  collateralTokenProgram: Address<TAccountCollateralTokenProgram>;
  collateralAmount: AddCollateralInstructionDataArgs["collateralAmount"];
};

export function getAddCollateralInstruction<
  TAccountOwner extends string,
  TAccountPosition extends string,
  TAccountCollateralMint extends string,
  TAccountPositionCollateralAccount extends string,
  TAccountPositionUsdcAccount extends string,
  TAccountPositionDestinationAccount extends string,
  TAccountOwnerCollateralAccount extends string,
  TAccountObligation extends string,
  TAccountLendingMarket extends string,
  TAccountLendingMarketAuthority extends string,
  TAccountCollateralReserve extends string,
  TAccountCollateralReserveLiquiditySupply extends string,
  TAccountCollateralReserveCollateralMint extends string,
  TAccountCollateralReserveCollateralSupply extends string,
  TAccountBorrowReserve extends string,
  TAccountCollateralReserveFarmState extends string,
  TAccountCollateralObligationFarmState extends string,
  TAccountScopePrices extends string,
  TAccountBorrowScopePrices extends string,
  TAccountFarmsProgram extends string,
  TAccountKaminoProgram extends string,
  TAccountInstructionSysvar extends string,
  TAccountKaminoCollateralTokenProgram extends string,
  TAccountCollateralTokenProgram extends string,
  TProgramAddress extends Address = typeof ACCRUE_PROGRAM_ADDRESS,
>(
  input: AddCollateralInput<
    TAccountOwner,
    TAccountPosition,
    TAccountCollateralMint,
    TAccountPositionCollateralAccount,
    TAccountPositionUsdcAccount,
    TAccountPositionDestinationAccount,
    TAccountOwnerCollateralAccount,
    TAccountObligation,
    TAccountLendingMarket,
    TAccountLendingMarketAuthority,
    TAccountCollateralReserve,
    TAccountCollateralReserveLiquiditySupply,
    TAccountCollateralReserveCollateralMint,
    TAccountCollateralReserveCollateralSupply,
    TAccountBorrowReserve,
    TAccountCollateralReserveFarmState,
    TAccountCollateralObligationFarmState,
    TAccountScopePrices,
    TAccountBorrowScopePrices,
    TAccountFarmsProgram,
    TAccountKaminoProgram,
    TAccountInstructionSysvar,
    TAccountKaminoCollateralTokenProgram,
    TAccountCollateralTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): AddCollateralInstruction<
  TProgramAddress,
  TAccountOwner,
  TAccountPosition,
  TAccountCollateralMint,
  TAccountPositionCollateralAccount,
  TAccountPositionUsdcAccount,
  TAccountPositionDestinationAccount,
  TAccountOwnerCollateralAccount,
  TAccountObligation,
  TAccountLendingMarket,
  TAccountLendingMarketAuthority,
  TAccountCollateralReserve,
  TAccountCollateralReserveLiquiditySupply,
  TAccountCollateralReserveCollateralMint,
  TAccountCollateralReserveCollateralSupply,
  TAccountBorrowReserve,
  TAccountCollateralReserveFarmState,
  TAccountCollateralObligationFarmState,
  TAccountScopePrices,
  TAccountBorrowScopePrices,
  TAccountFarmsProgram,
  TAccountKaminoProgram,
  TAccountInstructionSysvar,
  TAccountKaminoCollateralTokenProgram,
  TAccountCollateralTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? ACCRUE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    owner: { value: input.owner ?? null, isWritable: true },
    position: { value: input.position ?? null, isWritable: true },
    collateralMint: { value: input.collateralMint ?? null, isWritable: false },
    positionCollateralAccount: {
      value: input.positionCollateralAccount ?? null,
      isWritable: true,
    },
    positionUsdcAccount: {
      value: input.positionUsdcAccount ?? null,
      isWritable: true,
    },
    positionDestinationAccount: {
      value: input.positionDestinationAccount ?? null,
      isWritable: true,
    },
    ownerCollateralAccount: {
      value: input.ownerCollateralAccount ?? null,
      isWritable: true,
    },
    obligation: { value: input.obligation ?? null, isWritable: true },
    lendingMarket: { value: input.lendingMarket ?? null, isWritable: true },
    lendingMarketAuthority: {
      value: input.lendingMarketAuthority ?? null,
      isWritable: false,
    },
    collateralReserve: {
      value: input.collateralReserve ?? null,
      isWritable: true,
    },
    collateralReserveLiquiditySupply: {
      value: input.collateralReserveLiquiditySupply ?? null,
      isWritable: true,
    },
    collateralReserveCollateralMint: {
      value: input.collateralReserveCollateralMint ?? null,
      isWritable: true,
    },
    collateralReserveCollateralSupply: {
      value: input.collateralReserveCollateralSupply ?? null,
      isWritable: true,
    },
    borrowReserve: { value: input.borrowReserve ?? null, isWritable: true },
    collateralReserveFarmState: {
      value: input.collateralReserveFarmState ?? null,
      isWritable: true,
    },
    collateralObligationFarmState: {
      value: input.collateralObligationFarmState ?? null,
      isWritable: true,
    },
    scopePrices: { value: input.scopePrices ?? null, isWritable: false },
    borrowScopePrices: {
      value: input.borrowScopePrices ?? null,
      isWritable: false,
    },
    farmsProgram: { value: input.farmsProgram ?? null, isWritable: false },
    kaminoProgram: { value: input.kaminoProgram ?? null, isWritable: false },
    instructionSysvar: {
      value: input.instructionSysvar ?? null,
      isWritable: false,
    },
    kaminoCollateralTokenProgram: {
      value: input.kaminoCollateralTokenProgram ?? null,
      isWritable: false,
    },
    collateralTokenProgram: {
      value: input.collateralTokenProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.farmsProgram.value) {
    accounts.farmsProgram.value =
      (KAMINO_FARMS_PROGRAM_ADDRESS as Address<"FarmsPZpWu9i7Kky8tPN37rs2TpmMrAZrC7S7vJa91Hr">);
  }
  if (!accounts.kaminoProgram.value) {
    accounts.kaminoProgram.value =
      (KAMINO_LENDING_PROGRAM_ADDRESS as Address<"KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD">);
  }
  if (!accounts.instructionSysvar.value) {
    accounts.instructionSysvar.value =
      "Sysvar1nstructions1111111111111111111111111" as Address<"Sysvar1nstructions1111111111111111111111111">;
  }
  if (!accounts.kaminoCollateralTokenProgram.value) {
    accounts.kaminoCollateralTokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.owner),
      getAccountMeta(accounts.position),
      getAccountMeta(accounts.collateralMint),
      getAccountMeta(accounts.positionCollateralAccount),
      getAccountMeta(accounts.positionUsdcAccount),
      getAccountMeta(accounts.positionDestinationAccount),
      getAccountMeta(accounts.ownerCollateralAccount),
      getAccountMeta(accounts.obligation),
      getAccountMeta(accounts.lendingMarket),
      getAccountMeta(accounts.lendingMarketAuthority),
      getAccountMeta(accounts.collateralReserve),
      getAccountMeta(accounts.collateralReserveLiquiditySupply),
      getAccountMeta(accounts.collateralReserveCollateralMint),
      getAccountMeta(accounts.collateralReserveCollateralSupply),
      getAccountMeta(accounts.borrowReserve),
      getAccountMeta(accounts.collateralReserveFarmState),
      getAccountMeta(accounts.collateralObligationFarmState),
      getAccountMeta(accounts.scopePrices),
      getAccountMeta(accounts.borrowScopePrices),
      getAccountMeta(accounts.farmsProgram),
      getAccountMeta(accounts.kaminoProgram),
      getAccountMeta(accounts.instructionSysvar),
      getAccountMeta(accounts.kaminoCollateralTokenProgram),
      getAccountMeta(accounts.collateralTokenProgram),
    ],
    data: getAddCollateralInstructionDataEncoder().encode(
      args as AddCollateralInstructionDataArgs,
    ),
    programAddress,
  } as AddCollateralInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountPosition,
    TAccountCollateralMint,
    TAccountPositionCollateralAccount,
    TAccountPositionUsdcAccount,
    TAccountPositionDestinationAccount,
    TAccountOwnerCollateralAccount,
    TAccountObligation,
    TAccountLendingMarket,
    TAccountLendingMarketAuthority,
    TAccountCollateralReserve,
    TAccountCollateralReserveLiquiditySupply,
    TAccountCollateralReserveCollateralMint,
    TAccountCollateralReserveCollateralSupply,
    TAccountBorrowReserve,
    TAccountCollateralReserveFarmState,
    TAccountCollateralObligationFarmState,
    TAccountScopePrices,
    TAccountBorrowScopePrices,
    TAccountFarmsProgram,
    TAccountKaminoProgram,
    TAccountInstructionSysvar,
    TAccountKaminoCollateralTokenProgram,
    TAccountCollateralTokenProgram
  >);
}

export type ParsedAddCollateralInstruction<
  TProgram extends string = typeof ACCRUE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    owner: TAccountMetas[0];
    position: TAccountMetas[1];
    collateralMint: TAccountMetas[2];
    positionCollateralAccount: TAccountMetas[3];
    positionUsdcAccount: TAccountMetas[4];
    positionDestinationAccount: TAccountMetas[5];
    ownerCollateralAccount: TAccountMetas[6];
    obligation: TAccountMetas[7];
    lendingMarket: TAccountMetas[8];
    lendingMarketAuthority: TAccountMetas[9];
    collateralReserve: TAccountMetas[10];
    collateralReserveLiquiditySupply: TAccountMetas[11];
    collateralReserveCollateralMint: TAccountMetas[12];
    collateralReserveCollateralSupply: TAccountMetas[13];
    borrowReserve: TAccountMetas[14];
    collateralReserveFarmState?: TAccountMetas[15] | undefined;
    collateralObligationFarmState?: TAccountMetas[16] | undefined;
    scopePrices: TAccountMetas[17];
    borrowScopePrices: TAccountMetas[18];
    farmsProgram: TAccountMetas[19];
    kaminoProgram: TAccountMetas[20];
    instructionSysvar: TAccountMetas[21];
    kaminoCollateralTokenProgram: TAccountMetas[22];
    collateralTokenProgram: TAccountMetas[23];
  };
  data: AddCollateralInstructionData;
};

export function parseAddCollateralInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedAddCollateralInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 24) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  const getNextOptionalAccount = () => {
    const accountMeta = getNextAccount();
    return accountMeta.address === ACCRUE_PROGRAM_ADDRESS
      ? undefined
      : accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      owner: getNextAccount(),
      position: getNextAccount(),
      collateralMint: getNextAccount(),
      positionCollateralAccount: getNextAccount(),
      positionUsdcAccount: getNextAccount(),
      positionDestinationAccount: getNextAccount(),
      ownerCollateralAccount: getNextAccount(),
      obligation: getNextAccount(),
      lendingMarket: getNextAccount(),
      lendingMarketAuthority: getNextAccount(),
      collateralReserve: getNextAccount(),
      collateralReserveLiquiditySupply: getNextAccount(),
      collateralReserveCollateralMint: getNextAccount(),
      collateralReserveCollateralSupply: getNextAccount(),
      borrowReserve: getNextAccount(),
      collateralReserveFarmState: getNextOptionalAccount(),
      collateralObligationFarmState: getNextOptionalAccount(),
      scopePrices: getNextAccount(),
      borrowScopePrices: getNextAccount(),
      farmsProgram: getNextAccount(),
      kaminoProgram: getNextAccount(),
      instructionSysvar: getNextAccount(),
      kaminoCollateralTokenProgram: getNextAccount(),
      collateralTokenProgram: getNextAccount(),
    },
    data: getAddCollateralInstructionDataDecoder().decode(instruction.data),
  };
}
