/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { ACCRUE_PROGRAM_ADDRESS } from "../programs/index.js";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared/index.js";

export const CLOSE_POSITION_DISCRIMINATOR = new Uint8Array([
  123, 134, 81, 0, 49, 68, 98, 98,
]);

export function getClosePositionDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CLOSE_POSITION_DISCRIMINATOR,
  );
}

export type ClosePositionInstruction<
  TProgram extends string = typeof ACCRUE_PROGRAM_ADDRESS,
  TAccountOwner extends string | AccountMeta<string> = string,
  TAccountPosition extends string | AccountMeta<string> = string,
  TAccountPositionCollateralAccount extends string | AccountMeta<string> =
    string,
  TAccountPositionUsdcAccount extends string | AccountMeta<string> = string,
  TAccountPositionDestinationAccount extends string | AccountMeta<string> =
    string,
  TAccountObligation extends string | AccountMeta<string> = string,
  TAccountCollateralReserve extends string | AccountMeta<string> = string,
  TAccountCollateralTokenProgram extends string | AccountMeta<string> = string,
  TAccountBorrowTokenProgram extends string | AccountMeta<string> = string,
  TAccountDestinationTokenProgram extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountOwner extends string
        ? WritableSignerAccount<TAccountOwner> &
            AccountSignerMeta<TAccountOwner>
        : TAccountOwner,
      TAccountPosition extends string
        ? WritableAccount<TAccountPosition>
        : TAccountPosition,
      TAccountPositionCollateralAccount extends string
        ? WritableAccount<TAccountPositionCollateralAccount>
        : TAccountPositionCollateralAccount,
      TAccountPositionUsdcAccount extends string
        ? WritableAccount<TAccountPositionUsdcAccount>
        : TAccountPositionUsdcAccount,
      TAccountPositionDestinationAccount extends string
        ? WritableAccount<TAccountPositionDestinationAccount>
        : TAccountPositionDestinationAccount,
      TAccountObligation extends string
        ? ReadonlyAccount<TAccountObligation>
        : TAccountObligation,
      TAccountCollateralReserve extends string
        ? ReadonlyAccount<TAccountCollateralReserve>
        : TAccountCollateralReserve,
      TAccountCollateralTokenProgram extends string
        ? ReadonlyAccount<TAccountCollateralTokenProgram>
        : TAccountCollateralTokenProgram,
      TAccountBorrowTokenProgram extends string
        ? ReadonlyAccount<TAccountBorrowTokenProgram>
        : TAccountBorrowTokenProgram,
      TAccountDestinationTokenProgram extends string
        ? ReadonlyAccount<TAccountDestinationTokenProgram>
        : TAccountDestinationTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type ClosePositionInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type ClosePositionInstructionDataArgs = {};

export function getClosePositionInstructionDataEncoder(): FixedSizeEncoder<ClosePositionInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: CLOSE_POSITION_DISCRIMINATOR }),
  );
}

export function getClosePositionInstructionDataDecoder(): FixedSizeDecoder<ClosePositionInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getClosePositionInstructionDataCodec(): FixedSizeCodec<
  ClosePositionInstructionDataArgs,
  ClosePositionInstructionData
> {
  return combineCodec(
    getClosePositionInstructionDataEncoder(),
    getClosePositionInstructionDataDecoder(),
  );
}

export type ClosePositionInput<
  TAccountOwner extends string = string,
  TAccountPosition extends string = string,
  TAccountPositionCollateralAccount extends string = string,
  TAccountPositionUsdcAccount extends string = string,
  TAccountPositionDestinationAccount extends string = string,
  TAccountObligation extends string = string,
  TAccountCollateralReserve extends string = string,
  TAccountCollateralTokenProgram extends string = string,
  TAccountBorrowTokenProgram extends string = string,
  TAccountDestinationTokenProgram extends string = string,
> = {
  owner: TransactionSigner<TAccountOwner>;
  position: Address<TAccountPosition>;
  positionCollateralAccount: Address<TAccountPositionCollateralAccount>;
  positionUsdcAccount: Address<TAccountPositionUsdcAccount>;
  positionDestinationAccount: Address<TAccountPositionDestinationAccount>;
  obligation: Address<TAccountObligation>;
  collateralReserve: Address<TAccountCollateralReserve>;
  collateralTokenProgram: Address<TAccountCollateralTokenProgram>;
  borrowTokenProgram: Address<TAccountBorrowTokenProgram>;
  destinationTokenProgram: Address<TAccountDestinationTokenProgram>;
};

export function getClosePositionInstruction<
  TAccountOwner extends string,
  TAccountPosition extends string,
  TAccountPositionCollateralAccount extends string,
  TAccountPositionUsdcAccount extends string,
  TAccountPositionDestinationAccount extends string,
  TAccountObligation extends string,
  TAccountCollateralReserve extends string,
  TAccountCollateralTokenProgram extends string,
  TAccountBorrowTokenProgram extends string,
  TAccountDestinationTokenProgram extends string,
  TProgramAddress extends Address = typeof ACCRUE_PROGRAM_ADDRESS,
>(
  input: ClosePositionInput<
    TAccountOwner,
    TAccountPosition,
    TAccountPositionCollateralAccount,
    TAccountPositionUsdcAccount,
    TAccountPositionDestinationAccount,
    TAccountObligation,
    TAccountCollateralReserve,
    TAccountCollateralTokenProgram,
    TAccountBorrowTokenProgram,
    TAccountDestinationTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): ClosePositionInstruction<
  TProgramAddress,
  TAccountOwner,
  TAccountPosition,
  TAccountPositionCollateralAccount,
  TAccountPositionUsdcAccount,
  TAccountPositionDestinationAccount,
  TAccountObligation,
  TAccountCollateralReserve,
  TAccountCollateralTokenProgram,
  TAccountBorrowTokenProgram,
  TAccountDestinationTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? ACCRUE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    owner: { value: input.owner ?? null, isWritable: true },
    position: { value: input.position ?? null, isWritable: true },
    positionCollateralAccount: {
      value: input.positionCollateralAccount ?? null,
      isWritable: true,
    },
    positionUsdcAccount: {
      value: input.positionUsdcAccount ?? null,
      isWritable: true,
    },
    positionDestinationAccount: {
      value: input.positionDestinationAccount ?? null,
      isWritable: true,
    },
    obligation: { value: input.obligation ?? null, isWritable: false },
    collateralReserve: {
      value: input.collateralReserve ?? null,
      isWritable: false,
    },
    collateralTokenProgram: {
      value: input.collateralTokenProgram ?? null,
      isWritable: false,
    },
    borrowTokenProgram: {
      value: input.borrowTokenProgram ?? null,
      isWritable: false,
    },
    destinationTokenProgram: {
      value: input.destinationTokenProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.owner),
      getAccountMeta(accounts.position),
      getAccountMeta(accounts.positionCollateralAccount),
      getAccountMeta(accounts.positionUsdcAccount),
      getAccountMeta(accounts.positionDestinationAccount),
      getAccountMeta(accounts.obligation),
      getAccountMeta(accounts.collateralReserve),
      getAccountMeta(accounts.collateralTokenProgram),
      getAccountMeta(accounts.borrowTokenProgram),
      getAccountMeta(accounts.destinationTokenProgram),
    ],
    data: getClosePositionInstructionDataEncoder().encode({}),
    programAddress,
  } as ClosePositionInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountPosition,
    TAccountPositionCollateralAccount,
    TAccountPositionUsdcAccount,
    TAccountPositionDestinationAccount,
    TAccountObligation,
    TAccountCollateralReserve,
    TAccountCollateralTokenProgram,
    TAccountBorrowTokenProgram,
    TAccountDestinationTokenProgram
  >);
}

export type ParsedClosePositionInstruction<
  TProgram extends string = typeof ACCRUE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    owner: TAccountMetas[0];
    position: TAccountMetas[1];
    positionCollateralAccount: TAccountMetas[2];
    positionUsdcAccount: TAccountMetas[3];
    positionDestinationAccount: TAccountMetas[4];
    obligation: TAccountMetas[5];
    collateralReserve: TAccountMetas[6];
    collateralTokenProgram: TAccountMetas[7];
    borrowTokenProgram: TAccountMetas[8];
    destinationTokenProgram: TAccountMetas[9];
  };
  data: ClosePositionInstructionData;
};

export function parseClosePositionInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedClosePositionInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 10) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      owner: getNextAccount(),
      position: getNextAccount(),
      positionCollateralAccount: getNextAccount(),
      positionUsdcAccount: getNextAccount(),
      positionDestinationAccount: getNextAccount(),
      obligation: getNextAccount(),
      collateralReserve: getNextAccount(),
      collateralTokenProgram: getNextAccount(),
      borrowTokenProgram: getNextAccount(),
      destinationTokenProgram: getNextAccount(),
    },
    data: getClosePositionInstructionDataDecoder().decode(instruction.data),
  };
}
