/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { findConfigPda } from "../pdas/index.js";
import { ACCRUE_PROGRAM_ADDRESS } from "../programs/index.js";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared/index.js";
import {
  getConfigLimitsDecoder,
  getConfigLimitsEncoder,
  type ConfigLimits,
  type ConfigLimitsArgs,
} from "../types/index.js";

export const INITIALIZE_CONFIG_DISCRIMINATOR = new Uint8Array([
  208, 127, 21, 1, 194, 190, 196, 70,
]);

export function getInitializeConfigDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INITIALIZE_CONFIG_DISCRIMINATOR,
  );
}

export type InitializeConfigInstruction<
  TProgram extends string = typeof ACCRUE_PROGRAM_ADDRESS,
  TAccountDeployer extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountTreasury extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountDeployer extends string
        ? WritableSignerAccount<TAccountDeployer> &
            AccountSignerMeta<TAccountDeployer>
        : TAccountDeployer,
      TAccountConfig extends string
        ? WritableAccount<TAccountConfig>
        : TAccountConfig,
      TAccountTreasury extends string
        ? ReadonlyAccount<TAccountTreasury>
        : TAccountTreasury,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitializeConfigInstructionData = {
  discriminator: ReadonlyUint8Array;
  admin: Address;
  guardian: Address;
  borrowMint: Address;
  borrowReserve: Address;
  limits: ConfigLimits;
};

export type InitializeConfigInstructionDataArgs = {
  admin: Address;
  guardian: Address;
  borrowMint: Address;
  borrowReserve: Address;
  limits: ConfigLimitsArgs;
};

export function getInitializeConfigInstructionDataEncoder(): FixedSizeEncoder<InitializeConfigInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["admin", getAddressEncoder()],
      ["guardian", getAddressEncoder()],
      ["borrowMint", getAddressEncoder()],
      ["borrowReserve", getAddressEncoder()],
      ["limits", getConfigLimitsEncoder()],
    ]),
    (value) => ({ ...value, discriminator: INITIALIZE_CONFIG_DISCRIMINATOR }),
  );
}

export function getInitializeConfigInstructionDataDecoder(): FixedSizeDecoder<InitializeConfigInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["admin", getAddressDecoder()],
    ["guardian", getAddressDecoder()],
    ["borrowMint", getAddressDecoder()],
    ["borrowReserve", getAddressDecoder()],
    ["limits", getConfigLimitsDecoder()],
  ]);
}

export function getInitializeConfigInstructionDataCodec(): FixedSizeCodec<
  InitializeConfigInstructionDataArgs,
  InitializeConfigInstructionData
> {
  return combineCodec(
    getInitializeConfigInstructionDataEncoder(),
    getInitializeConfigInstructionDataDecoder(),
  );
}

export type InitializeConfigAsyncInput<
  TAccountDeployer extends string = string,
  TAccountConfig extends string = string,
  TAccountTreasury extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  deployer: TransactionSigner<TAccountDeployer>;
  config?: Address<TAccountConfig>;
  treasury: Address<TAccountTreasury>;
  systemProgram?: Address<TAccountSystemProgram>;
  admin: InitializeConfigInstructionDataArgs["admin"];
  guardian: InitializeConfigInstructionDataArgs["guardian"];
  borrowMint: InitializeConfigInstructionDataArgs["borrowMint"];
  borrowReserve: InitializeConfigInstructionDataArgs["borrowReserve"];
  limits: InitializeConfigInstructionDataArgs["limits"];
};

export async function getInitializeConfigInstructionAsync<
  TAccountDeployer extends string,
  TAccountConfig extends string,
  TAccountTreasury extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ACCRUE_PROGRAM_ADDRESS,
>(
  input: InitializeConfigAsyncInput<
    TAccountDeployer,
    TAccountConfig,
    TAccountTreasury,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  InitializeConfigInstruction<
    TProgramAddress,
    TAccountDeployer,
    TAccountConfig,
    TAccountTreasury,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ACCRUE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    deployer: { value: input.deployer ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: true },
    treasury: { value: input.treasury ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.deployer),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.treasury),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getInitializeConfigInstructionDataEncoder().encode(
      args as InitializeConfigInstructionDataArgs,
    ),
    programAddress,
  } as InitializeConfigInstruction<
    TProgramAddress,
    TAccountDeployer,
    TAccountConfig,
    TAccountTreasury,
    TAccountSystemProgram
  >);
}

export type InitializeConfigInput<
  TAccountDeployer extends string = string,
  TAccountConfig extends string = string,
  TAccountTreasury extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  deployer: TransactionSigner<TAccountDeployer>;
  config: Address<TAccountConfig>;
  treasury: Address<TAccountTreasury>;
  systemProgram?: Address<TAccountSystemProgram>;
  admin: InitializeConfigInstructionDataArgs["admin"];
  guardian: InitializeConfigInstructionDataArgs["guardian"];
  borrowMint: InitializeConfigInstructionDataArgs["borrowMint"];
  borrowReserve: InitializeConfigInstructionDataArgs["borrowReserve"];
  limits: InitializeConfigInstructionDataArgs["limits"];
};

export function getInitializeConfigInstruction<
  TAccountDeployer extends string,
  TAccountConfig extends string,
  TAccountTreasury extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ACCRUE_PROGRAM_ADDRESS,
>(
  input: InitializeConfigInput<
    TAccountDeployer,
    TAccountConfig,
    TAccountTreasury,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): InitializeConfigInstruction<
  TProgramAddress,
  TAccountDeployer,
  TAccountConfig,
  TAccountTreasury,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? ACCRUE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    deployer: { value: input.deployer ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: true },
    treasury: { value: input.treasury ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.deployer),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.treasury),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getInitializeConfigInstructionDataEncoder().encode(
      args as InitializeConfigInstructionDataArgs,
    ),
    programAddress,
  } as InitializeConfigInstruction<
    TProgramAddress,
    TAccountDeployer,
    TAccountConfig,
    TAccountTreasury,
    TAccountSystemProgram
  >);
}

export type ParsedInitializeConfigInstruction<
  TProgram extends string = typeof ACCRUE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    deployer: TAccountMetas[0];
    config: TAccountMetas[1];
    treasury: TAccountMetas[2];
    systemProgram: TAccountMetas[3];
  };
  data: InitializeConfigInstructionData;
};

export function parseInitializeConfigInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedInitializeConfigInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      deployer: getNextAccount(),
      config: getNextAccount(),
      treasury: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitializeConfigInstructionDataDecoder().decode(instruction.data),
  };
}
