import { JUPITER_V6_PROGRAM_ADDRESS, KAMINO_FARMS_PROGRAM_ADDRESS, KAMINO_LENDING_PROGRAM_ADDRESS } from "../../programIds.js";
/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { findConfigPda } from "../pdas/index.js";
import { ACCRUE_PROGRAM_ADDRESS } from "../programs/index.js";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared/index.js";

export const LEAVE_DISCRIMINATOR = new Uint8Array([
  59, 234, 148, 108, 107, 149, 173, 112,
]);

export function getLeaveDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(LEAVE_DISCRIMINATOR);
}

export type LeaveInstruction<
  TProgram extends string = typeof ACCRUE_PROGRAM_ADDRESS,
  TAccountCaller extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountPosition extends string | AccountMeta<string> = string,
  TAccountCollateralMint extends string | AccountMeta<string> = string,
  TAccountDestinationMint extends string | AccountMeta<string> = string,
  TAccountBorrowMint extends string | AccountMeta<string> = string,
  TAccountPositionCollateralAccount extends string | AccountMeta<string> =
    string,
  TAccountPositionUsdcAccount extends string | AccountMeta<string> = string,
  TAccountPositionDestinationAccount extends string | AccountMeta<string> =
    string,
  TAccountOwnerCollateralAccount extends string | AccountMeta<string> = string,
  TAccountOwnerUsdcAccount extends string | AccountMeta<string> = string,
  TAccountOwnerDestinationAccount extends string | AccountMeta<string> = string,
  TAccountOwner extends string | AccountMeta<string> = string,
  TAccountObligation extends string | AccountMeta<string> = string,
  TAccountLendingMarket extends string | AccountMeta<string> = string,
  TAccountLendingMarketAuthority extends string | AccountMeta<string> = string,
  TAccountCollateralReserve extends string | AccountMeta<string> = string,
  TAccountCollateralReserveCollateralSupply extends
    string | AccountMeta<string> = string,
  TAccountCollateralReserveCollateralMint extends string | AccountMeta<string> =
    string,
  TAccountCollateralReserveLiquiditySupply extends
    string | AccountMeta<string> = string,
  TAccountBorrowReserve extends string | AccountMeta<string> = string,
  TAccountBorrowReserveLiquiditySupply extends string | AccountMeta<string> =
    string,
  TAccountCollateralReserveFarmState extends string | AccountMeta<string> =
    string,
  TAccountCollateralObligationFarmState extends string | AccountMeta<string> =
    string,
  TAccountBorrowReserveFarmState extends string | AccountMeta<string> = string,
  TAccountBorrowObligationFarmState extends string | AccountMeta<string> =
    string,
  TAccountCollateralScopePrices extends string | AccountMeta<string> = string,
  TAccountBorrowScopePrices extends string | AccountMeta<string> = string,
  TAccountDestinationScopePrices extends string | AccountMeta<string> = string,
  TAccountFarmsProgram extends string | AccountMeta<string> =
    "FarmsPZpWu9i7Kky8tPN37rs2TpmMrAZrC7S7vJa91Hr",
  TAccountSwapProgram extends string | AccountMeta<string> =
    "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4",
  TAccountKaminoProgram extends string | AccountMeta<string> =
    "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD",
  TAccountInstructionSysvar extends string | AccountMeta<string> =
    "Sysvar1nstructions1111111111111111111111111",
  TAccountKaminoCollateralTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountCollateralTokenProgram extends string | AccountMeta<string> = string,
  TAccountBorrowTokenProgram extends string | AccountMeta<string> = string,
  TAccountDestinationTokenProgram extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountCaller extends string
        ? WritableSignerAccount<TAccountCaller> &
            AccountSignerMeta<TAccountCaller>
        : TAccountCaller,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountPosition extends string
        ? WritableAccount<TAccountPosition>
        : TAccountPosition,
      TAccountCollateralMint extends string
        ? ReadonlyAccount<TAccountCollateralMint>
        : TAccountCollateralMint,
      TAccountDestinationMint extends string
        ? ReadonlyAccount<TAccountDestinationMint>
        : TAccountDestinationMint,
      TAccountBorrowMint extends string
        ? ReadonlyAccount<TAccountBorrowMint>
        : TAccountBorrowMint,
      TAccountPositionCollateralAccount extends string
        ? WritableAccount<TAccountPositionCollateralAccount>
        : TAccountPositionCollateralAccount,
      TAccountPositionUsdcAccount extends string
        ? WritableAccount<TAccountPositionUsdcAccount>
        : TAccountPositionUsdcAccount,
      TAccountPositionDestinationAccount extends string
        ? WritableAccount<TAccountPositionDestinationAccount>
        : TAccountPositionDestinationAccount,
      TAccountOwnerCollateralAccount extends string
        ? WritableAccount<TAccountOwnerCollateralAccount>
        : TAccountOwnerCollateralAccount,
      TAccountOwnerUsdcAccount extends string
        ? WritableAccount<TAccountOwnerUsdcAccount>
        : TAccountOwnerUsdcAccount,
      TAccountOwnerDestinationAccount extends string
        ? WritableAccount<TAccountOwnerDestinationAccount>
        : TAccountOwnerDestinationAccount,
      TAccountOwner extends string
        ? ReadonlyAccount<TAccountOwner>
        : TAccountOwner,
      TAccountObligation extends string
        ? WritableAccount<TAccountObligation>
        : TAccountObligation,
      TAccountLendingMarket extends string
        ? WritableAccount<TAccountLendingMarket>
        : TAccountLendingMarket,
      TAccountLendingMarketAuthority extends string
        ? ReadonlyAccount<TAccountLendingMarketAuthority>
        : TAccountLendingMarketAuthority,
      TAccountCollateralReserve extends string
        ? WritableAccount<TAccountCollateralReserve>
        : TAccountCollateralReserve,
      TAccountCollateralReserveCollateralSupply extends string
        ? WritableAccount<TAccountCollateralReserveCollateralSupply>
        : TAccountCollateralReserveCollateralSupply,
      TAccountCollateralReserveCollateralMint extends string
        ? WritableAccount<TAccountCollateralReserveCollateralMint>
        : TAccountCollateralReserveCollateralMint,
      TAccountCollateralReserveLiquiditySupply extends string
        ? WritableAccount<TAccountCollateralReserveLiquiditySupply>
        : TAccountCollateralReserveLiquiditySupply,
      TAccountBorrowReserve extends string
        ? WritableAccount<TAccountBorrowReserve>
        : TAccountBorrowReserve,
      TAccountBorrowReserveLiquiditySupply extends string
        ? WritableAccount<TAccountBorrowReserveLiquiditySupply>
        : TAccountBorrowReserveLiquiditySupply,
      TAccountCollateralReserveFarmState extends string
        ? WritableAccount<TAccountCollateralReserveFarmState>
        : TAccountCollateralReserveFarmState,
      TAccountCollateralObligationFarmState extends string
        ? WritableAccount<TAccountCollateralObligationFarmState>
        : TAccountCollateralObligationFarmState,
      TAccountBorrowReserveFarmState extends string
        ? WritableAccount<TAccountBorrowReserveFarmState>
        : TAccountBorrowReserveFarmState,
      TAccountBorrowObligationFarmState extends string
        ? WritableAccount<TAccountBorrowObligationFarmState>
        : TAccountBorrowObligationFarmState,
      TAccountCollateralScopePrices extends string
        ? ReadonlyAccount<TAccountCollateralScopePrices>
        : TAccountCollateralScopePrices,
      TAccountBorrowScopePrices extends string
        ? ReadonlyAccount<TAccountBorrowScopePrices>
        : TAccountBorrowScopePrices,
      TAccountDestinationScopePrices extends string
        ? ReadonlyAccount<TAccountDestinationScopePrices>
        : TAccountDestinationScopePrices,
      TAccountFarmsProgram extends string
        ? ReadonlyAccount<TAccountFarmsProgram>
        : TAccountFarmsProgram,
      TAccountSwapProgram extends string
        ? ReadonlyAccount<TAccountSwapProgram>
        : TAccountSwapProgram,
      TAccountKaminoProgram extends string
        ? ReadonlyAccount<TAccountKaminoProgram>
        : TAccountKaminoProgram,
      TAccountInstructionSysvar extends string
        ? ReadonlyAccount<TAccountInstructionSysvar>
        : TAccountInstructionSysvar,
      TAccountKaminoCollateralTokenProgram extends string
        ? ReadonlyAccount<TAccountKaminoCollateralTokenProgram>
        : TAccountKaminoCollateralTokenProgram,
      TAccountCollateralTokenProgram extends string
        ? ReadonlyAccount<TAccountCollateralTokenProgram>
        : TAccountCollateralTokenProgram,
      TAccountBorrowTokenProgram extends string
        ? ReadonlyAccount<TAccountBorrowTokenProgram>
        : TAccountBorrowTokenProgram,
      TAccountDestinationTokenProgram extends string
        ? ReadonlyAccount<TAccountDestinationTokenProgram>
        : TAccountDestinationTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type LeaveInstructionData = {
  discriminator: ReadonlyUint8Array;
  jupiterRouteData: ReadonlyUint8Array;
};

export type LeaveInstructionDataArgs = { jupiterRouteData: ReadonlyUint8Array };

export function getLeaveInstructionDataEncoder(): Encoder<LeaveInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      [
        "jupiterRouteData",
        addEncoderSizePrefix(getBytesEncoder(), getU32Encoder()),
      ],
    ]),
    (value) => ({ ...value, discriminator: LEAVE_DISCRIMINATOR }),
  );
}

export function getLeaveInstructionDataDecoder(): Decoder<LeaveInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    [
      "jupiterRouteData",
      addDecoderSizePrefix(getBytesDecoder(), getU32Decoder()),
    ],
  ]);
}

export function getLeaveInstructionDataCodec(): Codec<
  LeaveInstructionDataArgs,
  LeaveInstructionData
> {
  return combineCodec(
    getLeaveInstructionDataEncoder(),
    getLeaveInstructionDataDecoder(),
  );
}

export type LeaveAsyncInput<
  TAccountCaller extends string = string,
  TAccountConfig extends string = string,
  TAccountPosition extends string = string,
  TAccountCollateralMint extends string = string,
  TAccountDestinationMint extends string = string,
  TAccountBorrowMint extends string = string,
  TAccountPositionCollateralAccount extends string = string,
  TAccountPositionUsdcAccount extends string = string,
  TAccountPositionDestinationAccount extends string = string,
  TAccountOwnerCollateralAccount extends string = string,
  TAccountOwnerUsdcAccount extends string = string,
  TAccountOwnerDestinationAccount extends string = string,
  TAccountOwner extends string = string,
  TAccountObligation extends string = string,
  TAccountLendingMarket extends string = string,
  TAccountLendingMarketAuthority extends string = string,
  TAccountCollateralReserve extends string = string,
  TAccountCollateralReserveCollateralSupply extends string = string,
  TAccountCollateralReserveCollateralMint extends string = string,
  TAccountCollateralReserveLiquiditySupply extends string = string,
  TAccountBorrowReserve extends string = string,
  TAccountBorrowReserveLiquiditySupply extends string = string,
  TAccountCollateralReserveFarmState extends string = string,
  TAccountCollateralObligationFarmState extends string = string,
  TAccountBorrowReserveFarmState extends string = string,
  TAccountBorrowObligationFarmState extends string = string,
  TAccountCollateralScopePrices extends string = string,
  TAccountBorrowScopePrices extends string = string,
  TAccountDestinationScopePrices extends string = string,
  TAccountFarmsProgram extends string = string,
  TAccountSwapProgram extends string = string,
  TAccountKaminoProgram extends string = string,
  TAccountInstructionSysvar extends string = string,
  TAccountKaminoCollateralTokenProgram extends string = string,
  TAccountCollateralTokenProgram extends string = string,
  TAccountBorrowTokenProgram extends string = string,
  TAccountDestinationTokenProgram extends string = string,
> = {
  caller: TransactionSigner<TAccountCaller>;
  config?: Address<TAccountConfig>;
  position: Address<TAccountPosition>;
  collateralMint: Address<TAccountCollateralMint>;
  destinationMint: Address<TAccountDestinationMint>;
  borrowMint: Address<TAccountBorrowMint>;
  positionCollateralAccount: Address<TAccountPositionCollateralAccount>;
  positionUsdcAccount: Address<TAccountPositionUsdcAccount>;
  positionDestinationAccount: Address<TAccountPositionDestinationAccount>;
  ownerCollateralAccount?: Address<TAccountOwnerCollateralAccount>;
  ownerUsdcAccount?: Address<TAccountOwnerUsdcAccount>;
  ownerDestinationAccount?: Address<TAccountOwnerDestinationAccount>;
  owner: Address<TAccountOwner>;
  obligation: Address<TAccountObligation>;
  lendingMarket: Address<TAccountLendingMarket>;
  lendingMarketAuthority: Address<TAccountLendingMarketAuthority>;
  collateralReserve: Address<TAccountCollateralReserve>;
  collateralReserveCollateralSupply: Address<TAccountCollateralReserveCollateralSupply>;
  collateralReserveCollateralMint: Address<TAccountCollateralReserveCollateralMint>;
  collateralReserveLiquiditySupply: Address<TAccountCollateralReserveLiquiditySupply>;
  borrowReserve: Address<TAccountBorrowReserve>;
  borrowReserveLiquiditySupply: Address<TAccountBorrowReserveLiquiditySupply>;
  collateralReserveFarmState?: Address<TAccountCollateralReserveFarmState>;
  collateralObligationFarmState?: Address<TAccountCollateralObligationFarmState>;
  borrowReserveFarmState?: Address<TAccountBorrowReserveFarmState>;
  borrowObligationFarmState?: Address<TAccountBorrowObligationFarmState>;
  collateralScopePrices: Address<TAccountCollateralScopePrices>;
  borrowScopePrices: Address<TAccountBorrowScopePrices>;
  destinationScopePrices: Address<TAccountDestinationScopePrices>;
  farmsProgram?: Address<TAccountFarmsProgram>;
  swapProgram?: Address<TAccountSwapProgram>;
  kaminoProgram?: Address<TAccountKaminoProgram>;
  instructionSysvar?: Address<TAccountInstructionSysvar>;
  kaminoCollateralTokenProgram?: Address<TAccountKaminoCollateralTokenProgram>;
  collateralTokenProgram: Address<TAccountCollateralTokenProgram>;
  borrowTokenProgram: Address<TAccountBorrowTokenProgram>;
  destinationTokenProgram: Address<TAccountDestinationTokenProgram>;
  jupiterRouteData: LeaveInstructionDataArgs["jupiterRouteData"];
};

export async function getLeaveInstructionAsync<
  TAccountCaller extends string,
  TAccountConfig extends string,
  TAccountPosition extends string,
  TAccountCollateralMint extends string,
  TAccountDestinationMint extends string,
  TAccountBorrowMint extends string,
  TAccountPositionCollateralAccount extends string,
  TAccountPositionUsdcAccount extends string,
  TAccountPositionDestinationAccount extends string,
  TAccountOwnerCollateralAccount extends string,
  TAccountOwnerUsdcAccount extends string,
  TAccountOwnerDestinationAccount extends string,
  TAccountOwner extends string,
  TAccountObligation extends string,
  TAccountLendingMarket extends string,
  TAccountLendingMarketAuthority extends string,
  TAccountCollateralReserve extends string,
  TAccountCollateralReserveCollateralSupply extends string,
  TAccountCollateralReserveCollateralMint extends string,
  TAccountCollateralReserveLiquiditySupply extends string,
  TAccountBorrowReserve extends string,
  TAccountBorrowReserveLiquiditySupply extends string,
  TAccountCollateralReserveFarmState extends string,
  TAccountCollateralObligationFarmState extends string,
  TAccountBorrowReserveFarmState extends string,
  TAccountBorrowObligationFarmState extends string,
  TAccountCollateralScopePrices extends string,
  TAccountBorrowScopePrices extends string,
  TAccountDestinationScopePrices extends string,
  TAccountFarmsProgram extends string,
  TAccountSwapProgram extends string,
  TAccountKaminoProgram extends string,
  TAccountInstructionSysvar extends string,
  TAccountKaminoCollateralTokenProgram extends string,
  TAccountCollateralTokenProgram extends string,
  TAccountBorrowTokenProgram extends string,
  TAccountDestinationTokenProgram extends string,
  TProgramAddress extends Address = typeof ACCRUE_PROGRAM_ADDRESS,
>(
  input: LeaveAsyncInput<
    TAccountCaller,
    TAccountConfig,
    TAccountPosition,
    TAccountCollateralMint,
    TAccountDestinationMint,
    TAccountBorrowMint,
    TAccountPositionCollateralAccount,
    TAccountPositionUsdcAccount,
    TAccountPositionDestinationAccount,
    TAccountOwnerCollateralAccount,
    TAccountOwnerUsdcAccount,
    TAccountOwnerDestinationAccount,
    TAccountOwner,
    TAccountObligation,
    TAccountLendingMarket,
    TAccountLendingMarketAuthority,
    TAccountCollateralReserve,
    TAccountCollateralReserveCollateralSupply,
    TAccountCollateralReserveCollateralMint,
    TAccountCollateralReserveLiquiditySupply,
    TAccountBorrowReserve,
    TAccountBorrowReserveLiquiditySupply,
    TAccountCollateralReserveFarmState,
    TAccountCollateralObligationFarmState,
    TAccountBorrowReserveFarmState,
    TAccountBorrowObligationFarmState,
    TAccountCollateralScopePrices,
    TAccountBorrowScopePrices,
    TAccountDestinationScopePrices,
    TAccountFarmsProgram,
    TAccountSwapProgram,
    TAccountKaminoProgram,
    TAccountInstructionSysvar,
    TAccountKaminoCollateralTokenProgram,
    TAccountCollateralTokenProgram,
    TAccountBorrowTokenProgram,
    TAccountDestinationTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  LeaveInstruction<
    TProgramAddress,
    TAccountCaller,
    TAccountConfig,
    TAccountPosition,
    TAccountCollateralMint,
    TAccountDestinationMint,
    TAccountBorrowMint,
    TAccountPositionCollateralAccount,
    TAccountPositionUsdcAccount,
    TAccountPositionDestinationAccount,
    TAccountOwnerCollateralAccount,
    TAccountOwnerUsdcAccount,
    TAccountOwnerDestinationAccount,
    TAccountOwner,
    TAccountObligation,
    TAccountLendingMarket,
    TAccountLendingMarketAuthority,
    TAccountCollateralReserve,
    TAccountCollateralReserveCollateralSupply,
    TAccountCollateralReserveCollateralMint,
    TAccountCollateralReserveLiquiditySupply,
    TAccountBorrowReserve,
    TAccountBorrowReserveLiquiditySupply,
    TAccountCollateralReserveFarmState,
    TAccountCollateralObligationFarmState,
    TAccountBorrowReserveFarmState,
    TAccountBorrowObligationFarmState,
    TAccountCollateralScopePrices,
    TAccountBorrowScopePrices,
    TAccountDestinationScopePrices,
    TAccountFarmsProgram,
    TAccountSwapProgram,
    TAccountKaminoProgram,
    TAccountInstructionSysvar,
    TAccountKaminoCollateralTokenProgram,
    TAccountCollateralTokenProgram,
    TAccountBorrowTokenProgram,
    TAccountDestinationTokenProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ACCRUE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    caller: { value: input.caller ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    position: { value: input.position ?? null, isWritable: true },
    collateralMint: { value: input.collateralMint ?? null, isWritable: false },
    destinationMint: {
      value: input.destinationMint ?? null,
      isWritable: false,
    },
    borrowMint: { value: input.borrowMint ?? null, isWritable: false },
    positionCollateralAccount: {
      value: input.positionCollateralAccount ?? null,
      isWritable: true,
    },
    positionUsdcAccount: {
      value: input.positionUsdcAccount ?? null,
      isWritable: true,
    },
    positionDestinationAccount: {
      value: input.positionDestinationAccount ?? null,
      isWritable: true,
    },
    ownerCollateralAccount: {
      value: input.ownerCollateralAccount ?? null,
      isWritable: true,
    },
    ownerUsdcAccount: {
      value: input.ownerUsdcAccount ?? null,
      isWritable: true,
    },
    ownerDestinationAccount: {
      value: input.ownerDestinationAccount ?? null,
      isWritable: true,
    },
    owner: { value: input.owner ?? null, isWritable: false },
    obligation: { value: input.obligation ?? null, isWritable: true },
    lendingMarket: { value: input.lendingMarket ?? null, isWritable: true },
    lendingMarketAuthority: {
      value: input.lendingMarketAuthority ?? null,
      isWritable: false,
    },
    collateralReserve: {
      value: input.collateralReserve ?? null,
      isWritable: true,
    },
    collateralReserveCollateralSupply: {
      value: input.collateralReserveCollateralSupply ?? null,
      isWritable: true,
    },
    collateralReserveCollateralMint: {
      value: input.collateralReserveCollateralMint ?? null,
      isWritable: true,
    },
    collateralReserveLiquiditySupply: {
      value: input.collateralReserveLiquiditySupply ?? null,
      isWritable: true,
    },
    borrowReserve: { value: input.borrowReserve ?? null, isWritable: true },
    borrowReserveLiquiditySupply: {
      value: input.borrowReserveLiquiditySupply ?? null,
      isWritable: true,
    },
    collateralReserveFarmState: {
      value: input.collateralReserveFarmState ?? null,
      isWritable: true,
    },
    collateralObligationFarmState: {
      value: input.collateralObligationFarmState ?? null,
      isWritable: true,
    },
    borrowReserveFarmState: {
      value: input.borrowReserveFarmState ?? null,
      isWritable: true,
    },
    borrowObligationFarmState: {
      value: input.borrowObligationFarmState ?? null,
      isWritable: true,
    },
    collateralScopePrices: {
      value: input.collateralScopePrices ?? null,
      isWritable: false,
    },
    borrowScopePrices: {
      value: input.borrowScopePrices ?? null,
      isWritable: false,
    },
    destinationScopePrices: {
      value: input.destinationScopePrices ?? null,
      isWritable: false,
    },
    farmsProgram: { value: input.farmsProgram ?? null, isWritable: false },
    swapProgram: { value: input.swapProgram ?? null, isWritable: false },
    kaminoProgram: { value: input.kaminoProgram ?? null, isWritable: false },
    instructionSysvar: {
      value: input.instructionSysvar ?? null,
      isWritable: false,
    },
    kaminoCollateralTokenProgram: {
      value: input.kaminoCollateralTokenProgram ?? null,
      isWritable: false,
    },
    collateralTokenProgram: {
      value: input.collateralTokenProgram ?? null,
      isWritable: false,
    },
    borrowTokenProgram: {
      value: input.borrowTokenProgram ?? null,
      isWritable: false,
    },
    destinationTokenProgram: {
      value: input.destinationTokenProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.ownerCollateralAccount.value) {
    accounts.ownerCollateralAccount.value = await getProgramDerivedAddress({
      programAddress:
        "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.owner.value)),
        getAddressEncoder().encode(
          expectAddress(accounts.collateralTokenProgram.value),
        ),
        getAddressEncoder().encode(
          expectAddress(accounts.collateralMint.value),
        ),
      ],
    });
  }
  if (!accounts.ownerUsdcAccount.value) {
    accounts.ownerUsdcAccount.value = await getProgramDerivedAddress({
      programAddress:
        "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.owner.value)),
        getAddressEncoder().encode(
          expectAddress(accounts.borrowTokenProgram.value),
        ),
        getAddressEncoder().encode(expectAddress(accounts.borrowMint.value)),
      ],
    });
  }
  if (!accounts.ownerDestinationAccount.value) {
    accounts.ownerDestinationAccount.value = await getProgramDerivedAddress({
      programAddress:
        "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.owner.value)),
        getAddressEncoder().encode(
          expectAddress(accounts.destinationTokenProgram.value),
        ),
        getAddressEncoder().encode(
          expectAddress(accounts.destinationMint.value),
        ),
      ],
    });
  }
  if (!accounts.farmsProgram.value) {
    accounts.farmsProgram.value =
      (KAMINO_FARMS_PROGRAM_ADDRESS as Address<"FarmsPZpWu9i7Kky8tPN37rs2TpmMrAZrC7S7vJa91Hr">);
  }
  if (!accounts.swapProgram.value) {
    accounts.swapProgram.value =
      (JUPITER_V6_PROGRAM_ADDRESS as Address<"JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4">);
  }
  if (!accounts.kaminoProgram.value) {
    accounts.kaminoProgram.value =
      (KAMINO_LENDING_PROGRAM_ADDRESS as Address<"KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD">);
  }
  if (!accounts.instructionSysvar.value) {
    accounts.instructionSysvar.value =
      "Sysvar1nstructions1111111111111111111111111" as Address<"Sysvar1nstructions1111111111111111111111111">;
  }
  if (!accounts.kaminoCollateralTokenProgram.value) {
    accounts.kaminoCollateralTokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.caller),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.position),
      getAccountMeta(accounts.collateralMint),
      getAccountMeta(accounts.destinationMint),
      getAccountMeta(accounts.borrowMint),
      getAccountMeta(accounts.positionCollateralAccount),
      getAccountMeta(accounts.positionUsdcAccount),
      getAccountMeta(accounts.positionDestinationAccount),
      getAccountMeta(accounts.ownerCollateralAccount),
      getAccountMeta(accounts.ownerUsdcAccount),
      getAccountMeta(accounts.ownerDestinationAccount),
      getAccountMeta(accounts.owner),
      getAccountMeta(accounts.obligation),
      getAccountMeta(accounts.lendingMarket),
      getAccountMeta(accounts.lendingMarketAuthority),
      getAccountMeta(accounts.collateralReserve),
      getAccountMeta(accounts.collateralReserveCollateralSupply),
      getAccountMeta(accounts.collateralReserveCollateralMint),
      getAccountMeta(accounts.collateralReserveLiquiditySupply),
      getAccountMeta(accounts.borrowReserve),
      getAccountMeta(accounts.borrowReserveLiquiditySupply),
      getAccountMeta(accounts.collateralReserveFarmState),
      getAccountMeta(accounts.collateralObligationFarmState),
      getAccountMeta(accounts.borrowReserveFarmState),
      getAccountMeta(accounts.borrowObligationFarmState),
      getAccountMeta(accounts.collateralScopePrices),
      getAccountMeta(accounts.borrowScopePrices),
      getAccountMeta(accounts.destinationScopePrices),
      getAccountMeta(accounts.farmsProgram),
      getAccountMeta(accounts.swapProgram),
      getAccountMeta(accounts.kaminoProgram),
      getAccountMeta(accounts.instructionSysvar),
      getAccountMeta(accounts.kaminoCollateralTokenProgram),
      getAccountMeta(accounts.collateralTokenProgram),
      getAccountMeta(accounts.borrowTokenProgram),
      getAccountMeta(accounts.destinationTokenProgram),
    ],
    data: getLeaveInstructionDataEncoder().encode(
      args as LeaveInstructionDataArgs,
    ),
    programAddress,
  } as LeaveInstruction<
    TProgramAddress,
    TAccountCaller,
    TAccountConfig,
    TAccountPosition,
    TAccountCollateralMint,
    TAccountDestinationMint,
    TAccountBorrowMint,
    TAccountPositionCollateralAccount,
    TAccountPositionUsdcAccount,
    TAccountPositionDestinationAccount,
    TAccountOwnerCollateralAccount,
    TAccountOwnerUsdcAccount,
    TAccountOwnerDestinationAccount,
    TAccountOwner,
    TAccountObligation,
    TAccountLendingMarket,
    TAccountLendingMarketAuthority,
    TAccountCollateralReserve,
    TAccountCollateralReserveCollateralSupply,
    TAccountCollateralReserveCollateralMint,
    TAccountCollateralReserveLiquiditySupply,
    TAccountBorrowReserve,
    TAccountBorrowReserveLiquiditySupply,
    TAccountCollateralReserveFarmState,
    TAccountCollateralObligationFarmState,
    TAccountBorrowReserveFarmState,
    TAccountBorrowObligationFarmState,
    TAccountCollateralScopePrices,
    TAccountBorrowScopePrices,
    TAccountDestinationScopePrices,
    TAccountFarmsProgram,
    TAccountSwapProgram,
    TAccountKaminoProgram,
    TAccountInstructionSysvar,
    TAccountKaminoCollateralTokenProgram,
    TAccountCollateralTokenProgram,
    TAccountBorrowTokenProgram,
    TAccountDestinationTokenProgram
  >);
}

export type LeaveInput<
  TAccountCaller extends string = string,
  TAccountConfig extends string = string,
  TAccountPosition extends string = string,
  TAccountCollateralMint extends string = string,
  TAccountDestinationMint extends string = string,
  TAccountBorrowMint extends string = string,
  TAccountPositionCollateralAccount extends string = string,
  TAccountPositionUsdcAccount extends string = string,
  TAccountPositionDestinationAccount extends string = string,
  TAccountOwnerCollateralAccount extends string = string,
  TAccountOwnerUsdcAccount extends string = string,
  TAccountOwnerDestinationAccount extends string = string,
  TAccountOwner extends string = string,
  TAccountObligation extends string = string,
  TAccountLendingMarket extends string = string,
  TAccountLendingMarketAuthority extends string = string,
  TAccountCollateralReserve extends string = string,
  TAccountCollateralReserveCollateralSupply extends string = string,
  TAccountCollateralReserveCollateralMint extends string = string,
  TAccountCollateralReserveLiquiditySupply extends string = string,
  TAccountBorrowReserve extends string = string,
  TAccountBorrowReserveLiquiditySupply extends string = string,
  TAccountCollateralReserveFarmState extends string = string,
  TAccountCollateralObligationFarmState extends string = string,
  TAccountBorrowReserveFarmState extends string = string,
  TAccountBorrowObligationFarmState extends string = string,
  TAccountCollateralScopePrices extends string = string,
  TAccountBorrowScopePrices extends string = string,
  TAccountDestinationScopePrices extends string = string,
  TAccountFarmsProgram extends string = string,
  TAccountSwapProgram extends string = string,
  TAccountKaminoProgram extends string = string,
  TAccountInstructionSysvar extends string = string,
  TAccountKaminoCollateralTokenProgram extends string = string,
  TAccountCollateralTokenProgram extends string = string,
  TAccountBorrowTokenProgram extends string = string,
  TAccountDestinationTokenProgram extends string = string,
> = {
  caller: TransactionSigner<TAccountCaller>;
  config: Address<TAccountConfig>;
  position: Address<TAccountPosition>;
  collateralMint: Address<TAccountCollateralMint>;
  destinationMint: Address<TAccountDestinationMint>;
  borrowMint: Address<TAccountBorrowMint>;
  positionCollateralAccount: Address<TAccountPositionCollateralAccount>;
  positionUsdcAccount: Address<TAccountPositionUsdcAccount>;
  positionDestinationAccount: Address<TAccountPositionDestinationAccount>;
  ownerCollateralAccount: Address<TAccountOwnerCollateralAccount>;
  ownerUsdcAccount: Address<TAccountOwnerUsdcAccount>;
  ownerDestinationAccount: Address<TAccountOwnerDestinationAccount>;
  owner: Address<TAccountOwner>;
  obligation: Address<TAccountObligation>;
  lendingMarket: Address<TAccountLendingMarket>;
  lendingMarketAuthority: Address<TAccountLendingMarketAuthority>;
  collateralReserve: Address<TAccountCollateralReserve>;
  collateralReserveCollateralSupply: Address<TAccountCollateralReserveCollateralSupply>;
  collateralReserveCollateralMint: Address<TAccountCollateralReserveCollateralMint>;
  collateralReserveLiquiditySupply: Address<TAccountCollateralReserveLiquiditySupply>;
  borrowReserve: Address<TAccountBorrowReserve>;
  borrowReserveLiquiditySupply: Address<TAccountBorrowReserveLiquiditySupply>;
  collateralReserveFarmState?: Address<TAccountCollateralReserveFarmState>;
  collateralObligationFarmState?: Address<TAccountCollateralObligationFarmState>;
  borrowReserveFarmState?: Address<TAccountBorrowReserveFarmState>;
  borrowObligationFarmState?: Address<TAccountBorrowObligationFarmState>;
  collateralScopePrices: Address<TAccountCollateralScopePrices>;
  borrowScopePrices: Address<TAccountBorrowScopePrices>;
  destinationScopePrices: Address<TAccountDestinationScopePrices>;
  farmsProgram?: Address<TAccountFarmsProgram>;
  swapProgram?: Address<TAccountSwapProgram>;
  kaminoProgram?: Address<TAccountKaminoProgram>;
  instructionSysvar?: Address<TAccountInstructionSysvar>;
  kaminoCollateralTokenProgram?: Address<TAccountKaminoCollateralTokenProgram>;
  collateralTokenProgram: Address<TAccountCollateralTokenProgram>;
  borrowTokenProgram: Address<TAccountBorrowTokenProgram>;
  destinationTokenProgram: Address<TAccountDestinationTokenProgram>;
  jupiterRouteData: LeaveInstructionDataArgs["jupiterRouteData"];
};

export function getLeaveInstruction<
  TAccountCaller extends string,
  TAccountConfig extends string,
  TAccountPosition extends string,
  TAccountCollateralMint extends string,
  TAccountDestinationMint extends string,
  TAccountBorrowMint extends string,
  TAccountPositionCollateralAccount extends string,
  TAccountPositionUsdcAccount extends string,
  TAccountPositionDestinationAccount extends string,
  TAccountOwnerCollateralAccount extends string,
  TAccountOwnerUsdcAccount extends string,
  TAccountOwnerDestinationAccount extends string,
  TAccountOwner extends string,
  TAccountObligation extends string,
  TAccountLendingMarket extends string,
  TAccountLendingMarketAuthority extends string,
  TAccountCollateralReserve extends string,
  TAccountCollateralReserveCollateralSupply extends string,
  TAccountCollateralReserveCollateralMint extends string,
  TAccountCollateralReserveLiquiditySupply extends string,
  TAccountBorrowReserve extends string,
  TAccountBorrowReserveLiquiditySupply extends string,
  TAccountCollateralReserveFarmState extends string,
  TAccountCollateralObligationFarmState extends string,
  TAccountBorrowReserveFarmState extends string,
  TAccountBorrowObligationFarmState extends string,
  TAccountCollateralScopePrices extends string,
  TAccountBorrowScopePrices extends string,
  TAccountDestinationScopePrices extends string,
  TAccountFarmsProgram extends string,
  TAccountSwapProgram extends string,
  TAccountKaminoProgram extends string,
  TAccountInstructionSysvar extends string,
  TAccountKaminoCollateralTokenProgram extends string,
  TAccountCollateralTokenProgram extends string,
  TAccountBorrowTokenProgram extends string,
  TAccountDestinationTokenProgram extends string,
  TProgramAddress extends Address = typeof ACCRUE_PROGRAM_ADDRESS,
>(
  input: LeaveInput<
    TAccountCaller,
    TAccountConfig,
    TAccountPosition,
    TAccountCollateralMint,
    TAccountDestinationMint,
    TAccountBorrowMint,
    TAccountPositionCollateralAccount,
    TAccountPositionUsdcAccount,
    TAccountPositionDestinationAccount,
    TAccountOwnerCollateralAccount,
    TAccountOwnerUsdcAccount,
    TAccountOwnerDestinationAccount,
    TAccountOwner,
    TAccountObligation,
    TAccountLendingMarket,
    TAccountLendingMarketAuthority,
    TAccountCollateralReserve,
    TAccountCollateralReserveCollateralSupply,
    TAccountCollateralReserveCollateralMint,
    TAccountCollateralReserveLiquiditySupply,
    TAccountBorrowReserve,
    TAccountBorrowReserveLiquiditySupply,
    TAccountCollateralReserveFarmState,
    TAccountCollateralObligationFarmState,
    TAccountBorrowReserveFarmState,
    TAccountBorrowObligationFarmState,
    TAccountCollateralScopePrices,
    TAccountBorrowScopePrices,
    TAccountDestinationScopePrices,
    TAccountFarmsProgram,
    TAccountSwapProgram,
    TAccountKaminoProgram,
    TAccountInstructionSysvar,
    TAccountKaminoCollateralTokenProgram,
    TAccountCollateralTokenProgram,
    TAccountBorrowTokenProgram,
    TAccountDestinationTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): LeaveInstruction<
  TProgramAddress,
  TAccountCaller,
  TAccountConfig,
  TAccountPosition,
  TAccountCollateralMint,
  TAccountDestinationMint,
  TAccountBorrowMint,
  TAccountPositionCollateralAccount,
  TAccountPositionUsdcAccount,
  TAccountPositionDestinationAccount,
  TAccountOwnerCollateralAccount,
  TAccountOwnerUsdcAccount,
  TAccountOwnerDestinationAccount,
  TAccountOwner,
  TAccountObligation,
  TAccountLendingMarket,
  TAccountLendingMarketAuthority,
  TAccountCollateralReserve,
  TAccountCollateralReserveCollateralSupply,
  TAccountCollateralReserveCollateralMint,
  TAccountCollateralReserveLiquiditySupply,
  TAccountBorrowReserve,
  TAccountBorrowReserveLiquiditySupply,
  TAccountCollateralReserveFarmState,
  TAccountCollateralObligationFarmState,
  TAccountBorrowReserveFarmState,
  TAccountBorrowObligationFarmState,
  TAccountCollateralScopePrices,
  TAccountBorrowScopePrices,
  TAccountDestinationScopePrices,
  TAccountFarmsProgram,
  TAccountSwapProgram,
  TAccountKaminoProgram,
  TAccountInstructionSysvar,
  TAccountKaminoCollateralTokenProgram,
  TAccountCollateralTokenProgram,
  TAccountBorrowTokenProgram,
  TAccountDestinationTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? ACCRUE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    caller: { value: input.caller ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    position: { value: input.position ?? null, isWritable: true },
    collateralMint: { value: input.collateralMint ?? null, isWritable: false },
    destinationMint: {
      value: input.destinationMint ?? null,
      isWritable: false,
    },
    borrowMint: { value: input.borrowMint ?? null, isWritable: false },
    positionCollateralAccount: {
      value: input.positionCollateralAccount ?? null,
      isWritable: true,
    },
    positionUsdcAccount: {
      value: input.positionUsdcAccount ?? null,
      isWritable: true,
    },
    positionDestinationAccount: {
      value: input.positionDestinationAccount ?? null,
      isWritable: true,
    },
    ownerCollateralAccount: {
      value: input.ownerCollateralAccount ?? null,
      isWritable: true,
    },
    ownerUsdcAccount: {
      value: input.ownerUsdcAccount ?? null,
      isWritable: true,
    },
    ownerDestinationAccount: {
      value: input.ownerDestinationAccount ?? null,
      isWritable: true,
    },
    owner: { value: input.owner ?? null, isWritable: false },
    obligation: { value: input.obligation ?? null, isWritable: true },
    lendingMarket: { value: input.lendingMarket ?? null, isWritable: true },
    lendingMarketAuthority: {
      value: input.lendingMarketAuthority ?? null,
      isWritable: false,
    },
    collateralReserve: {
      value: input.collateralReserve ?? null,
      isWritable: true,
    },
    collateralReserveCollateralSupply: {
      value: input.collateralReserveCollateralSupply ?? null,
      isWritable: true,
    },
    collateralReserveCollateralMint: {
      value: input.collateralReserveCollateralMint ?? null,
      isWritable: true,
    },
    collateralReserveLiquiditySupply: {
      value: input.collateralReserveLiquiditySupply ?? null,
      isWritable: true,
    },
    borrowReserve: { value: input.borrowReserve ?? null, isWritable: true },
    borrowReserveLiquiditySupply: {
      value: input.borrowReserveLiquiditySupply ?? null,
      isWritable: true,
    },
    collateralReserveFarmState: {
      value: input.collateralReserveFarmState ?? null,
      isWritable: true,
    },
    collateralObligationFarmState: {
      value: input.collateralObligationFarmState ?? null,
      isWritable: true,
    },
    borrowReserveFarmState: {
      value: input.borrowReserveFarmState ?? null,
      isWritable: true,
    },
    borrowObligationFarmState: {
      value: input.borrowObligationFarmState ?? null,
      isWritable: true,
    },
    collateralScopePrices: {
      value: input.collateralScopePrices ?? null,
      isWritable: false,
    },
    borrowScopePrices: {
      value: input.borrowScopePrices ?? null,
      isWritable: false,
    },
    destinationScopePrices: {
      value: input.destinationScopePrices ?? null,
      isWritable: false,
    },
    farmsProgram: { value: input.farmsProgram ?? null, isWritable: false },
    swapProgram: { value: input.swapProgram ?? null, isWritable: false },
    kaminoProgram: { value: input.kaminoProgram ?? null, isWritable: false },
    instructionSysvar: {
      value: input.instructionSysvar ?? null,
      isWritable: false,
    },
    kaminoCollateralTokenProgram: {
      value: input.kaminoCollateralTokenProgram ?? null,
      isWritable: false,
    },
    collateralTokenProgram: {
      value: input.collateralTokenProgram ?? null,
      isWritable: false,
    },
    borrowTokenProgram: {
      value: input.borrowTokenProgram ?? null,
      isWritable: false,
    },
    destinationTokenProgram: {
      value: input.destinationTokenProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.farmsProgram.value) {
    accounts.farmsProgram.value =
      (KAMINO_FARMS_PROGRAM_ADDRESS as Address<"FarmsPZpWu9i7Kky8tPN37rs2TpmMrAZrC7S7vJa91Hr">);
  }
  if (!accounts.swapProgram.value) {
    accounts.swapProgram.value =
      (JUPITER_V6_PROGRAM_ADDRESS as Address<"JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4">);
  }
  if (!accounts.kaminoProgram.value) {
    accounts.kaminoProgram.value =
      (KAMINO_LENDING_PROGRAM_ADDRESS as Address<"KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD">);
  }
  if (!accounts.instructionSysvar.value) {
    accounts.instructionSysvar.value =
      "Sysvar1nstructions1111111111111111111111111" as Address<"Sysvar1nstructions1111111111111111111111111">;
  }
  if (!accounts.kaminoCollateralTokenProgram.value) {
    accounts.kaminoCollateralTokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.caller),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.position),
      getAccountMeta(accounts.collateralMint),
      getAccountMeta(accounts.destinationMint),
      getAccountMeta(accounts.borrowMint),
      getAccountMeta(accounts.positionCollateralAccount),
      getAccountMeta(accounts.positionUsdcAccount),
      getAccountMeta(accounts.positionDestinationAccount),
      getAccountMeta(accounts.ownerCollateralAccount),
      getAccountMeta(accounts.ownerUsdcAccount),
      getAccountMeta(accounts.ownerDestinationAccount),
      getAccountMeta(accounts.owner),
      getAccountMeta(accounts.obligation),
      getAccountMeta(accounts.lendingMarket),
      getAccountMeta(accounts.lendingMarketAuthority),
      getAccountMeta(accounts.collateralReserve),
      getAccountMeta(accounts.collateralReserveCollateralSupply),
      getAccountMeta(accounts.collateralReserveCollateralMint),
      getAccountMeta(accounts.collateralReserveLiquiditySupply),
      getAccountMeta(accounts.borrowReserve),
      getAccountMeta(accounts.borrowReserveLiquiditySupply),
      getAccountMeta(accounts.collateralReserveFarmState),
      getAccountMeta(accounts.collateralObligationFarmState),
      getAccountMeta(accounts.borrowReserveFarmState),
      getAccountMeta(accounts.borrowObligationFarmState),
      getAccountMeta(accounts.collateralScopePrices),
      getAccountMeta(accounts.borrowScopePrices),
      getAccountMeta(accounts.destinationScopePrices),
      getAccountMeta(accounts.farmsProgram),
      getAccountMeta(accounts.swapProgram),
      getAccountMeta(accounts.kaminoProgram),
      getAccountMeta(accounts.instructionSysvar),
      getAccountMeta(accounts.kaminoCollateralTokenProgram),
      getAccountMeta(accounts.collateralTokenProgram),
      getAccountMeta(accounts.borrowTokenProgram),
      getAccountMeta(accounts.destinationTokenProgram),
    ],
    data: getLeaveInstructionDataEncoder().encode(
      args as LeaveInstructionDataArgs,
    ),
    programAddress,
  } as LeaveInstruction<
    TProgramAddress,
    TAccountCaller,
    TAccountConfig,
    TAccountPosition,
    TAccountCollateralMint,
    TAccountDestinationMint,
    TAccountBorrowMint,
    TAccountPositionCollateralAccount,
    TAccountPositionUsdcAccount,
    TAccountPositionDestinationAccount,
    TAccountOwnerCollateralAccount,
    TAccountOwnerUsdcAccount,
    TAccountOwnerDestinationAccount,
    TAccountOwner,
    TAccountObligation,
    TAccountLendingMarket,
    TAccountLendingMarketAuthority,
    TAccountCollateralReserve,
    TAccountCollateralReserveCollateralSupply,
    TAccountCollateralReserveCollateralMint,
    TAccountCollateralReserveLiquiditySupply,
    TAccountBorrowReserve,
    TAccountBorrowReserveLiquiditySupply,
    TAccountCollateralReserveFarmState,
    TAccountCollateralObligationFarmState,
    TAccountBorrowReserveFarmState,
    TAccountBorrowObligationFarmState,
    TAccountCollateralScopePrices,
    TAccountBorrowScopePrices,
    TAccountDestinationScopePrices,
    TAccountFarmsProgram,
    TAccountSwapProgram,
    TAccountKaminoProgram,
    TAccountInstructionSysvar,
    TAccountKaminoCollateralTokenProgram,
    TAccountCollateralTokenProgram,
    TAccountBorrowTokenProgram,
    TAccountDestinationTokenProgram
  >);
}

export type ParsedLeaveInstruction<
  TProgram extends string = typeof ACCRUE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    caller: TAccountMetas[0];
    config: TAccountMetas[1];
    position: TAccountMetas[2];
    collateralMint: TAccountMetas[3];
    destinationMint: TAccountMetas[4];
    borrowMint: TAccountMetas[5];
    positionCollateralAccount: TAccountMetas[6];
    positionUsdcAccount: TAccountMetas[7];
    positionDestinationAccount: TAccountMetas[8];
    ownerCollateralAccount: TAccountMetas[9];
    ownerUsdcAccount: TAccountMetas[10];
    ownerDestinationAccount: TAccountMetas[11];
    owner: TAccountMetas[12];
    obligation: TAccountMetas[13];
    lendingMarket: TAccountMetas[14];
    lendingMarketAuthority: TAccountMetas[15];
    collateralReserve: TAccountMetas[16];
    collateralReserveCollateralSupply: TAccountMetas[17];
    collateralReserveCollateralMint: TAccountMetas[18];
    collateralReserveLiquiditySupply: TAccountMetas[19];
    borrowReserve: TAccountMetas[20];
    borrowReserveLiquiditySupply: TAccountMetas[21];
    collateralReserveFarmState?: TAccountMetas[22] | undefined;
    collateralObligationFarmState?: TAccountMetas[23] | undefined;
    borrowReserveFarmState?: TAccountMetas[24] | undefined;
    borrowObligationFarmState?: TAccountMetas[25] | undefined;
    collateralScopePrices: TAccountMetas[26];
    borrowScopePrices: TAccountMetas[27];
    destinationScopePrices: TAccountMetas[28];
    farmsProgram: TAccountMetas[29];
    swapProgram: TAccountMetas[30];
    kaminoProgram: TAccountMetas[31];
    instructionSysvar: TAccountMetas[32];
    kaminoCollateralTokenProgram: TAccountMetas[33];
    collateralTokenProgram: TAccountMetas[34];
    borrowTokenProgram: TAccountMetas[35];
    destinationTokenProgram: TAccountMetas[36];
  };
  data: LeaveInstructionData;
};

export function parseLeaveInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedLeaveInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 37) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  const getNextOptionalAccount = () => {
    const accountMeta = getNextAccount();
    return accountMeta.address === ACCRUE_PROGRAM_ADDRESS
      ? undefined
      : accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      caller: getNextAccount(),
      config: getNextAccount(),
      position: getNextAccount(),
      collateralMint: getNextAccount(),
      destinationMint: getNextAccount(),
      borrowMint: getNextAccount(),
      positionCollateralAccount: getNextAccount(),
      positionUsdcAccount: getNextAccount(),
      positionDestinationAccount: getNextAccount(),
      ownerCollateralAccount: getNextAccount(),
      ownerUsdcAccount: getNextAccount(),
      ownerDestinationAccount: getNextAccount(),
      owner: getNextAccount(),
      obligation: getNextAccount(),
      lendingMarket: getNextAccount(),
      lendingMarketAuthority: getNextAccount(),
      collateralReserve: getNextAccount(),
      collateralReserveCollateralSupply: getNextAccount(),
      collateralReserveCollateralMint: getNextAccount(),
      collateralReserveLiquiditySupply: getNextAccount(),
      borrowReserve: getNextAccount(),
      borrowReserveLiquiditySupply: getNextAccount(),
      collateralReserveFarmState: getNextOptionalAccount(),
      collateralObligationFarmState: getNextOptionalAccount(),
      borrowReserveFarmState: getNextOptionalAccount(),
      borrowObligationFarmState: getNextOptionalAccount(),
      collateralScopePrices: getNextAccount(),
      borrowScopePrices: getNextAccount(),
      destinationScopePrices: getNextAccount(),
      farmsProgram: getNextAccount(),
      swapProgram: getNextAccount(),
      kaminoProgram: getNextAccount(),
      instructionSysvar: getNextAccount(),
      kaminoCollateralTokenProgram: getNextAccount(),
      collateralTokenProgram: getNextAccount(),
      borrowTokenProgram: getNextAccount(),
      destinationTokenProgram: getNextAccount(),
    },
    data: getLeaveInstructionDataDecoder().decode(instruction.data),
  };
}
