/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { findConfigPda, findPositionPda } from "../pdas/index.js";
import { ACCRUE_PROGRAM_ADDRESS } from "../programs/index.js";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared/index.js";
import {
  getStrategyDecoder,
  getStrategyEncoder,
  type Strategy,
  type StrategyArgs,
} from "../types/index.js";

export const OPEN_POSITION_DISCRIMINATOR = new Uint8Array([
  135, 128, 47, 77, 15, 152, 240, 49,
]);

export function getOpenPositionDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    OPEN_POSITION_DISCRIMINATOR,
  );
}

export type OpenPositionInstruction<
  TProgram extends string = typeof ACCRUE_PROGRAM_ADDRESS,
  TAccountOwner extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountPosition extends string | AccountMeta<string> = string,
  TAccountCollateralMint extends string | AccountMeta<string> = string,
  TAccountDestinationMint extends string | AccountMeta<string> = string,
  TAccountBorrowMint extends string | AccountMeta<string> = string,
  TAccountOwnerCollateralAccount extends string | AccountMeta<string> = string,
  TAccountPositionCollateralAccount extends string | AccountMeta<string> =
    string,
  TAccountPositionUsdcAccount extends string | AccountMeta<string> = string,
  TAccountPositionDestinationAccount extends string | AccountMeta<string> =
    string,
  TAccountLendingMarket extends string | AccountMeta<string> = string,
  TAccountLendingMarketAuthority extends string | AccountMeta<string> = string,
  TAccountObligation extends string | AccountMeta<string> = string,
  TAccountUserMetadata extends string | AccountMeta<string> = string,
  TAccountCollateralReserve extends string | AccountMeta<string> = string,
  TAccountCollateralReserveLiquiditySupply extends
    string | AccountMeta<string> = string,
  TAccountCollateralReserveCollateralMint extends string | AccountMeta<string> =
    string,
  TAccountCollateralReserveCollateralSupply extends
    string | AccountMeta<string> = string,
  TAccountBorrowReserve extends string | AccountMeta<string> = string,
  TAccountBorrowReserveLiquiditySupply extends string | AccountMeta<string> =
    string,
  TAccountBorrowReserveFeeReceiver extends string | AccountMeta<string> =
    string,
  TAccountCollateralReserveFarmState extends string | AccountMeta<string> =
    string,
  TAccountCollateralObligationFarmState extends string | AccountMeta<string> =
    string,
  TAccountBorrowReserveFarmState extends string | AccountMeta<string> = string,
  TAccountBorrowObligationFarmState extends string | AccountMeta<string> =
    string,
  TAccountScopePrices extends string | AccountMeta<string> = string,
  TAccountFarmsProgram extends string | AccountMeta<string> =
    "FarmsPZpWu9i7Kky8tPN37rs2TpmMrAZrC7S7vJa91Hr",
  TAccountSwapProgram extends string | AccountMeta<string> =
    "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4",
  TAccountKaminoProgram extends string | AccountMeta<string> =
    "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD",
  TAccountInstructionSysvar extends string | AccountMeta<string> =
    "Sysvar1nstructions1111111111111111111111111",
  TAccountCollateralTokenProgram extends string | AccountMeta<string> = string,
  TAccountKaminoCollateralTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountBorrowTokenProgram extends string | AccountMeta<string> = string,
  TAccountDestinationTokenProgram extends string | AccountMeta<string> = string,
  TAccountRent extends string | AccountMeta<string> =
    "SysvarRent111111111111111111111111111111111",
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountOwner extends string
        ? WritableSignerAccount<TAccountOwner> &
            AccountSignerMeta<TAccountOwner>
        : TAccountOwner,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountPosition extends string
        ? WritableAccount<TAccountPosition>
        : TAccountPosition,
      TAccountCollateralMint extends string
        ? ReadonlyAccount<TAccountCollateralMint>
        : TAccountCollateralMint,
      TAccountDestinationMint extends string
        ? ReadonlyAccount<TAccountDestinationMint>
        : TAccountDestinationMint,
      TAccountBorrowMint extends string
        ? ReadonlyAccount<TAccountBorrowMint>
        : TAccountBorrowMint,
      TAccountOwnerCollateralAccount extends string
        ? WritableAccount<TAccountOwnerCollateralAccount>
        : TAccountOwnerCollateralAccount,
      TAccountPositionCollateralAccount extends string
        ? WritableAccount<TAccountPositionCollateralAccount>
        : TAccountPositionCollateralAccount,
      TAccountPositionUsdcAccount extends string
        ? WritableAccount<TAccountPositionUsdcAccount>
        : TAccountPositionUsdcAccount,
      TAccountPositionDestinationAccount extends string
        ? WritableAccount<TAccountPositionDestinationAccount>
        : TAccountPositionDestinationAccount,
      TAccountLendingMarket extends string
        ? WritableAccount<TAccountLendingMarket>
        : TAccountLendingMarket,
      TAccountLendingMarketAuthority extends string
        ? ReadonlyAccount<TAccountLendingMarketAuthority>
        : TAccountLendingMarketAuthority,
      TAccountObligation extends string
        ? WritableAccount<TAccountObligation>
        : TAccountObligation,
      TAccountUserMetadata extends string
        ? WritableAccount<TAccountUserMetadata>
        : TAccountUserMetadata,
      TAccountCollateralReserve extends string
        ? WritableAccount<TAccountCollateralReserve>
        : TAccountCollateralReserve,
      TAccountCollateralReserveLiquiditySupply extends string
        ? WritableAccount<TAccountCollateralReserveLiquiditySupply>
        : TAccountCollateralReserveLiquiditySupply,
      TAccountCollateralReserveCollateralMint extends string
        ? WritableAccount<TAccountCollateralReserveCollateralMint>
        : TAccountCollateralReserveCollateralMint,
      TAccountCollateralReserveCollateralSupply extends string
        ? WritableAccount<TAccountCollateralReserveCollateralSupply>
        : TAccountCollateralReserveCollateralSupply,
      TAccountBorrowReserve extends string
        ? WritableAccount<TAccountBorrowReserve>
        : TAccountBorrowReserve,
      TAccountBorrowReserveLiquiditySupply extends string
        ? WritableAccount<TAccountBorrowReserveLiquiditySupply>
        : TAccountBorrowReserveLiquiditySupply,
      TAccountBorrowReserveFeeReceiver extends string
        ? WritableAccount<TAccountBorrowReserveFeeReceiver>
        : TAccountBorrowReserveFeeReceiver,
      TAccountCollateralReserveFarmState extends string
        ? WritableAccount<TAccountCollateralReserveFarmState>
        : TAccountCollateralReserveFarmState,
      TAccountCollateralObligationFarmState extends string
        ? WritableAccount<TAccountCollateralObligationFarmState>
        : TAccountCollateralObligationFarmState,
      TAccountBorrowReserveFarmState extends string
        ? WritableAccount<TAccountBorrowReserveFarmState>
        : TAccountBorrowReserveFarmState,
      TAccountBorrowObligationFarmState extends string
        ? WritableAccount<TAccountBorrowObligationFarmState>
        : TAccountBorrowObligationFarmState,
      TAccountScopePrices extends string
        ? ReadonlyAccount<TAccountScopePrices>
        : TAccountScopePrices,
      TAccountFarmsProgram extends string
        ? ReadonlyAccount<TAccountFarmsProgram>
        : TAccountFarmsProgram,
      TAccountSwapProgram extends string
        ? ReadonlyAccount<TAccountSwapProgram>
        : TAccountSwapProgram,
      TAccountKaminoProgram extends string
        ? ReadonlyAccount<TAccountKaminoProgram>
        : TAccountKaminoProgram,
      TAccountInstructionSysvar extends string
        ? ReadonlyAccount<TAccountInstructionSysvar>
        : TAccountInstructionSysvar,
      TAccountCollateralTokenProgram extends string
        ? ReadonlyAccount<TAccountCollateralTokenProgram>
        : TAccountCollateralTokenProgram,
      TAccountKaminoCollateralTokenProgram extends string
        ? ReadonlyAccount<TAccountKaminoCollateralTokenProgram>
        : TAccountKaminoCollateralTokenProgram,
      TAccountBorrowTokenProgram extends string
        ? ReadonlyAccount<TAccountBorrowTokenProgram>
        : TAccountBorrowTokenProgram,
      TAccountDestinationTokenProgram extends string
        ? ReadonlyAccount<TAccountDestinationTokenProgram>
        : TAccountDestinationTokenProgram,
      TAccountRent extends string
        ? ReadonlyAccount<TAccountRent>
        : TAccountRent,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type OpenPositionInstructionData = {
  discriminator: ReadonlyUint8Array;
  collateralAmount: bigint;
  borrowAmount: bigint;
  minimumDestinationAmount: bigint;
  strategy: Strategy;
  leaveUsdcForLaterSwap: boolean;
  jupiterRouteData: ReadonlyUint8Array;
};

export type OpenPositionInstructionDataArgs = {
  collateralAmount: number | bigint;
  borrowAmount: number | bigint;
  minimumDestinationAmount: number | bigint;
  strategy: StrategyArgs;
  leaveUsdcForLaterSwap: boolean;
  jupiterRouteData: ReadonlyUint8Array;
};

export function getOpenPositionInstructionDataEncoder(): Encoder<OpenPositionInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["collateralAmount", getU64Encoder()],
      ["borrowAmount", getU64Encoder()],
      ["minimumDestinationAmount", getU64Encoder()],
      ["strategy", getStrategyEncoder()],
      ["leaveUsdcForLaterSwap", getBooleanEncoder()],
      [
        "jupiterRouteData",
        addEncoderSizePrefix(getBytesEncoder(), getU32Encoder()),
      ],
    ]),
    (value) => ({ ...value, discriminator: OPEN_POSITION_DISCRIMINATOR }),
  );
}

export function getOpenPositionInstructionDataDecoder(): Decoder<OpenPositionInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["collateralAmount", getU64Decoder()],
    ["borrowAmount", getU64Decoder()],
    ["minimumDestinationAmount", getU64Decoder()],
    ["strategy", getStrategyDecoder()],
    ["leaveUsdcForLaterSwap", getBooleanDecoder()],
    [
      "jupiterRouteData",
      addDecoderSizePrefix(getBytesDecoder(), getU32Decoder()),
    ],
  ]);
}

export function getOpenPositionInstructionDataCodec(): Codec<
  OpenPositionInstructionDataArgs,
  OpenPositionInstructionData
> {
  return combineCodec(
    getOpenPositionInstructionDataEncoder(),
    getOpenPositionInstructionDataDecoder(),
  );
}

export type OpenPositionAsyncInput<
  TAccountOwner extends string = string,
  TAccountConfig extends string = string,
  TAccountPosition extends string = string,
  TAccountCollateralMint extends string = string,
  TAccountDestinationMint extends string = string,
  TAccountBorrowMint extends string = string,
  TAccountOwnerCollateralAccount extends string = string,
  TAccountPositionCollateralAccount extends string = string,
  TAccountPositionUsdcAccount extends string = string,
  TAccountPositionDestinationAccount extends string = string,
  TAccountLendingMarket extends string = string,
  TAccountLendingMarketAuthority extends string = string,
  TAccountObligation extends string = string,
  TAccountUserMetadata extends string = string,
  TAccountCollateralReserve extends string = string,
  TAccountCollateralReserveLiquiditySupply extends string = string,
  TAccountCollateralReserveCollateralMint extends string = string,
  TAccountCollateralReserveCollateralSupply extends string = string,
  TAccountBorrowReserve extends string = string,
  TAccountBorrowReserveLiquiditySupply extends string = string,
  TAccountBorrowReserveFeeReceiver extends string = string,
  TAccountCollateralReserveFarmState extends string = string,
  TAccountCollateralObligationFarmState extends string = string,
  TAccountBorrowReserveFarmState extends string = string,
  TAccountBorrowObligationFarmState extends string = string,
  TAccountScopePrices extends string = string,
  TAccountFarmsProgram extends string = string,
  TAccountSwapProgram extends string = string,
  TAccountKaminoProgram extends string = string,
  TAccountInstructionSysvar extends string = string,
  TAccountCollateralTokenProgram extends string = string,
  TAccountKaminoCollateralTokenProgram extends string = string,
  TAccountBorrowTokenProgram extends string = string,
  TAccountDestinationTokenProgram extends string = string,
  TAccountRent extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  owner: TransactionSigner<TAccountOwner>;
  config?: Address<TAccountConfig>;
  position?: Address<TAccountPosition>;
  collateralMint: Address<TAccountCollateralMint>;
  destinationMint: Address<TAccountDestinationMint>;
  borrowMint: Address<TAccountBorrowMint>;
  ownerCollateralAccount?: Address<TAccountOwnerCollateralAccount>;
  positionCollateralAccount?: Address<TAccountPositionCollateralAccount>;
  positionUsdcAccount?: Address<TAccountPositionUsdcAccount>;
  positionDestinationAccount?: Address<TAccountPositionDestinationAccount>;
  lendingMarket: Address<TAccountLendingMarket>;
  lendingMarketAuthority: Address<TAccountLendingMarketAuthority>;
  obligation: Address<TAccountObligation>;
  userMetadata: Address<TAccountUserMetadata>;
  collateralReserve: Address<TAccountCollateralReserve>;
  collateralReserveLiquiditySupply: Address<TAccountCollateralReserveLiquiditySupply>;
  collateralReserveCollateralMint: Address<TAccountCollateralReserveCollateralMint>;
  collateralReserveCollateralSupply: Address<TAccountCollateralReserveCollateralSupply>;
  borrowReserve: Address<TAccountBorrowReserve>;
  borrowReserveLiquiditySupply: Address<TAccountBorrowReserveLiquiditySupply>;
  borrowReserveFeeReceiver: Address<TAccountBorrowReserveFeeReceiver>;
  collateralReserveFarmState?: Address<TAccountCollateralReserveFarmState>;
  collateralObligationFarmState?: Address<TAccountCollateralObligationFarmState>;
  borrowReserveFarmState?: Address<TAccountBorrowReserveFarmState>;
  borrowObligationFarmState?: Address<TAccountBorrowObligationFarmState>;
  scopePrices: Address<TAccountScopePrices>;
  farmsProgram?: Address<TAccountFarmsProgram>;
  swapProgram?: Address<TAccountSwapProgram>;
  kaminoProgram?: Address<TAccountKaminoProgram>;
  instructionSysvar?: Address<TAccountInstructionSysvar>;
  collateralTokenProgram: Address<TAccountCollateralTokenProgram>;
  kaminoCollateralTokenProgram?: Address<TAccountKaminoCollateralTokenProgram>;
  borrowTokenProgram: Address<TAccountBorrowTokenProgram>;
  destinationTokenProgram: Address<TAccountDestinationTokenProgram>;
  rent?: Address<TAccountRent>;
  systemProgram?: Address<TAccountSystemProgram>;
  collateralAmount: OpenPositionInstructionDataArgs["collateralAmount"];
  borrowAmount: OpenPositionInstructionDataArgs["borrowAmount"];
  minimumDestinationAmount: OpenPositionInstructionDataArgs["minimumDestinationAmount"];
  strategy: OpenPositionInstructionDataArgs["strategy"];
  leaveUsdcForLaterSwap: OpenPositionInstructionDataArgs["leaveUsdcForLaterSwap"];
  jupiterRouteData: OpenPositionInstructionDataArgs["jupiterRouteData"];
};

export async function getOpenPositionInstructionAsync<
  TAccountOwner extends string,
  TAccountConfig extends string,
  TAccountPosition extends string,
  TAccountCollateralMint extends string,
  TAccountDestinationMint extends string,
  TAccountBorrowMint extends string,
  TAccountOwnerCollateralAccount extends string,
  TAccountPositionCollateralAccount extends string,
  TAccountPositionUsdcAccount extends string,
  TAccountPositionDestinationAccount extends string,
  TAccountLendingMarket extends string,
  TAccountLendingMarketAuthority extends string,
  TAccountObligation extends string,
  TAccountUserMetadata extends string,
  TAccountCollateralReserve extends string,
  TAccountCollateralReserveLiquiditySupply extends string,
  TAccountCollateralReserveCollateralMint extends string,
  TAccountCollateralReserveCollateralSupply extends string,
  TAccountBorrowReserve extends string,
  TAccountBorrowReserveLiquiditySupply extends string,
  TAccountBorrowReserveFeeReceiver extends string,
  TAccountCollateralReserveFarmState extends string,
  TAccountCollateralObligationFarmState extends string,
  TAccountBorrowReserveFarmState extends string,
  TAccountBorrowObligationFarmState extends string,
  TAccountScopePrices extends string,
  TAccountFarmsProgram extends string,
  TAccountSwapProgram extends string,
  TAccountKaminoProgram extends string,
  TAccountInstructionSysvar extends string,
  TAccountCollateralTokenProgram extends string,
  TAccountKaminoCollateralTokenProgram extends string,
  TAccountBorrowTokenProgram extends string,
  TAccountDestinationTokenProgram extends string,
  TAccountRent extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ACCRUE_PROGRAM_ADDRESS,
>(
  input: OpenPositionAsyncInput<
    TAccountOwner,
    TAccountConfig,
    TAccountPosition,
    TAccountCollateralMint,
    TAccountDestinationMint,
    TAccountBorrowMint,
    TAccountOwnerCollateralAccount,
    TAccountPositionCollateralAccount,
    TAccountPositionUsdcAccount,
    TAccountPositionDestinationAccount,
    TAccountLendingMarket,
    TAccountLendingMarketAuthority,
    TAccountObligation,
    TAccountUserMetadata,
    TAccountCollateralReserve,
    TAccountCollateralReserveLiquiditySupply,
    TAccountCollateralReserveCollateralMint,
    TAccountCollateralReserveCollateralSupply,
    TAccountBorrowReserve,
    TAccountBorrowReserveLiquiditySupply,
    TAccountBorrowReserveFeeReceiver,
    TAccountCollateralReserveFarmState,
    TAccountCollateralObligationFarmState,
    TAccountBorrowReserveFarmState,
    TAccountBorrowObligationFarmState,
    TAccountScopePrices,
    TAccountFarmsProgram,
    TAccountSwapProgram,
    TAccountKaminoProgram,
    TAccountInstructionSysvar,
    TAccountCollateralTokenProgram,
    TAccountKaminoCollateralTokenProgram,
    TAccountBorrowTokenProgram,
    TAccountDestinationTokenProgram,
    TAccountRent,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  OpenPositionInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountConfig,
    TAccountPosition,
    TAccountCollateralMint,
    TAccountDestinationMint,
    TAccountBorrowMint,
    TAccountOwnerCollateralAccount,
    TAccountPositionCollateralAccount,
    TAccountPositionUsdcAccount,
    TAccountPositionDestinationAccount,
    TAccountLendingMarket,
    TAccountLendingMarketAuthority,
    TAccountObligation,
    TAccountUserMetadata,
    TAccountCollateralReserve,
    TAccountCollateralReserveLiquiditySupply,
    TAccountCollateralReserveCollateralMint,
    TAccountCollateralReserveCollateralSupply,
    TAccountBorrowReserve,
    TAccountBorrowReserveLiquiditySupply,
    TAccountBorrowReserveFeeReceiver,
    TAccountCollateralReserveFarmState,
    TAccountCollateralObligationFarmState,
    TAccountBorrowReserveFarmState,
    TAccountBorrowObligationFarmState,
    TAccountScopePrices,
    TAccountFarmsProgram,
    TAccountSwapProgram,
    TAccountKaminoProgram,
    TAccountInstructionSysvar,
    TAccountCollateralTokenProgram,
    TAccountKaminoCollateralTokenProgram,
    TAccountBorrowTokenProgram,
    TAccountDestinationTokenProgram,
    TAccountRent,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ACCRUE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    owner: { value: input.owner ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    position: { value: input.position ?? null, isWritable: true },
    collateralMint: { value: input.collateralMint ?? null, isWritable: false },
    destinationMint: {
      value: input.destinationMint ?? null,
      isWritable: false,
    },
    borrowMint: { value: input.borrowMint ?? null, isWritable: false },
    ownerCollateralAccount: {
      value: input.ownerCollateralAccount ?? null,
      isWritable: true,
    },
    positionCollateralAccount: {
      value: input.positionCollateralAccount ?? null,
      isWritable: true,
    },
    positionUsdcAccount: {
      value: input.positionUsdcAccount ?? null,
      isWritable: true,
    },
    positionDestinationAccount: {
      value: input.positionDestinationAccount ?? null,
      isWritable: true,
    },
    lendingMarket: { value: input.lendingMarket ?? null, isWritable: true },
    lendingMarketAuthority: {
      value: input.lendingMarketAuthority ?? null,
      isWritable: false,
    },
    obligation: { value: input.obligation ?? null, isWritable: true },
    userMetadata: { value: input.userMetadata ?? null, isWritable: true },
    collateralReserve: {
      value: input.collateralReserve ?? null,
      isWritable: true,
    },
    collateralReserveLiquiditySupply: {
      value: input.collateralReserveLiquiditySupply ?? null,
      isWritable: true,
    },
    collateralReserveCollateralMint: {
      value: input.collateralReserveCollateralMint ?? null,
      isWritable: true,
    },
    collateralReserveCollateralSupply: {
      value: input.collateralReserveCollateralSupply ?? null,
      isWritable: true,
    },
    borrowReserve: { value: input.borrowReserve ?? null, isWritable: true },
    borrowReserveLiquiditySupply: {
      value: input.borrowReserveLiquiditySupply ?? null,
      isWritable: true,
    },
    borrowReserveFeeReceiver: {
      value: input.borrowReserveFeeReceiver ?? null,
      isWritable: true,
    },
    collateralReserveFarmState: {
      value: input.collateralReserveFarmState ?? null,
      isWritable: true,
    },
    collateralObligationFarmState: {
      value: input.collateralObligationFarmState ?? null,
      isWritable: true,
    },
    borrowReserveFarmState: {
      value: input.borrowReserveFarmState ?? null,
      isWritable: true,
    },
    borrowObligationFarmState: {
      value: input.borrowObligationFarmState ?? null,
      isWritable: true,
    },
    scopePrices: { value: input.scopePrices ?? null, isWritable: false },
    farmsProgram: { value: input.farmsProgram ?? null, isWritable: false },
    swapProgram: { value: input.swapProgram ?? null, isWritable: false },
    kaminoProgram: { value: input.kaminoProgram ?? null, isWritable: false },
    instructionSysvar: {
      value: input.instructionSysvar ?? null,
      isWritable: false,
    },
    collateralTokenProgram: {
      value: input.collateralTokenProgram ?? null,
      isWritable: false,
    },
    kaminoCollateralTokenProgram: {
      value: input.kaminoCollateralTokenProgram ?? null,
      isWritable: false,
    },
    borrowTokenProgram: {
      value: input.borrowTokenProgram ?? null,
      isWritable: false,
    },
    destinationTokenProgram: {
      value: input.destinationTokenProgram ?? null,
      isWritable: false,
    },
    rent: { value: input.rent ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.position.value) {
    accounts.position.value = await findPositionPda({
      owner: expectAddress(accounts.owner.value),
      collateralMint: expectAddress(accounts.collateralMint.value),
      destinationMint: expectAddress(accounts.destinationMint.value),
    });
  }
  if (!accounts.ownerCollateralAccount.value) {
    accounts.ownerCollateralAccount.value = await getProgramDerivedAddress({
      programAddress:
        "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.owner.value)),
        getAddressEncoder().encode(
          expectAddress(accounts.collateralTokenProgram.value),
        ),
        getAddressEncoder().encode(
          expectAddress(accounts.collateralMint.value),
        ),
      ],
    });
  }
  if (!accounts.positionCollateralAccount.value) {
    accounts.positionCollateralAccount.value = await getProgramDerivedAddress({
      programAddress:
        "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.position.value)),
        getAddressEncoder().encode(
          expectAddress(accounts.collateralTokenProgram.value),
        ),
        getAddressEncoder().encode(
          expectAddress(accounts.collateralMint.value),
        ),
      ],
    });
  }
  if (!accounts.positionUsdcAccount.value) {
    accounts.positionUsdcAccount.value = await getProgramDerivedAddress({
      programAddress:
        "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.position.value)),
        getAddressEncoder().encode(
          expectAddress(accounts.borrowTokenProgram.value),
        ),
        getAddressEncoder().encode(expectAddress(accounts.borrowMint.value)),
      ],
    });
  }
  if (!accounts.positionDestinationAccount.value) {
    accounts.positionDestinationAccount.value = await getProgramDerivedAddress({
      programAddress:
        "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.position.value)),
        getAddressEncoder().encode(
          expectAddress(accounts.destinationTokenProgram.value),
        ),
        getAddressEncoder().encode(
          expectAddress(accounts.destinationMint.value),
        ),
      ],
    });
  }
  if (!accounts.farmsProgram.value) {
    accounts.farmsProgram.value =
      "FarmsPZpWu9i7Kky8tPN37rs2TpmMrAZrC7S7vJa91Hr" as Address<"FarmsPZpWu9i7Kky8tPN37rs2TpmMrAZrC7S7vJa91Hr">;
  }
  if (!accounts.swapProgram.value) {
    accounts.swapProgram.value =
      "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4" as Address<"JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4">;
  }
  if (!accounts.kaminoProgram.value) {
    accounts.kaminoProgram.value =
      "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD" as Address<"KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD">;
  }
  if (!accounts.instructionSysvar.value) {
    accounts.instructionSysvar.value =
      "Sysvar1nstructions1111111111111111111111111" as Address<"Sysvar1nstructions1111111111111111111111111">;
  }
  if (!accounts.kaminoCollateralTokenProgram.value) {
    accounts.kaminoCollateralTokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.rent.value) {
    accounts.rent.value =
      "SysvarRent111111111111111111111111111111111" as Address<"SysvarRent111111111111111111111111111111111">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.owner),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.position),
      getAccountMeta(accounts.collateralMint),
      getAccountMeta(accounts.destinationMint),
      getAccountMeta(accounts.borrowMint),
      getAccountMeta(accounts.ownerCollateralAccount),
      getAccountMeta(accounts.positionCollateralAccount),
      getAccountMeta(accounts.positionUsdcAccount),
      getAccountMeta(accounts.positionDestinationAccount),
      getAccountMeta(accounts.lendingMarket),
      getAccountMeta(accounts.lendingMarketAuthority),
      getAccountMeta(accounts.obligation),
      getAccountMeta(accounts.userMetadata),
      getAccountMeta(accounts.collateralReserve),
      getAccountMeta(accounts.collateralReserveLiquiditySupply),
      getAccountMeta(accounts.collateralReserveCollateralMint),
      getAccountMeta(accounts.collateralReserveCollateralSupply),
      getAccountMeta(accounts.borrowReserve),
      getAccountMeta(accounts.borrowReserveLiquiditySupply),
      getAccountMeta(accounts.borrowReserveFeeReceiver),
      getAccountMeta(accounts.collateralReserveFarmState),
      getAccountMeta(accounts.collateralObligationFarmState),
      getAccountMeta(accounts.borrowReserveFarmState),
      getAccountMeta(accounts.borrowObligationFarmState),
      getAccountMeta(accounts.scopePrices),
      getAccountMeta(accounts.farmsProgram),
      getAccountMeta(accounts.swapProgram),
      getAccountMeta(accounts.kaminoProgram),
      getAccountMeta(accounts.instructionSysvar),
      getAccountMeta(accounts.collateralTokenProgram),
      getAccountMeta(accounts.kaminoCollateralTokenProgram),
      getAccountMeta(accounts.borrowTokenProgram),
      getAccountMeta(accounts.destinationTokenProgram),
      getAccountMeta(accounts.rent),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getOpenPositionInstructionDataEncoder().encode(
      args as OpenPositionInstructionDataArgs,
    ),
    programAddress,
  } as OpenPositionInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountConfig,
    TAccountPosition,
    TAccountCollateralMint,
    TAccountDestinationMint,
    TAccountBorrowMint,
    TAccountOwnerCollateralAccount,
    TAccountPositionCollateralAccount,
    TAccountPositionUsdcAccount,
    TAccountPositionDestinationAccount,
    TAccountLendingMarket,
    TAccountLendingMarketAuthority,
    TAccountObligation,
    TAccountUserMetadata,
    TAccountCollateralReserve,
    TAccountCollateralReserveLiquiditySupply,
    TAccountCollateralReserveCollateralMint,
    TAccountCollateralReserveCollateralSupply,
    TAccountBorrowReserve,
    TAccountBorrowReserveLiquiditySupply,
    TAccountBorrowReserveFeeReceiver,
    TAccountCollateralReserveFarmState,
    TAccountCollateralObligationFarmState,
    TAccountBorrowReserveFarmState,
    TAccountBorrowObligationFarmState,
    TAccountScopePrices,
    TAccountFarmsProgram,
    TAccountSwapProgram,
    TAccountKaminoProgram,
    TAccountInstructionSysvar,
    TAccountCollateralTokenProgram,
    TAccountKaminoCollateralTokenProgram,
    TAccountBorrowTokenProgram,
    TAccountDestinationTokenProgram,
    TAccountRent,
    TAccountSystemProgram
  >);
}

export type OpenPositionInput<
  TAccountOwner extends string = string,
  TAccountConfig extends string = string,
  TAccountPosition extends string = string,
  TAccountCollateralMint extends string = string,
  TAccountDestinationMint extends string = string,
  TAccountBorrowMint extends string = string,
  TAccountOwnerCollateralAccount extends string = string,
  TAccountPositionCollateralAccount extends string = string,
  TAccountPositionUsdcAccount extends string = string,
  TAccountPositionDestinationAccount extends string = string,
  TAccountLendingMarket extends string = string,
  TAccountLendingMarketAuthority extends string = string,
  TAccountObligation extends string = string,
  TAccountUserMetadata extends string = string,
  TAccountCollateralReserve extends string = string,
  TAccountCollateralReserveLiquiditySupply extends string = string,
  TAccountCollateralReserveCollateralMint extends string = string,
  TAccountCollateralReserveCollateralSupply extends string = string,
  TAccountBorrowReserve extends string = string,
  TAccountBorrowReserveLiquiditySupply extends string = string,
  TAccountBorrowReserveFeeReceiver extends string = string,
  TAccountCollateralReserveFarmState extends string = string,
  TAccountCollateralObligationFarmState extends string = string,
  TAccountBorrowReserveFarmState extends string = string,
  TAccountBorrowObligationFarmState extends string = string,
  TAccountScopePrices extends string = string,
  TAccountFarmsProgram extends string = string,
  TAccountSwapProgram extends string = string,
  TAccountKaminoProgram extends string = string,
  TAccountInstructionSysvar extends string = string,
  TAccountCollateralTokenProgram extends string = string,
  TAccountKaminoCollateralTokenProgram extends string = string,
  TAccountBorrowTokenProgram extends string = string,
  TAccountDestinationTokenProgram extends string = string,
  TAccountRent extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  owner: TransactionSigner<TAccountOwner>;
  config: Address<TAccountConfig>;
  position: Address<TAccountPosition>;
  collateralMint: Address<TAccountCollateralMint>;
  destinationMint: Address<TAccountDestinationMint>;
  borrowMint: Address<TAccountBorrowMint>;
  ownerCollateralAccount: Address<TAccountOwnerCollateralAccount>;
  positionCollateralAccount: Address<TAccountPositionCollateralAccount>;
  positionUsdcAccount: Address<TAccountPositionUsdcAccount>;
  positionDestinationAccount: Address<TAccountPositionDestinationAccount>;
  lendingMarket: Address<TAccountLendingMarket>;
  lendingMarketAuthority: Address<TAccountLendingMarketAuthority>;
  obligation: Address<TAccountObligation>;
  userMetadata: Address<TAccountUserMetadata>;
  collateralReserve: Address<TAccountCollateralReserve>;
  collateralReserveLiquiditySupply: Address<TAccountCollateralReserveLiquiditySupply>;
  collateralReserveCollateralMint: Address<TAccountCollateralReserveCollateralMint>;
  collateralReserveCollateralSupply: Address<TAccountCollateralReserveCollateralSupply>;
  borrowReserve: Address<TAccountBorrowReserve>;
  borrowReserveLiquiditySupply: Address<TAccountBorrowReserveLiquiditySupply>;
  borrowReserveFeeReceiver: Address<TAccountBorrowReserveFeeReceiver>;
  collateralReserveFarmState?: Address<TAccountCollateralReserveFarmState>;
  collateralObligationFarmState?: Address<TAccountCollateralObligationFarmState>;
  borrowReserveFarmState?: Address<TAccountBorrowReserveFarmState>;
  borrowObligationFarmState?: Address<TAccountBorrowObligationFarmState>;
  scopePrices: Address<TAccountScopePrices>;
  farmsProgram?: Address<TAccountFarmsProgram>;
  swapProgram?: Address<TAccountSwapProgram>;
  kaminoProgram?: Address<TAccountKaminoProgram>;
  instructionSysvar?: Address<TAccountInstructionSysvar>;
  collateralTokenProgram: Address<TAccountCollateralTokenProgram>;
  kaminoCollateralTokenProgram?: Address<TAccountKaminoCollateralTokenProgram>;
  borrowTokenProgram: Address<TAccountBorrowTokenProgram>;
  destinationTokenProgram: Address<TAccountDestinationTokenProgram>;
  rent?: Address<TAccountRent>;
  systemProgram?: Address<TAccountSystemProgram>;
  collateralAmount: OpenPositionInstructionDataArgs["collateralAmount"];
  borrowAmount: OpenPositionInstructionDataArgs["borrowAmount"];
  minimumDestinationAmount: OpenPositionInstructionDataArgs["minimumDestinationAmount"];
  strategy: OpenPositionInstructionDataArgs["strategy"];
  leaveUsdcForLaterSwap: OpenPositionInstructionDataArgs["leaveUsdcForLaterSwap"];
  jupiterRouteData: OpenPositionInstructionDataArgs["jupiterRouteData"];
};

export function getOpenPositionInstruction<
  TAccountOwner extends string,
  TAccountConfig extends string,
  TAccountPosition extends string,
  TAccountCollateralMint extends string,
  TAccountDestinationMint extends string,
  TAccountBorrowMint extends string,
  TAccountOwnerCollateralAccount extends string,
  TAccountPositionCollateralAccount extends string,
  TAccountPositionUsdcAccount extends string,
  TAccountPositionDestinationAccount extends string,
  TAccountLendingMarket extends string,
  TAccountLendingMarketAuthority extends string,
  TAccountObligation extends string,
  TAccountUserMetadata extends string,
  TAccountCollateralReserve extends string,
  TAccountCollateralReserveLiquiditySupply extends string,
  TAccountCollateralReserveCollateralMint extends string,
  TAccountCollateralReserveCollateralSupply extends string,
  TAccountBorrowReserve extends string,
  TAccountBorrowReserveLiquiditySupply extends string,
  TAccountBorrowReserveFeeReceiver extends string,
  TAccountCollateralReserveFarmState extends string,
  TAccountCollateralObligationFarmState extends string,
  TAccountBorrowReserveFarmState extends string,
  TAccountBorrowObligationFarmState extends string,
  TAccountScopePrices extends string,
  TAccountFarmsProgram extends string,
  TAccountSwapProgram extends string,
  TAccountKaminoProgram extends string,
  TAccountInstructionSysvar extends string,
  TAccountCollateralTokenProgram extends string,
  TAccountKaminoCollateralTokenProgram extends string,
  TAccountBorrowTokenProgram extends string,
  TAccountDestinationTokenProgram extends string,
  TAccountRent extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ACCRUE_PROGRAM_ADDRESS,
>(
  input: OpenPositionInput<
    TAccountOwner,
    TAccountConfig,
    TAccountPosition,
    TAccountCollateralMint,
    TAccountDestinationMint,
    TAccountBorrowMint,
    TAccountOwnerCollateralAccount,
    TAccountPositionCollateralAccount,
    TAccountPositionUsdcAccount,
    TAccountPositionDestinationAccount,
    TAccountLendingMarket,
    TAccountLendingMarketAuthority,
    TAccountObligation,
    TAccountUserMetadata,
    TAccountCollateralReserve,
    TAccountCollateralReserveLiquiditySupply,
    TAccountCollateralReserveCollateralMint,
    TAccountCollateralReserveCollateralSupply,
    TAccountBorrowReserve,
    TAccountBorrowReserveLiquiditySupply,
    TAccountBorrowReserveFeeReceiver,
    TAccountCollateralReserveFarmState,
    TAccountCollateralObligationFarmState,
    TAccountBorrowReserveFarmState,
    TAccountBorrowObligationFarmState,
    TAccountScopePrices,
    TAccountFarmsProgram,
    TAccountSwapProgram,
    TAccountKaminoProgram,
    TAccountInstructionSysvar,
    TAccountCollateralTokenProgram,
    TAccountKaminoCollateralTokenProgram,
    TAccountBorrowTokenProgram,
    TAccountDestinationTokenProgram,
    TAccountRent,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): OpenPositionInstruction<
  TProgramAddress,
  TAccountOwner,
  TAccountConfig,
  TAccountPosition,
  TAccountCollateralMint,
  TAccountDestinationMint,
  TAccountBorrowMint,
  TAccountOwnerCollateralAccount,
  TAccountPositionCollateralAccount,
  TAccountPositionUsdcAccount,
  TAccountPositionDestinationAccount,
  TAccountLendingMarket,
  TAccountLendingMarketAuthority,
  TAccountObligation,
  TAccountUserMetadata,
  TAccountCollateralReserve,
  TAccountCollateralReserveLiquiditySupply,
  TAccountCollateralReserveCollateralMint,
  TAccountCollateralReserveCollateralSupply,
  TAccountBorrowReserve,
  TAccountBorrowReserveLiquiditySupply,
  TAccountBorrowReserveFeeReceiver,
  TAccountCollateralReserveFarmState,
  TAccountCollateralObligationFarmState,
  TAccountBorrowReserveFarmState,
  TAccountBorrowObligationFarmState,
  TAccountScopePrices,
  TAccountFarmsProgram,
  TAccountSwapProgram,
  TAccountKaminoProgram,
  TAccountInstructionSysvar,
  TAccountCollateralTokenProgram,
  TAccountKaminoCollateralTokenProgram,
  TAccountBorrowTokenProgram,
  TAccountDestinationTokenProgram,
  TAccountRent,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? ACCRUE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    owner: { value: input.owner ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    position: { value: input.position ?? null, isWritable: true },
    collateralMint: { value: input.collateralMint ?? null, isWritable: false },
    destinationMint: {
      value: input.destinationMint ?? null,
      isWritable: false,
    },
    borrowMint: { value: input.borrowMint ?? null, isWritable: false },
    ownerCollateralAccount: {
      value: input.ownerCollateralAccount ?? null,
      isWritable: true,
    },
    positionCollateralAccount: {
      value: input.positionCollateralAccount ?? null,
      isWritable: true,
    },
    positionUsdcAccount: {
      value: input.positionUsdcAccount ?? null,
      isWritable: true,
    },
    positionDestinationAccount: {
      value: input.positionDestinationAccount ?? null,
      isWritable: true,
    },
    lendingMarket: { value: input.lendingMarket ?? null, isWritable: true },
    lendingMarketAuthority: {
      value: input.lendingMarketAuthority ?? null,
      isWritable: false,
    },
    obligation: { value: input.obligation ?? null, isWritable: true },
    userMetadata: { value: input.userMetadata ?? null, isWritable: true },
    collateralReserve: {
      value: input.collateralReserve ?? null,
      isWritable: true,
    },
    collateralReserveLiquiditySupply: {
      value: input.collateralReserveLiquiditySupply ?? null,
      isWritable: true,
    },
    collateralReserveCollateralMint: {
      value: input.collateralReserveCollateralMint ?? null,
      isWritable: true,
    },
    collateralReserveCollateralSupply: {
      value: input.collateralReserveCollateralSupply ?? null,
      isWritable: true,
    },
    borrowReserve: { value: input.borrowReserve ?? null, isWritable: true },
    borrowReserveLiquiditySupply: {
      value: input.borrowReserveLiquiditySupply ?? null,
      isWritable: true,
    },
    borrowReserveFeeReceiver: {
      value: input.borrowReserveFeeReceiver ?? null,
      isWritable: true,
    },
    collateralReserveFarmState: {
      value: input.collateralReserveFarmState ?? null,
      isWritable: true,
    },
    collateralObligationFarmState: {
      value: input.collateralObligationFarmState ?? null,
      isWritable: true,
    },
    borrowReserveFarmState: {
      value: input.borrowReserveFarmState ?? null,
      isWritable: true,
    },
    borrowObligationFarmState: {
      value: input.borrowObligationFarmState ?? null,
      isWritable: true,
    },
    scopePrices: { value: input.scopePrices ?? null, isWritable: false },
    farmsProgram: { value: input.farmsProgram ?? null, isWritable: false },
    swapProgram: { value: input.swapProgram ?? null, isWritable: false },
    kaminoProgram: { value: input.kaminoProgram ?? null, isWritable: false },
    instructionSysvar: {
      value: input.instructionSysvar ?? null,
      isWritable: false,
    },
    collateralTokenProgram: {
      value: input.collateralTokenProgram ?? null,
      isWritable: false,
    },
    kaminoCollateralTokenProgram: {
      value: input.kaminoCollateralTokenProgram ?? null,
      isWritable: false,
    },
    borrowTokenProgram: {
      value: input.borrowTokenProgram ?? null,
      isWritable: false,
    },
    destinationTokenProgram: {
      value: input.destinationTokenProgram ?? null,
      isWritable: false,
    },
    rent: { value: input.rent ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.farmsProgram.value) {
    accounts.farmsProgram.value =
      "FarmsPZpWu9i7Kky8tPN37rs2TpmMrAZrC7S7vJa91Hr" as Address<"FarmsPZpWu9i7Kky8tPN37rs2TpmMrAZrC7S7vJa91Hr">;
  }
  if (!accounts.swapProgram.value) {
    accounts.swapProgram.value =
      "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4" as Address<"JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4">;
  }
  if (!accounts.kaminoProgram.value) {
    accounts.kaminoProgram.value =
      "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD" as Address<"KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD">;
  }
  if (!accounts.instructionSysvar.value) {
    accounts.instructionSysvar.value =
      "Sysvar1nstructions1111111111111111111111111" as Address<"Sysvar1nstructions1111111111111111111111111">;
  }
  if (!accounts.kaminoCollateralTokenProgram.value) {
    accounts.kaminoCollateralTokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.rent.value) {
    accounts.rent.value =
      "SysvarRent111111111111111111111111111111111" as Address<"SysvarRent111111111111111111111111111111111">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.owner),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.position),
      getAccountMeta(accounts.collateralMint),
      getAccountMeta(accounts.destinationMint),
      getAccountMeta(accounts.borrowMint),
      getAccountMeta(accounts.ownerCollateralAccount),
      getAccountMeta(accounts.positionCollateralAccount),
      getAccountMeta(accounts.positionUsdcAccount),
      getAccountMeta(accounts.positionDestinationAccount),
      getAccountMeta(accounts.lendingMarket),
      getAccountMeta(accounts.lendingMarketAuthority),
      getAccountMeta(accounts.obligation),
      getAccountMeta(accounts.userMetadata),
      getAccountMeta(accounts.collateralReserve),
      getAccountMeta(accounts.collateralReserveLiquiditySupply),
      getAccountMeta(accounts.collateralReserveCollateralMint),
      getAccountMeta(accounts.collateralReserveCollateralSupply),
      getAccountMeta(accounts.borrowReserve),
      getAccountMeta(accounts.borrowReserveLiquiditySupply),
      getAccountMeta(accounts.borrowReserveFeeReceiver),
      getAccountMeta(accounts.collateralReserveFarmState),
      getAccountMeta(accounts.collateralObligationFarmState),
      getAccountMeta(accounts.borrowReserveFarmState),
      getAccountMeta(accounts.borrowObligationFarmState),
      getAccountMeta(accounts.scopePrices),
      getAccountMeta(accounts.farmsProgram),
      getAccountMeta(accounts.swapProgram),
      getAccountMeta(accounts.kaminoProgram),
      getAccountMeta(accounts.instructionSysvar),
      getAccountMeta(accounts.collateralTokenProgram),
      getAccountMeta(accounts.kaminoCollateralTokenProgram),
      getAccountMeta(accounts.borrowTokenProgram),
      getAccountMeta(accounts.destinationTokenProgram),
      getAccountMeta(accounts.rent),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getOpenPositionInstructionDataEncoder().encode(
      args as OpenPositionInstructionDataArgs,
    ),
    programAddress,
  } as OpenPositionInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountConfig,
    TAccountPosition,
    TAccountCollateralMint,
    TAccountDestinationMint,
    TAccountBorrowMint,
    TAccountOwnerCollateralAccount,
    TAccountPositionCollateralAccount,
    TAccountPositionUsdcAccount,
    TAccountPositionDestinationAccount,
    TAccountLendingMarket,
    TAccountLendingMarketAuthority,
    TAccountObligation,
    TAccountUserMetadata,
    TAccountCollateralReserve,
    TAccountCollateralReserveLiquiditySupply,
    TAccountCollateralReserveCollateralMint,
    TAccountCollateralReserveCollateralSupply,
    TAccountBorrowReserve,
    TAccountBorrowReserveLiquiditySupply,
    TAccountBorrowReserveFeeReceiver,
    TAccountCollateralReserveFarmState,
    TAccountCollateralObligationFarmState,
    TAccountBorrowReserveFarmState,
    TAccountBorrowObligationFarmState,
    TAccountScopePrices,
    TAccountFarmsProgram,
    TAccountSwapProgram,
    TAccountKaminoProgram,
    TAccountInstructionSysvar,
    TAccountCollateralTokenProgram,
    TAccountKaminoCollateralTokenProgram,
    TAccountBorrowTokenProgram,
    TAccountDestinationTokenProgram,
    TAccountRent,
    TAccountSystemProgram
  >);
}

export type ParsedOpenPositionInstruction<
  TProgram extends string = typeof ACCRUE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    owner: TAccountMetas[0];
    config: TAccountMetas[1];
    position: TAccountMetas[2];
    collateralMint: TAccountMetas[3];
    destinationMint: TAccountMetas[4];
    borrowMint: TAccountMetas[5];
    ownerCollateralAccount: TAccountMetas[6];
    positionCollateralAccount: TAccountMetas[7];
    positionUsdcAccount: TAccountMetas[8];
    positionDestinationAccount: TAccountMetas[9];
    lendingMarket: TAccountMetas[10];
    lendingMarketAuthority: TAccountMetas[11];
    obligation: TAccountMetas[12];
    userMetadata: TAccountMetas[13];
    collateralReserve: TAccountMetas[14];
    collateralReserveLiquiditySupply: TAccountMetas[15];
    collateralReserveCollateralMint: TAccountMetas[16];
    collateralReserveCollateralSupply: TAccountMetas[17];
    borrowReserve: TAccountMetas[18];
    borrowReserveLiquiditySupply: TAccountMetas[19];
    borrowReserveFeeReceiver: TAccountMetas[20];
    collateralReserveFarmState?: TAccountMetas[21] | undefined;
    collateralObligationFarmState?: TAccountMetas[22] | undefined;
    borrowReserveFarmState?: TAccountMetas[23] | undefined;
    borrowObligationFarmState?: TAccountMetas[24] | undefined;
    scopePrices: TAccountMetas[25];
    farmsProgram: TAccountMetas[26];
    swapProgram: TAccountMetas[27];
    kaminoProgram: TAccountMetas[28];
    instructionSysvar: TAccountMetas[29];
    collateralTokenProgram: TAccountMetas[30];
    kaminoCollateralTokenProgram: TAccountMetas[31];
    borrowTokenProgram: TAccountMetas[32];
    destinationTokenProgram: TAccountMetas[33];
    rent: TAccountMetas[34];
    systemProgram: TAccountMetas[35];
  };
  data: OpenPositionInstructionData;
};

export function parseOpenPositionInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedOpenPositionInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 36) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  const getNextOptionalAccount = () => {
    const accountMeta = getNextAccount();
    return accountMeta.address === ACCRUE_PROGRAM_ADDRESS
      ? undefined
      : accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      owner: getNextAccount(),
      config: getNextAccount(),
      position: getNextAccount(),
      collateralMint: getNextAccount(),
      destinationMint: getNextAccount(),
      borrowMint: getNextAccount(),
      ownerCollateralAccount: getNextAccount(),
      positionCollateralAccount: getNextAccount(),
      positionUsdcAccount: getNextAccount(),
      positionDestinationAccount: getNextAccount(),
      lendingMarket: getNextAccount(),
      lendingMarketAuthority: getNextAccount(),
      obligation: getNextAccount(),
      userMetadata: getNextAccount(),
      collateralReserve: getNextAccount(),
      collateralReserveLiquiditySupply: getNextAccount(),
      collateralReserveCollateralMint: getNextAccount(),
      collateralReserveCollateralSupply: getNextAccount(),
      borrowReserve: getNextAccount(),
      borrowReserveLiquiditySupply: getNextAccount(),
      borrowReserveFeeReceiver: getNextAccount(),
      collateralReserveFarmState: getNextOptionalAccount(),
      collateralObligationFarmState: getNextOptionalAccount(),
      borrowReserveFarmState: getNextOptionalAccount(),
      borrowObligationFarmState: getNextOptionalAccount(),
      scopePrices: getNextAccount(),
      farmsProgram: getNextAccount(),
      swapProgram: getNextAccount(),
      kaminoProgram: getNextAccount(),
      instructionSysvar: getNextAccount(),
      collateralTokenProgram: getNextAccount(),
      kaminoCollateralTokenProgram: getNextAccount(),
      borrowTokenProgram: getNextAccount(),
      destinationTokenProgram: getNextAccount(),
      rent: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getOpenPositionInstructionDataDecoder().decode(instruction.data),
  };
}
