import { JUPITER_V6_PROGRAM_ADDRESS, KAMINO_FARMS_PROGRAM_ADDRESS, KAMINO_LENDING_PROGRAM_ADDRESS } from "../../programIds.js";
/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { findConfigPda } from "../pdas/index.js";
import { ACCRUE_PROGRAM_ADDRESS } from "../programs/index.js";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared/index.js";

export const PROTECT_DISCRIMINATOR = new Uint8Array([
  7, 200, 63, 183, 60, 48, 87, 142,
]);

export function getProtectDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(PROTECT_DISCRIMINATOR);
}

export type ProtectInstruction<
  TProgram extends string = typeof ACCRUE_PROGRAM_ADDRESS,
  TAccountCaller extends string | AccountMeta<string> = string,
  TAccountCallerUsdcAccount extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountPosition extends string | AccountMeta<string> = string,
  TAccountDestinationMint extends string | AccountMeta<string> = string,
  TAccountBorrowMint extends string | AccountMeta<string> = string,
  TAccountPositionCollateralAccount extends string | AccountMeta<string> =
    string,
  TAccountPositionUsdcAccount extends string | AccountMeta<string> = string,
  TAccountPositionDestinationAccount extends string | AccountMeta<string> =
    string,
  TAccountObligation extends string | AccountMeta<string> = string,
  TAccountLendingMarket extends string | AccountMeta<string> = string,
  TAccountLendingMarketAuthority extends string | AccountMeta<string> = string,
  TAccountCollateralReserve extends string | AccountMeta<string> = string,
  TAccountBorrowReserve extends string | AccountMeta<string> = string,
  TAccountBorrowReserveLiquiditySupply extends string | AccountMeta<string> =
    string,
  TAccountBorrowReserveFarmState extends string | AccountMeta<string> = string,
  TAccountBorrowObligationFarmState extends string | AccountMeta<string> =
    string,
  TAccountCollateralScopePrices extends string | AccountMeta<string> = string,
  TAccountBorrowScopePrices extends string | AccountMeta<string> = string,
  TAccountDestinationScopePrices extends string | AccountMeta<string> = string,
  TAccountFarmsProgram extends string | AccountMeta<string> =
    "FarmsPZpWu9i7Kky8tPN37rs2TpmMrAZrC7S7vJa91Hr",
  TAccountSwapProgram extends string | AccountMeta<string> =
    "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4",
  TAccountKaminoProgram extends string | AccountMeta<string> =
    "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD",
  TAccountInstructionSysvar extends string | AccountMeta<string> =
    "Sysvar1nstructions1111111111111111111111111",
  TAccountBorrowTokenProgram extends string | AccountMeta<string> = string,
  TAccountDestinationTokenProgram extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountCaller extends string
        ? WritableSignerAccount<TAccountCaller> &
            AccountSignerMeta<TAccountCaller>
        : TAccountCaller,
      TAccountCallerUsdcAccount extends string
        ? WritableAccount<TAccountCallerUsdcAccount>
        : TAccountCallerUsdcAccount,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountPosition extends string
        ? WritableAccount<TAccountPosition>
        : TAccountPosition,
      TAccountDestinationMint extends string
        ? ReadonlyAccount<TAccountDestinationMint>
        : TAccountDestinationMint,
      TAccountBorrowMint extends string
        ? ReadonlyAccount<TAccountBorrowMint>
        : TAccountBorrowMint,
      TAccountPositionCollateralAccount extends string
        ? WritableAccount<TAccountPositionCollateralAccount>
        : TAccountPositionCollateralAccount,
      TAccountPositionUsdcAccount extends string
        ? WritableAccount<TAccountPositionUsdcAccount>
        : TAccountPositionUsdcAccount,
      TAccountPositionDestinationAccount extends string
        ? WritableAccount<TAccountPositionDestinationAccount>
        : TAccountPositionDestinationAccount,
      TAccountObligation extends string
        ? WritableAccount<TAccountObligation>
        : TAccountObligation,
      TAccountLendingMarket extends string
        ? WritableAccount<TAccountLendingMarket>
        : TAccountLendingMarket,
      TAccountLendingMarketAuthority extends string
        ? ReadonlyAccount<TAccountLendingMarketAuthority>
        : TAccountLendingMarketAuthority,
      TAccountCollateralReserve extends string
        ? WritableAccount<TAccountCollateralReserve>
        : TAccountCollateralReserve,
      TAccountBorrowReserve extends string
        ? WritableAccount<TAccountBorrowReserve>
        : TAccountBorrowReserve,
      TAccountBorrowReserveLiquiditySupply extends string
        ? WritableAccount<TAccountBorrowReserveLiquiditySupply>
        : TAccountBorrowReserveLiquiditySupply,
      TAccountBorrowReserveFarmState extends string
        ? WritableAccount<TAccountBorrowReserveFarmState>
        : TAccountBorrowReserveFarmState,
      TAccountBorrowObligationFarmState extends string
        ? WritableAccount<TAccountBorrowObligationFarmState>
        : TAccountBorrowObligationFarmState,
      TAccountCollateralScopePrices extends string
        ? ReadonlyAccount<TAccountCollateralScopePrices>
        : TAccountCollateralScopePrices,
      TAccountBorrowScopePrices extends string
        ? ReadonlyAccount<TAccountBorrowScopePrices>
        : TAccountBorrowScopePrices,
      TAccountDestinationScopePrices extends string
        ? ReadonlyAccount<TAccountDestinationScopePrices>
        : TAccountDestinationScopePrices,
      TAccountFarmsProgram extends string
        ? ReadonlyAccount<TAccountFarmsProgram>
        : TAccountFarmsProgram,
      TAccountSwapProgram extends string
        ? ReadonlyAccount<TAccountSwapProgram>
        : TAccountSwapProgram,
      TAccountKaminoProgram extends string
        ? ReadonlyAccount<TAccountKaminoProgram>
        : TAccountKaminoProgram,
      TAccountInstructionSysvar extends string
        ? ReadonlyAccount<TAccountInstructionSysvar>
        : TAccountInstructionSysvar,
      TAccountBorrowTokenProgram extends string
        ? ReadonlyAccount<TAccountBorrowTokenProgram>
        : TAccountBorrowTokenProgram,
      TAccountDestinationTokenProgram extends string
        ? ReadonlyAccount<TAccountDestinationTokenProgram>
        : TAccountDestinationTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type ProtectInstructionData = {
  discriminator: ReadonlyUint8Array;
  ownerMinimumUsdcOut: bigint;
  jupiterRouteData: ReadonlyUint8Array;
};

export type ProtectInstructionDataArgs = {
  ownerMinimumUsdcOut: number | bigint;
  jupiterRouteData: ReadonlyUint8Array;
};

export function getProtectInstructionDataEncoder(): Encoder<ProtectInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["ownerMinimumUsdcOut", getU64Encoder()],
      [
        "jupiterRouteData",
        addEncoderSizePrefix(getBytesEncoder(), getU32Encoder()),
      ],
    ]),
    (value) => ({ ...value, discriminator: PROTECT_DISCRIMINATOR }),
  );
}

export function getProtectInstructionDataDecoder(): Decoder<ProtectInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["ownerMinimumUsdcOut", getU64Decoder()],
    [
      "jupiterRouteData",
      addDecoderSizePrefix(getBytesDecoder(), getU32Decoder()),
    ],
  ]);
}

export function getProtectInstructionDataCodec(): Codec<
  ProtectInstructionDataArgs,
  ProtectInstructionData
> {
  return combineCodec(
    getProtectInstructionDataEncoder(),
    getProtectInstructionDataDecoder(),
  );
}

export type ProtectAsyncInput<
  TAccountCaller extends string = string,
  TAccountCallerUsdcAccount extends string = string,
  TAccountConfig extends string = string,
  TAccountPosition extends string = string,
  TAccountDestinationMint extends string = string,
  TAccountBorrowMint extends string = string,
  TAccountPositionCollateralAccount extends string = string,
  TAccountPositionUsdcAccount extends string = string,
  TAccountPositionDestinationAccount extends string = string,
  TAccountObligation extends string = string,
  TAccountLendingMarket extends string = string,
  TAccountLendingMarketAuthority extends string = string,
  TAccountCollateralReserve extends string = string,
  TAccountBorrowReserve extends string = string,
  TAccountBorrowReserveLiquiditySupply extends string = string,
  TAccountBorrowReserveFarmState extends string = string,
  TAccountBorrowObligationFarmState extends string = string,
  TAccountCollateralScopePrices extends string = string,
  TAccountBorrowScopePrices extends string = string,
  TAccountDestinationScopePrices extends string = string,
  TAccountFarmsProgram extends string = string,
  TAccountSwapProgram extends string = string,
  TAccountKaminoProgram extends string = string,
  TAccountInstructionSysvar extends string = string,
  TAccountBorrowTokenProgram extends string = string,
  TAccountDestinationTokenProgram extends string = string,
> = {
  caller: TransactionSigner<TAccountCaller>;
  callerUsdcAccount: Address<TAccountCallerUsdcAccount>;
  config?: Address<TAccountConfig>;
  position: Address<TAccountPosition>;
  destinationMint: Address<TAccountDestinationMint>;
  borrowMint: Address<TAccountBorrowMint>;
  positionCollateralAccount: Address<TAccountPositionCollateralAccount>;
  positionUsdcAccount: Address<TAccountPositionUsdcAccount>;
  positionDestinationAccount: Address<TAccountPositionDestinationAccount>;
  obligation: Address<TAccountObligation>;
  lendingMarket: Address<TAccountLendingMarket>;
  lendingMarketAuthority: Address<TAccountLendingMarketAuthority>;
  collateralReserve: Address<TAccountCollateralReserve>;
  borrowReserve: Address<TAccountBorrowReserve>;
  borrowReserveLiquiditySupply: Address<TAccountBorrowReserveLiquiditySupply>;
  borrowReserveFarmState?: Address<TAccountBorrowReserveFarmState>;
  borrowObligationFarmState?: Address<TAccountBorrowObligationFarmState>;
  collateralScopePrices: Address<TAccountCollateralScopePrices>;
  borrowScopePrices: Address<TAccountBorrowScopePrices>;
  destinationScopePrices: Address<TAccountDestinationScopePrices>;
  farmsProgram?: Address<TAccountFarmsProgram>;
  swapProgram?: Address<TAccountSwapProgram>;
  kaminoProgram?: Address<TAccountKaminoProgram>;
  instructionSysvar?: Address<TAccountInstructionSysvar>;
  borrowTokenProgram: Address<TAccountBorrowTokenProgram>;
  destinationTokenProgram: Address<TAccountDestinationTokenProgram>;
  ownerMinimumUsdcOut: ProtectInstructionDataArgs["ownerMinimumUsdcOut"];
  jupiterRouteData: ProtectInstructionDataArgs["jupiterRouteData"];
};

export async function getProtectInstructionAsync<
  TAccountCaller extends string,
  TAccountCallerUsdcAccount extends string,
  TAccountConfig extends string,
  TAccountPosition extends string,
  TAccountDestinationMint extends string,
  TAccountBorrowMint extends string,
  TAccountPositionCollateralAccount extends string,
  TAccountPositionUsdcAccount extends string,
  TAccountPositionDestinationAccount extends string,
  TAccountObligation extends string,
  TAccountLendingMarket extends string,
  TAccountLendingMarketAuthority extends string,
  TAccountCollateralReserve extends string,
  TAccountBorrowReserve extends string,
  TAccountBorrowReserveLiquiditySupply extends string,
  TAccountBorrowReserveFarmState extends string,
  TAccountBorrowObligationFarmState extends string,
  TAccountCollateralScopePrices extends string,
  TAccountBorrowScopePrices extends string,
  TAccountDestinationScopePrices extends string,
  TAccountFarmsProgram extends string,
  TAccountSwapProgram extends string,
  TAccountKaminoProgram extends string,
  TAccountInstructionSysvar extends string,
  TAccountBorrowTokenProgram extends string,
  TAccountDestinationTokenProgram extends string,
  TProgramAddress extends Address = typeof ACCRUE_PROGRAM_ADDRESS,
>(
  input: ProtectAsyncInput<
    TAccountCaller,
    TAccountCallerUsdcAccount,
    TAccountConfig,
    TAccountPosition,
    TAccountDestinationMint,
    TAccountBorrowMint,
    TAccountPositionCollateralAccount,
    TAccountPositionUsdcAccount,
    TAccountPositionDestinationAccount,
    TAccountObligation,
    TAccountLendingMarket,
    TAccountLendingMarketAuthority,
    TAccountCollateralReserve,
    TAccountBorrowReserve,
    TAccountBorrowReserveLiquiditySupply,
    TAccountBorrowReserveFarmState,
    TAccountBorrowObligationFarmState,
    TAccountCollateralScopePrices,
    TAccountBorrowScopePrices,
    TAccountDestinationScopePrices,
    TAccountFarmsProgram,
    TAccountSwapProgram,
    TAccountKaminoProgram,
    TAccountInstructionSysvar,
    TAccountBorrowTokenProgram,
    TAccountDestinationTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  ProtectInstruction<
    TProgramAddress,
    TAccountCaller,
    TAccountCallerUsdcAccount,
    TAccountConfig,
    TAccountPosition,
    TAccountDestinationMint,
    TAccountBorrowMint,
    TAccountPositionCollateralAccount,
    TAccountPositionUsdcAccount,
    TAccountPositionDestinationAccount,
    TAccountObligation,
    TAccountLendingMarket,
    TAccountLendingMarketAuthority,
    TAccountCollateralReserve,
    TAccountBorrowReserve,
    TAccountBorrowReserveLiquiditySupply,
    TAccountBorrowReserveFarmState,
    TAccountBorrowObligationFarmState,
    TAccountCollateralScopePrices,
    TAccountBorrowScopePrices,
    TAccountDestinationScopePrices,
    TAccountFarmsProgram,
    TAccountSwapProgram,
    TAccountKaminoProgram,
    TAccountInstructionSysvar,
    TAccountBorrowTokenProgram,
    TAccountDestinationTokenProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ACCRUE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    caller: { value: input.caller ?? null, isWritable: true },
    callerUsdcAccount: {
      value: input.callerUsdcAccount ?? null,
      isWritable: true,
    },
    config: { value: input.config ?? null, isWritable: false },
    position: { value: input.position ?? null, isWritable: true },
    destinationMint: {
      value: input.destinationMint ?? null,
      isWritable: false,
    },
    borrowMint: { value: input.borrowMint ?? null, isWritable: false },
    positionCollateralAccount: {
      value: input.positionCollateralAccount ?? null,
      isWritable: true,
    },
    positionUsdcAccount: {
      value: input.positionUsdcAccount ?? null,
      isWritable: true,
    },
    positionDestinationAccount: {
      value: input.positionDestinationAccount ?? null,
      isWritable: true,
    },
    obligation: { value: input.obligation ?? null, isWritable: true },
    lendingMarket: { value: input.lendingMarket ?? null, isWritable: true },
    lendingMarketAuthority: {
      value: input.lendingMarketAuthority ?? null,
      isWritable: false,
    },
    collateralReserve: {
      value: input.collateralReserve ?? null,
      isWritable: true,
    },
    borrowReserve: { value: input.borrowReserve ?? null, isWritable: true },
    borrowReserveLiquiditySupply: {
      value: input.borrowReserveLiquiditySupply ?? null,
      isWritable: true,
    },
    borrowReserveFarmState: {
      value: input.borrowReserveFarmState ?? null,
      isWritable: true,
    },
    borrowObligationFarmState: {
      value: input.borrowObligationFarmState ?? null,
      isWritable: true,
    },
    collateralScopePrices: {
      value: input.collateralScopePrices ?? null,
      isWritable: false,
    },
    borrowScopePrices: {
      value: input.borrowScopePrices ?? null,
      isWritable: false,
    },
    destinationScopePrices: {
      value: input.destinationScopePrices ?? null,
      isWritable: false,
    },
    farmsProgram: { value: input.farmsProgram ?? null, isWritable: false },
    swapProgram: { value: input.swapProgram ?? null, isWritable: false },
    kaminoProgram: { value: input.kaminoProgram ?? null, isWritable: false },
    instructionSysvar: {
      value: input.instructionSysvar ?? null,
      isWritable: false,
    },
    borrowTokenProgram: {
      value: input.borrowTokenProgram ?? null,
      isWritable: false,
    },
    destinationTokenProgram: {
      value: input.destinationTokenProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.farmsProgram.value) {
    accounts.farmsProgram.value =
      (KAMINO_FARMS_PROGRAM_ADDRESS as Address<"FarmsPZpWu9i7Kky8tPN37rs2TpmMrAZrC7S7vJa91Hr">);
  }
  if (!accounts.swapProgram.value) {
    accounts.swapProgram.value =
      (JUPITER_V6_PROGRAM_ADDRESS as Address<"JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4">);
  }
  if (!accounts.kaminoProgram.value) {
    accounts.kaminoProgram.value =
      (KAMINO_LENDING_PROGRAM_ADDRESS as Address<"KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD">);
  }
  if (!accounts.instructionSysvar.value) {
    accounts.instructionSysvar.value =
      "Sysvar1nstructions1111111111111111111111111" as Address<"Sysvar1nstructions1111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.caller),
      getAccountMeta(accounts.callerUsdcAccount),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.position),
      getAccountMeta(accounts.destinationMint),
      getAccountMeta(accounts.borrowMint),
      getAccountMeta(accounts.positionCollateralAccount),
      getAccountMeta(accounts.positionUsdcAccount),
      getAccountMeta(accounts.positionDestinationAccount),
      getAccountMeta(accounts.obligation),
      getAccountMeta(accounts.lendingMarket),
      getAccountMeta(accounts.lendingMarketAuthority),
      getAccountMeta(accounts.collateralReserve),
      getAccountMeta(accounts.borrowReserve),
      getAccountMeta(accounts.borrowReserveLiquiditySupply),
      getAccountMeta(accounts.borrowReserveFarmState),
      getAccountMeta(accounts.borrowObligationFarmState),
      getAccountMeta(accounts.collateralScopePrices),
      getAccountMeta(accounts.borrowScopePrices),
      getAccountMeta(accounts.destinationScopePrices),
      getAccountMeta(accounts.farmsProgram),
      getAccountMeta(accounts.swapProgram),
      getAccountMeta(accounts.kaminoProgram),
      getAccountMeta(accounts.instructionSysvar),
      getAccountMeta(accounts.borrowTokenProgram),
      getAccountMeta(accounts.destinationTokenProgram),
    ],
    data: getProtectInstructionDataEncoder().encode(
      args as ProtectInstructionDataArgs,
    ),
    programAddress,
  } as ProtectInstruction<
    TProgramAddress,
    TAccountCaller,
    TAccountCallerUsdcAccount,
    TAccountConfig,
    TAccountPosition,
    TAccountDestinationMint,
    TAccountBorrowMint,
    TAccountPositionCollateralAccount,
    TAccountPositionUsdcAccount,
    TAccountPositionDestinationAccount,
    TAccountObligation,
    TAccountLendingMarket,
    TAccountLendingMarketAuthority,
    TAccountCollateralReserve,
    TAccountBorrowReserve,
    TAccountBorrowReserveLiquiditySupply,
    TAccountBorrowReserveFarmState,
    TAccountBorrowObligationFarmState,
    TAccountCollateralScopePrices,
    TAccountBorrowScopePrices,
    TAccountDestinationScopePrices,
    TAccountFarmsProgram,
    TAccountSwapProgram,
    TAccountKaminoProgram,
    TAccountInstructionSysvar,
    TAccountBorrowTokenProgram,
    TAccountDestinationTokenProgram
  >);
}

export type ProtectInput<
  TAccountCaller extends string = string,
  TAccountCallerUsdcAccount extends string = string,
  TAccountConfig extends string = string,
  TAccountPosition extends string = string,
  TAccountDestinationMint extends string = string,
  TAccountBorrowMint extends string = string,
  TAccountPositionCollateralAccount extends string = string,
  TAccountPositionUsdcAccount extends string = string,
  TAccountPositionDestinationAccount extends string = string,
  TAccountObligation extends string = string,
  TAccountLendingMarket extends string = string,
  TAccountLendingMarketAuthority extends string = string,
  TAccountCollateralReserve extends string = string,
  TAccountBorrowReserve extends string = string,
  TAccountBorrowReserveLiquiditySupply extends string = string,
  TAccountBorrowReserveFarmState extends string = string,
  TAccountBorrowObligationFarmState extends string = string,
  TAccountCollateralScopePrices extends string = string,
  TAccountBorrowScopePrices extends string = string,
  TAccountDestinationScopePrices extends string = string,
  TAccountFarmsProgram extends string = string,
  TAccountSwapProgram extends string = string,
  TAccountKaminoProgram extends string = string,
  TAccountInstructionSysvar extends string = string,
  TAccountBorrowTokenProgram extends string = string,
  TAccountDestinationTokenProgram extends string = string,
> = {
  caller: TransactionSigner<TAccountCaller>;
  callerUsdcAccount: Address<TAccountCallerUsdcAccount>;
  config: Address<TAccountConfig>;
  position: Address<TAccountPosition>;
  destinationMint: Address<TAccountDestinationMint>;
  borrowMint: Address<TAccountBorrowMint>;
  positionCollateralAccount: Address<TAccountPositionCollateralAccount>;
  positionUsdcAccount: Address<TAccountPositionUsdcAccount>;
  positionDestinationAccount: Address<TAccountPositionDestinationAccount>;
  obligation: Address<TAccountObligation>;
  lendingMarket: Address<TAccountLendingMarket>;
  lendingMarketAuthority: Address<TAccountLendingMarketAuthority>;
  collateralReserve: Address<TAccountCollateralReserve>;
  borrowReserve: Address<TAccountBorrowReserve>;
  borrowReserveLiquiditySupply: Address<TAccountBorrowReserveLiquiditySupply>;
  borrowReserveFarmState?: Address<TAccountBorrowReserveFarmState>;
  borrowObligationFarmState?: Address<TAccountBorrowObligationFarmState>;
  collateralScopePrices: Address<TAccountCollateralScopePrices>;
  borrowScopePrices: Address<TAccountBorrowScopePrices>;
  destinationScopePrices: Address<TAccountDestinationScopePrices>;
  farmsProgram?: Address<TAccountFarmsProgram>;
  swapProgram?: Address<TAccountSwapProgram>;
  kaminoProgram?: Address<TAccountKaminoProgram>;
  instructionSysvar?: Address<TAccountInstructionSysvar>;
  borrowTokenProgram: Address<TAccountBorrowTokenProgram>;
  destinationTokenProgram: Address<TAccountDestinationTokenProgram>;
  ownerMinimumUsdcOut: ProtectInstructionDataArgs["ownerMinimumUsdcOut"];
  jupiterRouteData: ProtectInstructionDataArgs["jupiterRouteData"];
};

export function getProtectInstruction<
  TAccountCaller extends string,
  TAccountCallerUsdcAccount extends string,
  TAccountConfig extends string,
  TAccountPosition extends string,
  TAccountDestinationMint extends string,
  TAccountBorrowMint extends string,
  TAccountPositionCollateralAccount extends string,
  TAccountPositionUsdcAccount extends string,
  TAccountPositionDestinationAccount extends string,
  TAccountObligation extends string,
  TAccountLendingMarket extends string,
  TAccountLendingMarketAuthority extends string,
  TAccountCollateralReserve extends string,
  TAccountBorrowReserve extends string,
  TAccountBorrowReserveLiquiditySupply extends string,
  TAccountBorrowReserveFarmState extends string,
  TAccountBorrowObligationFarmState extends string,
  TAccountCollateralScopePrices extends string,
  TAccountBorrowScopePrices extends string,
  TAccountDestinationScopePrices extends string,
  TAccountFarmsProgram extends string,
  TAccountSwapProgram extends string,
  TAccountKaminoProgram extends string,
  TAccountInstructionSysvar extends string,
  TAccountBorrowTokenProgram extends string,
  TAccountDestinationTokenProgram extends string,
  TProgramAddress extends Address = typeof ACCRUE_PROGRAM_ADDRESS,
>(
  input: ProtectInput<
    TAccountCaller,
    TAccountCallerUsdcAccount,
    TAccountConfig,
    TAccountPosition,
    TAccountDestinationMint,
    TAccountBorrowMint,
    TAccountPositionCollateralAccount,
    TAccountPositionUsdcAccount,
    TAccountPositionDestinationAccount,
    TAccountObligation,
    TAccountLendingMarket,
    TAccountLendingMarketAuthority,
    TAccountCollateralReserve,
    TAccountBorrowReserve,
    TAccountBorrowReserveLiquiditySupply,
    TAccountBorrowReserveFarmState,
    TAccountBorrowObligationFarmState,
    TAccountCollateralScopePrices,
    TAccountBorrowScopePrices,
    TAccountDestinationScopePrices,
    TAccountFarmsProgram,
    TAccountSwapProgram,
    TAccountKaminoProgram,
    TAccountInstructionSysvar,
    TAccountBorrowTokenProgram,
    TAccountDestinationTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): ProtectInstruction<
  TProgramAddress,
  TAccountCaller,
  TAccountCallerUsdcAccount,
  TAccountConfig,
  TAccountPosition,
  TAccountDestinationMint,
  TAccountBorrowMint,
  TAccountPositionCollateralAccount,
  TAccountPositionUsdcAccount,
  TAccountPositionDestinationAccount,
  TAccountObligation,
  TAccountLendingMarket,
  TAccountLendingMarketAuthority,
  TAccountCollateralReserve,
  TAccountBorrowReserve,
  TAccountBorrowReserveLiquiditySupply,
  TAccountBorrowReserveFarmState,
  TAccountBorrowObligationFarmState,
  TAccountCollateralScopePrices,
  TAccountBorrowScopePrices,
  TAccountDestinationScopePrices,
  TAccountFarmsProgram,
  TAccountSwapProgram,
  TAccountKaminoProgram,
  TAccountInstructionSysvar,
  TAccountBorrowTokenProgram,
  TAccountDestinationTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? ACCRUE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    caller: { value: input.caller ?? null, isWritable: true },
    callerUsdcAccount: {
      value: input.callerUsdcAccount ?? null,
      isWritable: true,
    },
    config: { value: input.config ?? null, isWritable: false },
    position: { value: input.position ?? null, isWritable: true },
    destinationMint: {
      value: input.destinationMint ?? null,
      isWritable: false,
    },
    borrowMint: { value: input.borrowMint ?? null, isWritable: false },
    positionCollateralAccount: {
      value: input.positionCollateralAccount ?? null,
      isWritable: true,
    },
    positionUsdcAccount: {
      value: input.positionUsdcAccount ?? null,
      isWritable: true,
    },
    positionDestinationAccount: {
      value: input.positionDestinationAccount ?? null,
      isWritable: true,
    },
    obligation: { value: input.obligation ?? null, isWritable: true },
    lendingMarket: { value: input.lendingMarket ?? null, isWritable: true },
    lendingMarketAuthority: {
      value: input.lendingMarketAuthority ?? null,
      isWritable: false,
    },
    collateralReserve: {
      value: input.collateralReserve ?? null,
      isWritable: true,
    },
    borrowReserve: { value: input.borrowReserve ?? null, isWritable: true },
    borrowReserveLiquiditySupply: {
      value: input.borrowReserveLiquiditySupply ?? null,
      isWritable: true,
    },
    borrowReserveFarmState: {
      value: input.borrowReserveFarmState ?? null,
      isWritable: true,
    },
    borrowObligationFarmState: {
      value: input.borrowObligationFarmState ?? null,
      isWritable: true,
    },
    collateralScopePrices: {
      value: input.collateralScopePrices ?? null,
      isWritable: false,
    },
    borrowScopePrices: {
      value: input.borrowScopePrices ?? null,
      isWritable: false,
    },
    destinationScopePrices: {
      value: input.destinationScopePrices ?? null,
      isWritable: false,
    },
    farmsProgram: { value: input.farmsProgram ?? null, isWritable: false },
    swapProgram: { value: input.swapProgram ?? null, isWritable: false },
    kaminoProgram: { value: input.kaminoProgram ?? null, isWritable: false },
    instructionSysvar: {
      value: input.instructionSysvar ?? null,
      isWritable: false,
    },
    borrowTokenProgram: {
      value: input.borrowTokenProgram ?? null,
      isWritable: false,
    },
    destinationTokenProgram: {
      value: input.destinationTokenProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.farmsProgram.value) {
    accounts.farmsProgram.value =
      (KAMINO_FARMS_PROGRAM_ADDRESS as Address<"FarmsPZpWu9i7Kky8tPN37rs2TpmMrAZrC7S7vJa91Hr">);
  }
  if (!accounts.swapProgram.value) {
    accounts.swapProgram.value =
      (JUPITER_V6_PROGRAM_ADDRESS as Address<"JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4">);
  }
  if (!accounts.kaminoProgram.value) {
    accounts.kaminoProgram.value =
      (KAMINO_LENDING_PROGRAM_ADDRESS as Address<"KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD">);
  }
  if (!accounts.instructionSysvar.value) {
    accounts.instructionSysvar.value =
      "Sysvar1nstructions1111111111111111111111111" as Address<"Sysvar1nstructions1111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.caller),
      getAccountMeta(accounts.callerUsdcAccount),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.position),
      getAccountMeta(accounts.destinationMint),
      getAccountMeta(accounts.borrowMint),
      getAccountMeta(accounts.positionCollateralAccount),
      getAccountMeta(accounts.positionUsdcAccount),
      getAccountMeta(accounts.positionDestinationAccount),
      getAccountMeta(accounts.obligation),
      getAccountMeta(accounts.lendingMarket),
      getAccountMeta(accounts.lendingMarketAuthority),
      getAccountMeta(accounts.collateralReserve),
      getAccountMeta(accounts.borrowReserve),
      getAccountMeta(accounts.borrowReserveLiquiditySupply),
      getAccountMeta(accounts.borrowReserveFarmState),
      getAccountMeta(accounts.borrowObligationFarmState),
      getAccountMeta(accounts.collateralScopePrices),
      getAccountMeta(accounts.borrowScopePrices),
      getAccountMeta(accounts.destinationScopePrices),
      getAccountMeta(accounts.farmsProgram),
      getAccountMeta(accounts.swapProgram),
      getAccountMeta(accounts.kaminoProgram),
      getAccountMeta(accounts.instructionSysvar),
      getAccountMeta(accounts.borrowTokenProgram),
      getAccountMeta(accounts.destinationTokenProgram),
    ],
    data: getProtectInstructionDataEncoder().encode(
      args as ProtectInstructionDataArgs,
    ),
    programAddress,
  } as ProtectInstruction<
    TProgramAddress,
    TAccountCaller,
    TAccountCallerUsdcAccount,
    TAccountConfig,
    TAccountPosition,
    TAccountDestinationMint,
    TAccountBorrowMint,
    TAccountPositionCollateralAccount,
    TAccountPositionUsdcAccount,
    TAccountPositionDestinationAccount,
    TAccountObligation,
    TAccountLendingMarket,
    TAccountLendingMarketAuthority,
    TAccountCollateralReserve,
    TAccountBorrowReserve,
    TAccountBorrowReserveLiquiditySupply,
    TAccountBorrowReserveFarmState,
    TAccountBorrowObligationFarmState,
    TAccountCollateralScopePrices,
    TAccountBorrowScopePrices,
    TAccountDestinationScopePrices,
    TAccountFarmsProgram,
    TAccountSwapProgram,
    TAccountKaminoProgram,
    TAccountInstructionSysvar,
    TAccountBorrowTokenProgram,
    TAccountDestinationTokenProgram
  >);
}

export type ParsedProtectInstruction<
  TProgram extends string = typeof ACCRUE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    caller: TAccountMetas[0];
    callerUsdcAccount: TAccountMetas[1];
    config: TAccountMetas[2];
    position: TAccountMetas[3];
    destinationMint: TAccountMetas[4];
    borrowMint: TAccountMetas[5];
    positionCollateralAccount: TAccountMetas[6];
    positionUsdcAccount: TAccountMetas[7];
    positionDestinationAccount: TAccountMetas[8];
    obligation: TAccountMetas[9];
    lendingMarket: TAccountMetas[10];
    lendingMarketAuthority: TAccountMetas[11];
    collateralReserve: TAccountMetas[12];
    borrowReserve: TAccountMetas[13];
    borrowReserveLiquiditySupply: TAccountMetas[14];
    borrowReserveFarmState?: TAccountMetas[15] | undefined;
    borrowObligationFarmState?: TAccountMetas[16] | undefined;
    collateralScopePrices: TAccountMetas[17];
    borrowScopePrices: TAccountMetas[18];
    destinationScopePrices: TAccountMetas[19];
    farmsProgram: TAccountMetas[20];
    swapProgram: TAccountMetas[21];
    kaminoProgram: TAccountMetas[22];
    instructionSysvar: TAccountMetas[23];
    borrowTokenProgram: TAccountMetas[24];
    destinationTokenProgram: TAccountMetas[25];
  };
  data: ProtectInstructionData;
};

export function parseProtectInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedProtectInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 26) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  const getNextOptionalAccount = () => {
    const accountMeta = getNextAccount();
    return accountMeta.address === ACCRUE_PROGRAM_ADDRESS
      ? undefined
      : accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      caller: getNextAccount(),
      callerUsdcAccount: getNextAccount(),
      config: getNextAccount(),
      position: getNextAccount(),
      destinationMint: getNextAccount(),
      borrowMint: getNextAccount(),
      positionCollateralAccount: getNextAccount(),
      positionUsdcAccount: getNextAccount(),
      positionDestinationAccount: getNextAccount(),
      obligation: getNextAccount(),
      lendingMarket: getNextAccount(),
      lendingMarketAuthority: getNextAccount(),
      collateralReserve: getNextAccount(),
      borrowReserve: getNextAccount(),
      borrowReserveLiquiditySupply: getNextAccount(),
      borrowReserveFarmState: getNextOptionalAccount(),
      borrowObligationFarmState: getNextOptionalAccount(),
      collateralScopePrices: getNextAccount(),
      borrowScopePrices: getNextAccount(),
      destinationScopePrices: getNextAccount(),
      farmsProgram: getNextAccount(),
      swapProgram: getNextAccount(),
      kaminoProgram: getNextAccount(),
      instructionSysvar: getNextAccount(),
      borrowTokenProgram: getNextAccount(),
      destinationTokenProgram: getNextAccount(),
    },
    data: getProtectInstructionDataDecoder().decode(instruction.data),
  };
}
