/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { ACCRUE_PROGRAM_ADDRESS } from "../programs/index.js";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared/index.js";

export const REPAY_DISCRIMINATOR = new Uint8Array([
  234, 103, 67, 82, 208, 234, 219, 166,
]);

export function getRepayDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(REPAY_DISCRIMINATOR);
}

export type RepayInstruction<
  TProgram extends string = typeof ACCRUE_PROGRAM_ADDRESS,
  TAccountOwner extends string | AccountMeta<string> = string,
  TAccountPosition extends string | AccountMeta<string> = string,
  TAccountBorrowMint extends string | AccountMeta<string> = string,
  TAccountPositionCollateralAccount extends string | AccountMeta<string> =
    string,
  TAccountPositionUsdcAccount extends string | AccountMeta<string> = string,
  TAccountPositionDestinationAccount extends string | AccountMeta<string> =
    string,
  TAccountOwnerUsdcAccount extends string | AccountMeta<string> = string,
  TAccountObligation extends string | AccountMeta<string> = string,
  TAccountLendingMarket extends string | AccountMeta<string> = string,
  TAccountLendingMarketAuthority extends string | AccountMeta<string> = string,
  TAccountCollateralReserve extends string | AccountMeta<string> = string,
  TAccountBorrowReserve extends string | AccountMeta<string> = string,
  TAccountBorrowReserveLiquiditySupply extends string | AccountMeta<string> =
    string,
  TAccountBorrowReserveFarmState extends string | AccountMeta<string> = string,
  TAccountBorrowObligationFarmState extends string | AccountMeta<string> =
    string,
  TAccountCollateralScopePrices extends string | AccountMeta<string> = string,
  TAccountBorrowScopePrices extends string | AccountMeta<string> = string,
  TAccountFarmsProgram extends string | AccountMeta<string> =
    "FarmsPZpWu9i7Kky8tPN37rs2TpmMrAZrC7S7vJa91Hr",
  TAccountKaminoProgram extends string | AccountMeta<string> =
    "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD",
  TAccountInstructionSysvar extends string | AccountMeta<string> =
    "Sysvar1nstructions1111111111111111111111111",
  TAccountBorrowTokenProgram extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountOwner extends string
        ? WritableSignerAccount<TAccountOwner> &
            AccountSignerMeta<TAccountOwner>
        : TAccountOwner,
      TAccountPosition extends string
        ? WritableAccount<TAccountPosition>
        : TAccountPosition,
      TAccountBorrowMint extends string
        ? ReadonlyAccount<TAccountBorrowMint>
        : TAccountBorrowMint,
      TAccountPositionCollateralAccount extends string
        ? WritableAccount<TAccountPositionCollateralAccount>
        : TAccountPositionCollateralAccount,
      TAccountPositionUsdcAccount extends string
        ? WritableAccount<TAccountPositionUsdcAccount>
        : TAccountPositionUsdcAccount,
      TAccountPositionDestinationAccount extends string
        ? WritableAccount<TAccountPositionDestinationAccount>
        : TAccountPositionDestinationAccount,
      TAccountOwnerUsdcAccount extends string
        ? WritableAccount<TAccountOwnerUsdcAccount>
        : TAccountOwnerUsdcAccount,
      TAccountObligation extends string
        ? WritableAccount<TAccountObligation>
        : TAccountObligation,
      TAccountLendingMarket extends string
        ? WritableAccount<TAccountLendingMarket>
        : TAccountLendingMarket,
      TAccountLendingMarketAuthority extends string
        ? ReadonlyAccount<TAccountLendingMarketAuthority>
        : TAccountLendingMarketAuthority,
      TAccountCollateralReserve extends string
        ? WritableAccount<TAccountCollateralReserve>
        : TAccountCollateralReserve,
      TAccountBorrowReserve extends string
        ? WritableAccount<TAccountBorrowReserve>
        : TAccountBorrowReserve,
      TAccountBorrowReserveLiquiditySupply extends string
        ? WritableAccount<TAccountBorrowReserveLiquiditySupply>
        : TAccountBorrowReserveLiquiditySupply,
      TAccountBorrowReserveFarmState extends string
        ? WritableAccount<TAccountBorrowReserveFarmState>
        : TAccountBorrowReserveFarmState,
      TAccountBorrowObligationFarmState extends string
        ? WritableAccount<TAccountBorrowObligationFarmState>
        : TAccountBorrowObligationFarmState,
      TAccountCollateralScopePrices extends string
        ? ReadonlyAccount<TAccountCollateralScopePrices>
        : TAccountCollateralScopePrices,
      TAccountBorrowScopePrices extends string
        ? ReadonlyAccount<TAccountBorrowScopePrices>
        : TAccountBorrowScopePrices,
      TAccountFarmsProgram extends string
        ? ReadonlyAccount<TAccountFarmsProgram>
        : TAccountFarmsProgram,
      TAccountKaminoProgram extends string
        ? ReadonlyAccount<TAccountKaminoProgram>
        : TAccountKaminoProgram,
      TAccountInstructionSysvar extends string
        ? ReadonlyAccount<TAccountInstructionSysvar>
        : TAccountInstructionSysvar,
      TAccountBorrowTokenProgram extends string
        ? ReadonlyAccount<TAccountBorrowTokenProgram>
        : TAccountBorrowTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type RepayInstructionData = {
  discriminator: ReadonlyUint8Array;
  requestedAmount: bigint;
};

export type RepayInstructionDataArgs = { requestedAmount: number | bigint };

export function getRepayInstructionDataEncoder(): FixedSizeEncoder<RepayInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["requestedAmount", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: REPAY_DISCRIMINATOR }),
  );
}

export function getRepayInstructionDataDecoder(): FixedSizeDecoder<RepayInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["requestedAmount", getU64Decoder()],
  ]);
}

export function getRepayInstructionDataCodec(): FixedSizeCodec<
  RepayInstructionDataArgs,
  RepayInstructionData
> {
  return combineCodec(
    getRepayInstructionDataEncoder(),
    getRepayInstructionDataDecoder(),
  );
}

export type RepayAsyncInput<
  TAccountOwner extends string = string,
  TAccountPosition extends string = string,
  TAccountBorrowMint extends string = string,
  TAccountPositionCollateralAccount extends string = string,
  TAccountPositionUsdcAccount extends string = string,
  TAccountPositionDestinationAccount extends string = string,
  TAccountOwnerUsdcAccount extends string = string,
  TAccountObligation extends string = string,
  TAccountLendingMarket extends string = string,
  TAccountLendingMarketAuthority extends string = string,
  TAccountCollateralReserve extends string = string,
  TAccountBorrowReserve extends string = string,
  TAccountBorrowReserveLiquiditySupply extends string = string,
  TAccountBorrowReserveFarmState extends string = string,
  TAccountBorrowObligationFarmState extends string = string,
  TAccountCollateralScopePrices extends string = string,
  TAccountBorrowScopePrices extends string = string,
  TAccountFarmsProgram extends string = string,
  TAccountKaminoProgram extends string = string,
  TAccountInstructionSysvar extends string = string,
  TAccountBorrowTokenProgram extends string = string,
> = {
  owner: TransactionSigner<TAccountOwner>;
  position: Address<TAccountPosition>;
  borrowMint: Address<TAccountBorrowMint>;
  positionCollateralAccount: Address<TAccountPositionCollateralAccount>;
  positionUsdcAccount: Address<TAccountPositionUsdcAccount>;
  positionDestinationAccount: Address<TAccountPositionDestinationAccount>;
  ownerUsdcAccount?: Address<TAccountOwnerUsdcAccount>;
  obligation: Address<TAccountObligation>;
  lendingMarket: Address<TAccountLendingMarket>;
  lendingMarketAuthority: Address<TAccountLendingMarketAuthority>;
  collateralReserve: Address<TAccountCollateralReserve>;
  borrowReserve: Address<TAccountBorrowReserve>;
  borrowReserveLiquiditySupply: Address<TAccountBorrowReserveLiquiditySupply>;
  borrowReserveFarmState?: Address<TAccountBorrowReserveFarmState>;
  borrowObligationFarmState?: Address<TAccountBorrowObligationFarmState>;
  collateralScopePrices: Address<TAccountCollateralScopePrices>;
  borrowScopePrices: Address<TAccountBorrowScopePrices>;
  farmsProgram?: Address<TAccountFarmsProgram>;
  kaminoProgram?: Address<TAccountKaminoProgram>;
  instructionSysvar?: Address<TAccountInstructionSysvar>;
  borrowTokenProgram: Address<TAccountBorrowTokenProgram>;
  requestedAmount: RepayInstructionDataArgs["requestedAmount"];
};

export async function getRepayInstructionAsync<
  TAccountOwner extends string,
  TAccountPosition extends string,
  TAccountBorrowMint extends string,
  TAccountPositionCollateralAccount extends string,
  TAccountPositionUsdcAccount extends string,
  TAccountPositionDestinationAccount extends string,
  TAccountOwnerUsdcAccount extends string,
  TAccountObligation extends string,
  TAccountLendingMarket extends string,
  TAccountLendingMarketAuthority extends string,
  TAccountCollateralReserve extends string,
  TAccountBorrowReserve extends string,
  TAccountBorrowReserveLiquiditySupply extends string,
  TAccountBorrowReserveFarmState extends string,
  TAccountBorrowObligationFarmState extends string,
  TAccountCollateralScopePrices extends string,
  TAccountBorrowScopePrices extends string,
  TAccountFarmsProgram extends string,
  TAccountKaminoProgram extends string,
  TAccountInstructionSysvar extends string,
  TAccountBorrowTokenProgram extends string,
  TProgramAddress extends Address = typeof ACCRUE_PROGRAM_ADDRESS,
>(
  input: RepayAsyncInput<
    TAccountOwner,
    TAccountPosition,
    TAccountBorrowMint,
    TAccountPositionCollateralAccount,
    TAccountPositionUsdcAccount,
    TAccountPositionDestinationAccount,
    TAccountOwnerUsdcAccount,
    TAccountObligation,
    TAccountLendingMarket,
    TAccountLendingMarketAuthority,
    TAccountCollateralReserve,
    TAccountBorrowReserve,
    TAccountBorrowReserveLiquiditySupply,
    TAccountBorrowReserveFarmState,
    TAccountBorrowObligationFarmState,
    TAccountCollateralScopePrices,
    TAccountBorrowScopePrices,
    TAccountFarmsProgram,
    TAccountKaminoProgram,
    TAccountInstructionSysvar,
    TAccountBorrowTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  RepayInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountPosition,
    TAccountBorrowMint,
    TAccountPositionCollateralAccount,
    TAccountPositionUsdcAccount,
    TAccountPositionDestinationAccount,
    TAccountOwnerUsdcAccount,
    TAccountObligation,
    TAccountLendingMarket,
    TAccountLendingMarketAuthority,
    TAccountCollateralReserve,
    TAccountBorrowReserve,
    TAccountBorrowReserveLiquiditySupply,
    TAccountBorrowReserveFarmState,
    TAccountBorrowObligationFarmState,
    TAccountCollateralScopePrices,
    TAccountBorrowScopePrices,
    TAccountFarmsProgram,
    TAccountKaminoProgram,
    TAccountInstructionSysvar,
    TAccountBorrowTokenProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ACCRUE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    owner: { value: input.owner ?? null, isWritable: true },
    position: { value: input.position ?? null, isWritable: true },
    borrowMint: { value: input.borrowMint ?? null, isWritable: false },
    positionCollateralAccount: {
      value: input.positionCollateralAccount ?? null,
      isWritable: true,
    },
    positionUsdcAccount: {
      value: input.positionUsdcAccount ?? null,
      isWritable: true,
    },
    positionDestinationAccount: {
      value: input.positionDestinationAccount ?? null,
      isWritable: true,
    },
    ownerUsdcAccount: {
      value: input.ownerUsdcAccount ?? null,
      isWritable: true,
    },
    obligation: { value: input.obligation ?? null, isWritable: true },
    lendingMarket: { value: input.lendingMarket ?? null, isWritable: true },
    lendingMarketAuthority: {
      value: input.lendingMarketAuthority ?? null,
      isWritable: false,
    },
    collateralReserve: {
      value: input.collateralReserve ?? null,
      isWritable: true,
    },
    borrowReserve: { value: input.borrowReserve ?? null, isWritable: true },
    borrowReserveLiquiditySupply: {
      value: input.borrowReserveLiquiditySupply ?? null,
      isWritable: true,
    },
    borrowReserveFarmState: {
      value: input.borrowReserveFarmState ?? null,
      isWritable: true,
    },
    borrowObligationFarmState: {
      value: input.borrowObligationFarmState ?? null,
      isWritable: true,
    },
    collateralScopePrices: {
      value: input.collateralScopePrices ?? null,
      isWritable: false,
    },
    borrowScopePrices: {
      value: input.borrowScopePrices ?? null,
      isWritable: false,
    },
    farmsProgram: { value: input.farmsProgram ?? null, isWritable: false },
    kaminoProgram: { value: input.kaminoProgram ?? null, isWritable: false },
    instructionSysvar: {
      value: input.instructionSysvar ?? null,
      isWritable: false,
    },
    borrowTokenProgram: {
      value: input.borrowTokenProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.ownerUsdcAccount.value) {
    accounts.ownerUsdcAccount.value = await getProgramDerivedAddress({
      programAddress:
        "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.owner.value)),
        getAddressEncoder().encode(
          expectAddress(accounts.borrowTokenProgram.value),
        ),
        getAddressEncoder().encode(expectAddress(accounts.borrowMint.value)),
      ],
    });
  }
  if (!accounts.farmsProgram.value) {
    accounts.farmsProgram.value =
      "FarmsPZpWu9i7Kky8tPN37rs2TpmMrAZrC7S7vJa91Hr" as Address<"FarmsPZpWu9i7Kky8tPN37rs2TpmMrAZrC7S7vJa91Hr">;
  }
  if (!accounts.kaminoProgram.value) {
    accounts.kaminoProgram.value =
      "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD" as Address<"KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD">;
  }
  if (!accounts.instructionSysvar.value) {
    accounts.instructionSysvar.value =
      "Sysvar1nstructions1111111111111111111111111" as Address<"Sysvar1nstructions1111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.owner),
      getAccountMeta(accounts.position),
      getAccountMeta(accounts.borrowMint),
      getAccountMeta(accounts.positionCollateralAccount),
      getAccountMeta(accounts.positionUsdcAccount),
      getAccountMeta(accounts.positionDestinationAccount),
      getAccountMeta(accounts.ownerUsdcAccount),
      getAccountMeta(accounts.obligation),
      getAccountMeta(accounts.lendingMarket),
      getAccountMeta(accounts.lendingMarketAuthority),
      getAccountMeta(accounts.collateralReserve),
      getAccountMeta(accounts.borrowReserve),
      getAccountMeta(accounts.borrowReserveLiquiditySupply),
      getAccountMeta(accounts.borrowReserveFarmState),
      getAccountMeta(accounts.borrowObligationFarmState),
      getAccountMeta(accounts.collateralScopePrices),
      getAccountMeta(accounts.borrowScopePrices),
      getAccountMeta(accounts.farmsProgram),
      getAccountMeta(accounts.kaminoProgram),
      getAccountMeta(accounts.instructionSysvar),
      getAccountMeta(accounts.borrowTokenProgram),
    ],
    data: getRepayInstructionDataEncoder().encode(
      args as RepayInstructionDataArgs,
    ),
    programAddress,
  } as RepayInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountPosition,
    TAccountBorrowMint,
    TAccountPositionCollateralAccount,
    TAccountPositionUsdcAccount,
    TAccountPositionDestinationAccount,
    TAccountOwnerUsdcAccount,
    TAccountObligation,
    TAccountLendingMarket,
    TAccountLendingMarketAuthority,
    TAccountCollateralReserve,
    TAccountBorrowReserve,
    TAccountBorrowReserveLiquiditySupply,
    TAccountBorrowReserveFarmState,
    TAccountBorrowObligationFarmState,
    TAccountCollateralScopePrices,
    TAccountBorrowScopePrices,
    TAccountFarmsProgram,
    TAccountKaminoProgram,
    TAccountInstructionSysvar,
    TAccountBorrowTokenProgram
  >);
}

export type RepayInput<
  TAccountOwner extends string = string,
  TAccountPosition extends string = string,
  TAccountBorrowMint extends string = string,
  TAccountPositionCollateralAccount extends string = string,
  TAccountPositionUsdcAccount extends string = string,
  TAccountPositionDestinationAccount extends string = string,
  TAccountOwnerUsdcAccount extends string = string,
  TAccountObligation extends string = string,
  TAccountLendingMarket extends string = string,
  TAccountLendingMarketAuthority extends string = string,
  TAccountCollateralReserve extends string = string,
  TAccountBorrowReserve extends string = string,
  TAccountBorrowReserveLiquiditySupply extends string = string,
  TAccountBorrowReserveFarmState extends string = string,
  TAccountBorrowObligationFarmState extends string = string,
  TAccountCollateralScopePrices extends string = string,
  TAccountBorrowScopePrices extends string = string,
  TAccountFarmsProgram extends string = string,
  TAccountKaminoProgram extends string = string,
  TAccountInstructionSysvar extends string = string,
  TAccountBorrowTokenProgram extends string = string,
> = {
  owner: TransactionSigner<TAccountOwner>;
  position: Address<TAccountPosition>;
  borrowMint: Address<TAccountBorrowMint>;
  positionCollateralAccount: Address<TAccountPositionCollateralAccount>;
  positionUsdcAccount: Address<TAccountPositionUsdcAccount>;
  positionDestinationAccount: Address<TAccountPositionDestinationAccount>;
  ownerUsdcAccount: Address<TAccountOwnerUsdcAccount>;
  obligation: Address<TAccountObligation>;
  lendingMarket: Address<TAccountLendingMarket>;
  lendingMarketAuthority: Address<TAccountLendingMarketAuthority>;
  collateralReserve: Address<TAccountCollateralReserve>;
  borrowReserve: Address<TAccountBorrowReserve>;
  borrowReserveLiquiditySupply: Address<TAccountBorrowReserveLiquiditySupply>;
  borrowReserveFarmState?: Address<TAccountBorrowReserveFarmState>;
  borrowObligationFarmState?: Address<TAccountBorrowObligationFarmState>;
  collateralScopePrices: Address<TAccountCollateralScopePrices>;
  borrowScopePrices: Address<TAccountBorrowScopePrices>;
  farmsProgram?: Address<TAccountFarmsProgram>;
  kaminoProgram?: Address<TAccountKaminoProgram>;
  instructionSysvar?: Address<TAccountInstructionSysvar>;
  borrowTokenProgram: Address<TAccountBorrowTokenProgram>;
  requestedAmount: RepayInstructionDataArgs["requestedAmount"];
};

export function getRepayInstruction<
  TAccountOwner extends string,
  TAccountPosition extends string,
  TAccountBorrowMint extends string,
  TAccountPositionCollateralAccount extends string,
  TAccountPositionUsdcAccount extends string,
  TAccountPositionDestinationAccount extends string,
  TAccountOwnerUsdcAccount extends string,
  TAccountObligation extends string,
  TAccountLendingMarket extends string,
  TAccountLendingMarketAuthority extends string,
  TAccountCollateralReserve extends string,
  TAccountBorrowReserve extends string,
  TAccountBorrowReserveLiquiditySupply extends string,
  TAccountBorrowReserveFarmState extends string,
  TAccountBorrowObligationFarmState extends string,
  TAccountCollateralScopePrices extends string,
  TAccountBorrowScopePrices extends string,
  TAccountFarmsProgram extends string,
  TAccountKaminoProgram extends string,
  TAccountInstructionSysvar extends string,
  TAccountBorrowTokenProgram extends string,
  TProgramAddress extends Address = typeof ACCRUE_PROGRAM_ADDRESS,
>(
  input: RepayInput<
    TAccountOwner,
    TAccountPosition,
    TAccountBorrowMint,
    TAccountPositionCollateralAccount,
    TAccountPositionUsdcAccount,
    TAccountPositionDestinationAccount,
    TAccountOwnerUsdcAccount,
    TAccountObligation,
    TAccountLendingMarket,
    TAccountLendingMarketAuthority,
    TAccountCollateralReserve,
    TAccountBorrowReserve,
    TAccountBorrowReserveLiquiditySupply,
    TAccountBorrowReserveFarmState,
    TAccountBorrowObligationFarmState,
    TAccountCollateralScopePrices,
    TAccountBorrowScopePrices,
    TAccountFarmsProgram,
    TAccountKaminoProgram,
    TAccountInstructionSysvar,
    TAccountBorrowTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): RepayInstruction<
  TProgramAddress,
  TAccountOwner,
  TAccountPosition,
  TAccountBorrowMint,
  TAccountPositionCollateralAccount,
  TAccountPositionUsdcAccount,
  TAccountPositionDestinationAccount,
  TAccountOwnerUsdcAccount,
  TAccountObligation,
  TAccountLendingMarket,
  TAccountLendingMarketAuthority,
  TAccountCollateralReserve,
  TAccountBorrowReserve,
  TAccountBorrowReserveLiquiditySupply,
  TAccountBorrowReserveFarmState,
  TAccountBorrowObligationFarmState,
  TAccountCollateralScopePrices,
  TAccountBorrowScopePrices,
  TAccountFarmsProgram,
  TAccountKaminoProgram,
  TAccountInstructionSysvar,
  TAccountBorrowTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? ACCRUE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    owner: { value: input.owner ?? null, isWritable: true },
    position: { value: input.position ?? null, isWritable: true },
    borrowMint: { value: input.borrowMint ?? null, isWritable: false },
    positionCollateralAccount: {
      value: input.positionCollateralAccount ?? null,
      isWritable: true,
    },
    positionUsdcAccount: {
      value: input.positionUsdcAccount ?? null,
      isWritable: true,
    },
    positionDestinationAccount: {
      value: input.positionDestinationAccount ?? null,
      isWritable: true,
    },
    ownerUsdcAccount: {
      value: input.ownerUsdcAccount ?? null,
      isWritable: true,
    },
    obligation: { value: input.obligation ?? null, isWritable: true },
    lendingMarket: { value: input.lendingMarket ?? null, isWritable: true },
    lendingMarketAuthority: {
      value: input.lendingMarketAuthority ?? null,
      isWritable: false,
    },
    collateralReserve: {
      value: input.collateralReserve ?? null,
      isWritable: true,
    },
    borrowReserve: { value: input.borrowReserve ?? null, isWritable: true },
    borrowReserveLiquiditySupply: {
      value: input.borrowReserveLiquiditySupply ?? null,
      isWritable: true,
    },
    borrowReserveFarmState: {
      value: input.borrowReserveFarmState ?? null,
      isWritable: true,
    },
    borrowObligationFarmState: {
      value: input.borrowObligationFarmState ?? null,
      isWritable: true,
    },
    collateralScopePrices: {
      value: input.collateralScopePrices ?? null,
      isWritable: false,
    },
    borrowScopePrices: {
      value: input.borrowScopePrices ?? null,
      isWritable: false,
    },
    farmsProgram: { value: input.farmsProgram ?? null, isWritable: false },
    kaminoProgram: { value: input.kaminoProgram ?? null, isWritable: false },
    instructionSysvar: {
      value: input.instructionSysvar ?? null,
      isWritable: false,
    },
    borrowTokenProgram: {
      value: input.borrowTokenProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.farmsProgram.value) {
    accounts.farmsProgram.value =
      "FarmsPZpWu9i7Kky8tPN37rs2TpmMrAZrC7S7vJa91Hr" as Address<"FarmsPZpWu9i7Kky8tPN37rs2TpmMrAZrC7S7vJa91Hr">;
  }
  if (!accounts.kaminoProgram.value) {
    accounts.kaminoProgram.value =
      "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD" as Address<"KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD">;
  }
  if (!accounts.instructionSysvar.value) {
    accounts.instructionSysvar.value =
      "Sysvar1nstructions1111111111111111111111111" as Address<"Sysvar1nstructions1111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.owner),
      getAccountMeta(accounts.position),
      getAccountMeta(accounts.borrowMint),
      getAccountMeta(accounts.positionCollateralAccount),
      getAccountMeta(accounts.positionUsdcAccount),
      getAccountMeta(accounts.positionDestinationAccount),
      getAccountMeta(accounts.ownerUsdcAccount),
      getAccountMeta(accounts.obligation),
      getAccountMeta(accounts.lendingMarket),
      getAccountMeta(accounts.lendingMarketAuthority),
      getAccountMeta(accounts.collateralReserve),
      getAccountMeta(accounts.borrowReserve),
      getAccountMeta(accounts.borrowReserveLiquiditySupply),
      getAccountMeta(accounts.borrowReserveFarmState),
      getAccountMeta(accounts.borrowObligationFarmState),
      getAccountMeta(accounts.collateralScopePrices),
      getAccountMeta(accounts.borrowScopePrices),
      getAccountMeta(accounts.farmsProgram),
      getAccountMeta(accounts.kaminoProgram),
      getAccountMeta(accounts.instructionSysvar),
      getAccountMeta(accounts.borrowTokenProgram),
    ],
    data: getRepayInstructionDataEncoder().encode(
      args as RepayInstructionDataArgs,
    ),
    programAddress,
  } as RepayInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountPosition,
    TAccountBorrowMint,
    TAccountPositionCollateralAccount,
    TAccountPositionUsdcAccount,
    TAccountPositionDestinationAccount,
    TAccountOwnerUsdcAccount,
    TAccountObligation,
    TAccountLendingMarket,
    TAccountLendingMarketAuthority,
    TAccountCollateralReserve,
    TAccountBorrowReserve,
    TAccountBorrowReserveLiquiditySupply,
    TAccountBorrowReserveFarmState,
    TAccountBorrowObligationFarmState,
    TAccountCollateralScopePrices,
    TAccountBorrowScopePrices,
    TAccountFarmsProgram,
    TAccountKaminoProgram,
    TAccountInstructionSysvar,
    TAccountBorrowTokenProgram
  >);
}

export type ParsedRepayInstruction<
  TProgram extends string = typeof ACCRUE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    owner: TAccountMetas[0];
    position: TAccountMetas[1];
    borrowMint: TAccountMetas[2];
    positionCollateralAccount: TAccountMetas[3];
    positionUsdcAccount: TAccountMetas[4];
    positionDestinationAccount: TAccountMetas[5];
    ownerUsdcAccount: TAccountMetas[6];
    obligation: TAccountMetas[7];
    lendingMarket: TAccountMetas[8];
    lendingMarketAuthority: TAccountMetas[9];
    collateralReserve: TAccountMetas[10];
    borrowReserve: TAccountMetas[11];
    borrowReserveLiquiditySupply: TAccountMetas[12];
    borrowReserveFarmState?: TAccountMetas[13] | undefined;
    borrowObligationFarmState?: TAccountMetas[14] | undefined;
    collateralScopePrices: TAccountMetas[15];
    borrowScopePrices: TAccountMetas[16];
    farmsProgram: TAccountMetas[17];
    kaminoProgram: TAccountMetas[18];
    instructionSysvar: TAccountMetas[19];
    borrowTokenProgram: TAccountMetas[20];
  };
  data: RepayInstructionData;
};

export function parseRepayInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedRepayInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 21) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  const getNextOptionalAccount = () => {
    const accountMeta = getNextAccount();
    return accountMeta.address === ACCRUE_PROGRAM_ADDRESS
      ? undefined
      : accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      owner: getNextAccount(),
      position: getNextAccount(),
      borrowMint: getNextAccount(),
      positionCollateralAccount: getNextAccount(),
      positionUsdcAccount: getNextAccount(),
      positionDestinationAccount: getNextAccount(),
      ownerUsdcAccount: getNextAccount(),
      obligation: getNextAccount(),
      lendingMarket: getNextAccount(),
      lendingMarketAuthority: getNextAccount(),
      collateralReserve: getNextAccount(),
      borrowReserve: getNextAccount(),
      borrowReserveLiquiditySupply: getNextAccount(),
      borrowReserveFarmState: getNextOptionalAccount(),
      borrowObligationFarmState: getNextOptionalAccount(),
      collateralScopePrices: getNextAccount(),
      borrowScopePrices: getNextAccount(),
      farmsProgram: getNextAccount(),
      kaminoProgram: getNextAccount(),
      instructionSysvar: getNextAccount(),
      borrowTokenProgram: getNextAccount(),
    },
    data: getRepayInstructionDataDecoder().decode(instruction.data),
  };
}
