/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type Option,
  type OptionOrNullable,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { findConfigPda } from "../pdas/index.js";
import { ACCRUE_PROGRAM_ADDRESS } from "../programs/index.js";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared/index.js";

export const SET_PAUSED_DISCRIMINATOR = new Uint8Array([
  91, 60, 125, 192, 176, 225, 166, 218,
]);

export function getSetPausedDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(SET_PAUSED_DISCRIMINATOR);
}

export type SetPausedInstruction<
  TProgram extends string = typeof ACCRUE_PROGRAM_ADDRESS,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountConfig extends string
        ? WritableAccount<TAccountConfig>
        : TAccountConfig,
      ...TRemainingAccounts,
    ]
  >;

export type SetPausedInstructionData = {
  discriminator: ReadonlyUint8Array;
  openPaused: Option<boolean>;
  growPaused: Option<boolean>;
};

export type SetPausedInstructionDataArgs = {
  openPaused: OptionOrNullable<boolean>;
  growPaused: OptionOrNullable<boolean>;
};

export function getSetPausedInstructionDataEncoder(): Encoder<SetPausedInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["openPaused", getOptionEncoder(getBooleanEncoder())],
      ["growPaused", getOptionEncoder(getBooleanEncoder())],
    ]),
    (value) => ({ ...value, discriminator: SET_PAUSED_DISCRIMINATOR }),
  );
}

export function getSetPausedInstructionDataDecoder(): Decoder<SetPausedInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["openPaused", getOptionDecoder(getBooleanDecoder())],
    ["growPaused", getOptionDecoder(getBooleanDecoder())],
  ]);
}

export function getSetPausedInstructionDataCodec(): Codec<
  SetPausedInstructionDataArgs,
  SetPausedInstructionData
> {
  return combineCodec(
    getSetPausedInstructionDataEncoder(),
    getSetPausedInstructionDataDecoder(),
  );
}

export type SetPausedAsyncInput<
  TAccountAuthority extends string = string,
  TAccountConfig extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  config?: Address<TAccountConfig>;
  openPaused: SetPausedInstructionDataArgs["openPaused"];
  growPaused: SetPausedInstructionDataArgs["growPaused"];
};

export async function getSetPausedInstructionAsync<
  TAccountAuthority extends string,
  TAccountConfig extends string,
  TProgramAddress extends Address = typeof ACCRUE_PROGRAM_ADDRESS,
>(
  input: SetPausedAsyncInput<TAccountAuthority, TAccountConfig>,
  config?: { programAddress?: TProgramAddress },
): Promise<
  SetPausedInstruction<TProgramAddress, TAccountAuthority, TAccountConfig>
> {
  // Program address.
  const programAddress = config?.programAddress ?? ACCRUE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.config),
    ],
    data: getSetPausedInstructionDataEncoder().encode(
      args as SetPausedInstructionDataArgs,
    ),
    programAddress,
  } as SetPausedInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountConfig
  >);
}

export type SetPausedInput<
  TAccountAuthority extends string = string,
  TAccountConfig extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  config: Address<TAccountConfig>;
  openPaused: SetPausedInstructionDataArgs["openPaused"];
  growPaused: SetPausedInstructionDataArgs["growPaused"];
};

export function getSetPausedInstruction<
  TAccountAuthority extends string,
  TAccountConfig extends string,
  TProgramAddress extends Address = typeof ACCRUE_PROGRAM_ADDRESS,
>(
  input: SetPausedInput<TAccountAuthority, TAccountConfig>,
  config?: { programAddress?: TProgramAddress },
): SetPausedInstruction<TProgramAddress, TAccountAuthority, TAccountConfig> {
  // Program address.
  const programAddress = config?.programAddress ?? ACCRUE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.config),
    ],
    data: getSetPausedInstructionDataEncoder().encode(
      args as SetPausedInstructionDataArgs,
    ),
    programAddress,
  } as SetPausedInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountConfig
  >);
}

export type ParsedSetPausedInstruction<
  TProgram extends string = typeof ACCRUE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    authority: TAccountMetas[0];
    config: TAccountMetas[1];
  };
  data: SetPausedInstructionData;
};

export function parseSetPausedInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedSetPausedInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { authority: getNextAccount(), config: getNextAccount() },
    data: getSetPausedInstructionDataDecoder().decode(instruction.data),
  };
}
