/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { ACCRUE_PROGRAM_ADDRESS } from "../programs/index.js";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared/index.js";
import {
  getStrategyDecoder,
  getStrategyEncoder,
  type Strategy,
  type StrategyArgs,
} from "../types/index.js";

export const SET_STRATEGY_DISCRIMINATOR = new Uint8Array([
  251, 41, 210, 173, 140, 96, 78, 235,
]);

export function getSetStrategyDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    SET_STRATEGY_DISCRIMINATOR,
  );
}

export type SetStrategyInstruction<
  TProgram extends string = typeof ACCRUE_PROGRAM_ADDRESS,
  TAccountOwner extends string | AccountMeta<string> = string,
  TAccountPosition extends string | AccountMeta<string> = string,
  TAccountPositionCollateralAccount extends string | AccountMeta<string> =
    string,
  TAccountPositionUsdcAccount extends string | AccountMeta<string> = string,
  TAccountPositionDestinationAccount extends string | AccountMeta<string> =
    string,
  TAccountObligation extends string | AccountMeta<string> = string,
  TAccountCollateralReserve extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountOwner extends string
        ? ReadonlySignerAccount<TAccountOwner> &
            AccountSignerMeta<TAccountOwner>
        : TAccountOwner,
      TAccountPosition extends string
        ? WritableAccount<TAccountPosition>
        : TAccountPosition,
      TAccountPositionCollateralAccount extends string
        ? ReadonlyAccount<TAccountPositionCollateralAccount>
        : TAccountPositionCollateralAccount,
      TAccountPositionUsdcAccount extends string
        ? ReadonlyAccount<TAccountPositionUsdcAccount>
        : TAccountPositionUsdcAccount,
      TAccountPositionDestinationAccount extends string
        ? ReadonlyAccount<TAccountPositionDestinationAccount>
        : TAccountPositionDestinationAccount,
      TAccountObligation extends string
        ? ReadonlyAccount<TAccountObligation>
        : TAccountObligation,
      TAccountCollateralReserve extends string
        ? ReadonlyAccount<TAccountCollateralReserve>
        : TAccountCollateralReserve,
      ...TRemainingAccounts,
    ]
  >;

export type SetStrategyInstructionData = {
  discriminator: ReadonlyUint8Array;
  strategy: Strategy;
};

export type SetStrategyInstructionDataArgs = { strategy: StrategyArgs };

export function getSetStrategyInstructionDataEncoder(): FixedSizeEncoder<SetStrategyInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["strategy", getStrategyEncoder()],
    ]),
    (value) => ({ ...value, discriminator: SET_STRATEGY_DISCRIMINATOR }),
  );
}

export function getSetStrategyInstructionDataDecoder(): FixedSizeDecoder<SetStrategyInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["strategy", getStrategyDecoder()],
  ]);
}

export function getSetStrategyInstructionDataCodec(): FixedSizeCodec<
  SetStrategyInstructionDataArgs,
  SetStrategyInstructionData
> {
  return combineCodec(
    getSetStrategyInstructionDataEncoder(),
    getSetStrategyInstructionDataDecoder(),
  );
}

export type SetStrategyInput<
  TAccountOwner extends string = string,
  TAccountPosition extends string = string,
  TAccountPositionCollateralAccount extends string = string,
  TAccountPositionUsdcAccount extends string = string,
  TAccountPositionDestinationAccount extends string = string,
  TAccountObligation extends string = string,
  TAccountCollateralReserve extends string = string,
> = {
  owner: TransactionSigner<TAccountOwner>;
  position: Address<TAccountPosition>;
  positionCollateralAccount: Address<TAccountPositionCollateralAccount>;
  positionUsdcAccount: Address<TAccountPositionUsdcAccount>;
  positionDestinationAccount: Address<TAccountPositionDestinationAccount>;
  obligation: Address<TAccountObligation>;
  collateralReserve: Address<TAccountCollateralReserve>;
  strategy: SetStrategyInstructionDataArgs["strategy"];
};

export function getSetStrategyInstruction<
  TAccountOwner extends string,
  TAccountPosition extends string,
  TAccountPositionCollateralAccount extends string,
  TAccountPositionUsdcAccount extends string,
  TAccountPositionDestinationAccount extends string,
  TAccountObligation extends string,
  TAccountCollateralReserve extends string,
  TProgramAddress extends Address = typeof ACCRUE_PROGRAM_ADDRESS,
>(
  input: SetStrategyInput<
    TAccountOwner,
    TAccountPosition,
    TAccountPositionCollateralAccount,
    TAccountPositionUsdcAccount,
    TAccountPositionDestinationAccount,
    TAccountObligation,
    TAccountCollateralReserve
  >,
  config?: { programAddress?: TProgramAddress },
): SetStrategyInstruction<
  TProgramAddress,
  TAccountOwner,
  TAccountPosition,
  TAccountPositionCollateralAccount,
  TAccountPositionUsdcAccount,
  TAccountPositionDestinationAccount,
  TAccountObligation,
  TAccountCollateralReserve
> {
  // Program address.
  const programAddress = config?.programAddress ?? ACCRUE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    owner: { value: input.owner ?? null, isWritable: false },
    position: { value: input.position ?? null, isWritable: true },
    positionCollateralAccount: {
      value: input.positionCollateralAccount ?? null,
      isWritable: false,
    },
    positionUsdcAccount: {
      value: input.positionUsdcAccount ?? null,
      isWritable: false,
    },
    positionDestinationAccount: {
      value: input.positionDestinationAccount ?? null,
      isWritable: false,
    },
    obligation: { value: input.obligation ?? null, isWritable: false },
    collateralReserve: {
      value: input.collateralReserve ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.owner),
      getAccountMeta(accounts.position),
      getAccountMeta(accounts.positionCollateralAccount),
      getAccountMeta(accounts.positionUsdcAccount),
      getAccountMeta(accounts.positionDestinationAccount),
      getAccountMeta(accounts.obligation),
      getAccountMeta(accounts.collateralReserve),
    ],
    data: getSetStrategyInstructionDataEncoder().encode(
      args as SetStrategyInstructionDataArgs,
    ),
    programAddress,
  } as SetStrategyInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountPosition,
    TAccountPositionCollateralAccount,
    TAccountPositionUsdcAccount,
    TAccountPositionDestinationAccount,
    TAccountObligation,
    TAccountCollateralReserve
  >);
}

export type ParsedSetStrategyInstruction<
  TProgram extends string = typeof ACCRUE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    owner: TAccountMetas[0];
    position: TAccountMetas[1];
    positionCollateralAccount: TAccountMetas[2];
    positionUsdcAccount: TAccountMetas[3];
    positionDestinationAccount: TAccountMetas[4];
    obligation: TAccountMetas[5];
    collateralReserve: TAccountMetas[6];
  };
  data: SetStrategyInstructionData;
};

export function parseSetStrategyInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedSetStrategyInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      owner: getNextAccount(),
      position: getNextAccount(),
      positionCollateralAccount: getNextAccount(),
      positionUsdcAccount: getNextAccount(),
      positionDestinationAccount: getNextAccount(),
      obligation: getNextAccount(),
      collateralReserve: getNextAccount(),
    },
    data: getSetStrategyInstructionDataDecoder().decode(instruction.data),
  };
}
