/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { findConfigPda } from "../pdas/index.js";
import { ACCRUE_PROGRAM_ADDRESS } from "../programs/index.js";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared/index.js";

export const SET_SUNSET_DISCRIMINATOR = new Uint8Array([
  65, 164, 24, 89, 110, 17, 175, 70,
]);

export function getSetSunsetDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(SET_SUNSET_DISCRIMINATOR);
}

export type SetSunsetInstruction<
  TProgram extends string = typeof ACCRUE_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? ReadonlySignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountConfig extends string
        ? WritableAccount<TAccountConfig>
        : TAccountConfig,
      ...TRemainingAccounts,
    ]
  >;

export type SetSunsetInstructionData = { discriminator: ReadonlyUint8Array };

export type SetSunsetInstructionDataArgs = {};

export function getSetSunsetInstructionDataEncoder(): FixedSizeEncoder<SetSunsetInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: SET_SUNSET_DISCRIMINATOR }),
  );
}

export function getSetSunsetInstructionDataDecoder(): FixedSizeDecoder<SetSunsetInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getSetSunsetInstructionDataCodec(): FixedSizeCodec<
  SetSunsetInstructionDataArgs,
  SetSunsetInstructionData
> {
  return combineCodec(
    getSetSunsetInstructionDataEncoder(),
    getSetSunsetInstructionDataDecoder(),
  );
}

export type SetSunsetAsyncInput<
  TAccountAdmin extends string = string,
  TAccountConfig extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  config?: Address<TAccountConfig>;
};

export async function getSetSunsetInstructionAsync<
  TAccountAdmin extends string,
  TAccountConfig extends string,
  TProgramAddress extends Address = typeof ACCRUE_PROGRAM_ADDRESS,
>(
  input: SetSunsetAsyncInput<TAccountAdmin, TAccountConfig>,
  config?: { programAddress?: TProgramAddress },
): Promise<
  SetSunsetInstruction<TProgramAddress, TAccountAdmin, TAccountConfig>
> {
  // Program address.
  const programAddress = config?.programAddress ?? ACCRUE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [getAccountMeta(accounts.admin), getAccountMeta(accounts.config)],
    data: getSetSunsetInstructionDataEncoder().encode({}),
    programAddress,
  } as SetSunsetInstruction<TProgramAddress, TAccountAdmin, TAccountConfig>);
}

export type SetSunsetInput<
  TAccountAdmin extends string = string,
  TAccountConfig extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  config: Address<TAccountConfig>;
};

export function getSetSunsetInstruction<
  TAccountAdmin extends string,
  TAccountConfig extends string,
  TProgramAddress extends Address = typeof ACCRUE_PROGRAM_ADDRESS,
>(
  input: SetSunsetInput<TAccountAdmin, TAccountConfig>,
  config?: { programAddress?: TProgramAddress },
): SetSunsetInstruction<TProgramAddress, TAccountAdmin, TAccountConfig> {
  // Program address.
  const programAddress = config?.programAddress ?? ACCRUE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [getAccountMeta(accounts.admin), getAccountMeta(accounts.config)],
    data: getSetSunsetInstructionDataEncoder().encode({}),
    programAddress,
  } as SetSunsetInstruction<TProgramAddress, TAccountAdmin, TAccountConfig>);
}

export type ParsedSetSunsetInstruction<
  TProgram extends string = typeof ACCRUE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    admin: TAccountMetas[0];
    config: TAccountMetas[1];
  };
  data: SetSunsetInstructionData;
};

export function parseSetSunsetInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedSetSunsetInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { admin: getNextAccount(), config: getNextAccount() },
    data: getSetSunsetInstructionDataDecoder().decode(instruction.data),
  };
}
