/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type Option,
  type OptionOrNullable,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { findConfigPda } from "../pdas/index.js";
import { ACCRUE_PROGRAM_ADDRESS } from "../programs/index.js";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared/index.js";
import {
  getCollateralEntryDecoder,
  getCollateralEntryEncoder,
  getConfigLimitsDecoder,
  getConfigLimitsEncoder,
  getDestinationEntryDecoder,
  getDestinationEntryEncoder,
  type CollateralEntry,
  type CollateralEntryArgs,
  type ConfigLimits,
  type ConfigLimitsArgs,
  type DestinationEntry,
  type DestinationEntryArgs,
} from "../types/index.js";

export const UPDATE_CONFIG_DISCRIMINATOR = new Uint8Array([
  29, 158, 252, 191, 10, 83, 219, 99,
]);

export function getUpdateConfigDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_CONFIG_DISCRIMINATOR,
  );
}

export type UpdateConfigInstruction<
  TProgram extends string = typeof ACCRUE_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? ReadonlySignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountConfig extends string
        ? WritableAccount<TAccountConfig>
        : TAccountConfig,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateConfigInstructionData = {
  discriminator: ReadonlyUint8Array;
  limits: Option<ConfigLimits>;
  treasury: Option<Address>;
  guardian: Option<Address>;
  admin: Option<Address>;
  collateral: Option<CollateralEntry>;
  destination: Option<DestinationEntry>;
  borrowMint: Option<Address>;
  borrowReserve: Option<Address>;
};

export type UpdateConfigInstructionDataArgs = {
  limits: OptionOrNullable<ConfigLimitsArgs>;
  treasury: OptionOrNullable<Address>;
  guardian: OptionOrNullable<Address>;
  admin: OptionOrNullable<Address>;
  collateral: OptionOrNullable<CollateralEntryArgs>;
  destination: OptionOrNullable<DestinationEntryArgs>;
  borrowMint: OptionOrNullable<Address>;
  borrowReserve: OptionOrNullable<Address>;
};

export function getUpdateConfigInstructionDataEncoder(): Encoder<UpdateConfigInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["limits", getOptionEncoder(getConfigLimitsEncoder())],
      ["treasury", getOptionEncoder(getAddressEncoder())],
      ["guardian", getOptionEncoder(getAddressEncoder())],
      ["admin", getOptionEncoder(getAddressEncoder())],
      ["collateral", getOptionEncoder(getCollateralEntryEncoder())],
      ["destination", getOptionEncoder(getDestinationEntryEncoder())],
      ["borrowMint", getOptionEncoder(getAddressEncoder())],
      ["borrowReserve", getOptionEncoder(getAddressEncoder())],
    ]),
    (value) => ({ ...value, discriminator: UPDATE_CONFIG_DISCRIMINATOR }),
  );
}

export function getUpdateConfigInstructionDataDecoder(): Decoder<UpdateConfigInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["limits", getOptionDecoder(getConfigLimitsDecoder())],
    ["treasury", getOptionDecoder(getAddressDecoder())],
    ["guardian", getOptionDecoder(getAddressDecoder())],
    ["admin", getOptionDecoder(getAddressDecoder())],
    ["collateral", getOptionDecoder(getCollateralEntryDecoder())],
    ["destination", getOptionDecoder(getDestinationEntryDecoder())],
    ["borrowMint", getOptionDecoder(getAddressDecoder())],
    ["borrowReserve", getOptionDecoder(getAddressDecoder())],
  ]);
}

export function getUpdateConfigInstructionDataCodec(): Codec<
  UpdateConfigInstructionDataArgs,
  UpdateConfigInstructionData
> {
  return combineCodec(
    getUpdateConfigInstructionDataEncoder(),
    getUpdateConfigInstructionDataDecoder(),
  );
}

export type UpdateConfigAsyncInput<
  TAccountAdmin extends string = string,
  TAccountConfig extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  config?: Address<TAccountConfig>;
  limits: UpdateConfigInstructionDataArgs["limits"];
  treasury: UpdateConfigInstructionDataArgs["treasury"];
  guardian: UpdateConfigInstructionDataArgs["guardian"];
  adminArg: UpdateConfigInstructionDataArgs["admin"];
  collateral: UpdateConfigInstructionDataArgs["collateral"];
  destination: UpdateConfigInstructionDataArgs["destination"];
  borrowMint: UpdateConfigInstructionDataArgs["borrowMint"];
  borrowReserve: UpdateConfigInstructionDataArgs["borrowReserve"];
};

export async function getUpdateConfigInstructionAsync<
  TAccountAdmin extends string,
  TAccountConfig extends string,
  TProgramAddress extends Address = typeof ACCRUE_PROGRAM_ADDRESS,
>(
  input: UpdateConfigAsyncInput<TAccountAdmin, TAccountConfig>,
  config?: { programAddress?: TProgramAddress },
): Promise<
  UpdateConfigInstruction<TProgramAddress, TAccountAdmin, TAccountConfig>
> {
  // Program address.
  const programAddress = config?.programAddress ?? ACCRUE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input, admin: input.adminArg };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [getAccountMeta(accounts.admin), getAccountMeta(accounts.config)],
    data: getUpdateConfigInstructionDataEncoder().encode(
      args as UpdateConfigInstructionDataArgs,
    ),
    programAddress,
  } as UpdateConfigInstruction<TProgramAddress, TAccountAdmin, TAccountConfig>);
}

export type UpdateConfigInput<
  TAccountAdmin extends string = string,
  TAccountConfig extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  config: Address<TAccountConfig>;
  limits: UpdateConfigInstructionDataArgs["limits"];
  treasury: UpdateConfigInstructionDataArgs["treasury"];
  guardian: UpdateConfigInstructionDataArgs["guardian"];
  adminArg: UpdateConfigInstructionDataArgs["admin"];
  collateral: UpdateConfigInstructionDataArgs["collateral"];
  destination: UpdateConfigInstructionDataArgs["destination"];
  borrowMint: UpdateConfigInstructionDataArgs["borrowMint"];
  borrowReserve: UpdateConfigInstructionDataArgs["borrowReserve"];
};

export function getUpdateConfigInstruction<
  TAccountAdmin extends string,
  TAccountConfig extends string,
  TProgramAddress extends Address = typeof ACCRUE_PROGRAM_ADDRESS,
>(
  input: UpdateConfigInput<TAccountAdmin, TAccountConfig>,
  config?: { programAddress?: TProgramAddress },
): UpdateConfigInstruction<TProgramAddress, TAccountAdmin, TAccountConfig> {
  // Program address.
  const programAddress = config?.programAddress ?? ACCRUE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input, admin: input.adminArg };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [getAccountMeta(accounts.admin), getAccountMeta(accounts.config)],
    data: getUpdateConfigInstructionDataEncoder().encode(
      args as UpdateConfigInstructionDataArgs,
    ),
    programAddress,
  } as UpdateConfigInstruction<TProgramAddress, TAccountAdmin, TAccountConfig>);
}

export type ParsedUpdateConfigInstruction<
  TProgram extends string = typeof ACCRUE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    admin: TAccountMetas[0];
    config: TAccountMetas[1];
  };
  data: UpdateConfigInstructionData;
};

export function parseUpdateConfigInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedUpdateConfigInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { admin: getNextAccount(), config: getNextAccount() },
    data: getUpdateConfigInstructionDataDecoder().decode(instruction.data),
  };
}
