/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type Codec,
  type Decoder,
  type EncodedAccount,
  type Encoder,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  getCollateralEntryDecoder,
  getCollateralEntryEncoder,
  getDestinationEntryDecoder,
  getDestinationEntryEncoder,
  type CollateralEntry,
  type CollateralEntryArgs,
  type DestinationEntry,
  type DestinationEntryArgs,
} from "../types/index.js";

export const CONFIG_DISCRIMINATOR = new Uint8Array([
  155, 12, 170, 224, 30, 250, 204, 130,
]);

export function getConfigDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(CONFIG_DISCRIMINATOR);
}

export type Config = {
  discriminator: ReadonlyUint8Array;
  admin: Address;
  guardian: Address;
  treasury: Address;
  borrowMint: Address;
  borrowReserve: Address;
  keeperBountyBps: number;
  keeperBountyCapUsdc: bigint;
  performanceFeeBps: number;
  maxSlippageBps: number;
  maxPriceAgeSlots: bigint;
  minProtectIntervalSeconds: bigint;
  minGrowIntervalSeconds: bigint;
  maxShareOfAvailableBps: number;
  minPositionUsd: bigint;
  maxPositionUsd: bigint;
  allowedCollateral: Array<CollateralEntry>;
  allowedDestinations: Array<DestinationEntry>;
  openPaused: boolean;
  growPaused: boolean;
  sunset: boolean;
  version: number;
  bump: number;
};

export type ConfigArgs = {
  admin: Address;
  guardian: Address;
  treasury: Address;
  borrowMint: Address;
  borrowReserve: Address;
  keeperBountyBps: number;
  keeperBountyCapUsdc: number | bigint;
  performanceFeeBps: number;
  maxSlippageBps: number;
  maxPriceAgeSlots: number | bigint;
  minProtectIntervalSeconds: number | bigint;
  minGrowIntervalSeconds: number | bigint;
  maxShareOfAvailableBps: number;
  minPositionUsd: number | bigint;
  maxPositionUsd: number | bigint;
  allowedCollateral: Array<CollateralEntryArgs>;
  allowedDestinations: Array<DestinationEntryArgs>;
  openPaused: boolean;
  growPaused: boolean;
  sunset: boolean;
  version: number;
  bump: number;
};

/** Gets the encoder for {@link ConfigArgs} account data. */
export function getConfigEncoder(): Encoder<ConfigArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["admin", getAddressEncoder()],
      ["guardian", getAddressEncoder()],
      ["treasury", getAddressEncoder()],
      ["borrowMint", getAddressEncoder()],
      ["borrowReserve", getAddressEncoder()],
      ["keeperBountyBps", getU16Encoder()],
      ["keeperBountyCapUsdc", getU64Encoder()],
      ["performanceFeeBps", getU16Encoder()],
      ["maxSlippageBps", getU16Encoder()],
      ["maxPriceAgeSlots", getU64Encoder()],
      ["minProtectIntervalSeconds", getU64Encoder()],
      ["minGrowIntervalSeconds", getU64Encoder()],
      ["maxShareOfAvailableBps", getU16Encoder()],
      ["minPositionUsd", getU64Encoder()],
      ["maxPositionUsd", getU64Encoder()],
      ["allowedCollateral", getArrayEncoder(getCollateralEntryEncoder())],
      ["allowedDestinations", getArrayEncoder(getDestinationEntryEncoder())],
      ["openPaused", getBooleanEncoder()],
      ["growPaused", getBooleanEncoder()],
      ["sunset", getBooleanEncoder()],
      ["version", getU16Encoder()],
      ["bump", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: CONFIG_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link Config} account data. */
export function getConfigDecoder(): Decoder<Config> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["admin", getAddressDecoder()],
    ["guardian", getAddressDecoder()],
    ["treasury", getAddressDecoder()],
    ["borrowMint", getAddressDecoder()],
    ["borrowReserve", getAddressDecoder()],
    ["keeperBountyBps", getU16Decoder()],
    ["keeperBountyCapUsdc", getU64Decoder()],
    ["performanceFeeBps", getU16Decoder()],
    ["maxSlippageBps", getU16Decoder()],
    ["maxPriceAgeSlots", getU64Decoder()],
    ["minProtectIntervalSeconds", getU64Decoder()],
    ["minGrowIntervalSeconds", getU64Decoder()],
    ["maxShareOfAvailableBps", getU16Decoder()],
    ["minPositionUsd", getU64Decoder()],
    ["maxPositionUsd", getU64Decoder()],
    ["allowedCollateral", getArrayDecoder(getCollateralEntryDecoder())],
    ["allowedDestinations", getArrayDecoder(getDestinationEntryDecoder())],
    ["openPaused", getBooleanDecoder()],
    ["growPaused", getBooleanDecoder()],
    ["sunset", getBooleanDecoder()],
    ["version", getU16Decoder()],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link Config} account data. */
export function getConfigCodec(): Codec<ConfigArgs, Config> {
  return combineCodec(getConfigEncoder(), getConfigDecoder());
}

export function decodeConfig<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<Config, TAddress>;
export function decodeConfig<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<Config, TAddress>;
export function decodeConfig<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<Config, TAddress> | MaybeAccount<Config, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getConfigDecoder(),
  );
}

export async function fetchConfig<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<Config, TAddress>> {
  const maybeAccount = await fetchMaybeConfig(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeConfig<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<Config, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeConfig(maybeAccount);
}

export async function fetchAllConfig(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<Config>[]> {
  const maybeAccounts = await fetchAllMaybeConfig(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeConfig(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<Config>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeConfig(maybeAccount));
}
