/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  getPositionStateDecoder,
  getPositionStateEncoder,
  getStrategyDecoder,
  getStrategyEncoder,
  type PositionState,
  type PositionStateArgs,
  type Strategy,
  type StrategyArgs,
} from "../types/index.js";

export const POSITION_DISCRIMINATOR = new Uint8Array([
  170, 188, 143, 228, 122, 64, 247, 208,
]);

export function getPositionDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(POSITION_DISCRIMINATOR);
}

export type Position = {
  discriminator: ReadonlyUint8Array;
  owner: Address;
  collateralMint: Address;
  destinationMint: Address;
  borrowMint: Address;
  market: Address;
  borrowReserve: Address;
  obligation: Address;
  collateralTokenAccount: Address;
  usdcTokenAccount: Address;
  destinationTokenAccount: Address;
  strategy: Strategy;
  feeBpsAtOpen: number;
  state: PositionState;
  openedAt: bigint;
  lastProtectAt: bigint;
  lastGrowAt: bigint;
  protectCount: number;
  growCount: number;
  usdcBorrowedTotal: bigint;
  usdcRepaidTotal: bigint;
  usdcFromSalesTotal: bigint;
  bump: number;
};

export type PositionArgs = {
  owner: Address;
  collateralMint: Address;
  destinationMint: Address;
  borrowMint: Address;
  market: Address;
  borrowReserve: Address;
  obligation: Address;
  collateralTokenAccount: Address;
  usdcTokenAccount: Address;
  destinationTokenAccount: Address;
  strategy: StrategyArgs;
  feeBpsAtOpen: number;
  state: PositionStateArgs;
  openedAt: number | bigint;
  lastProtectAt: number | bigint;
  lastGrowAt: number | bigint;
  protectCount: number;
  growCount: number;
  usdcBorrowedTotal: number | bigint;
  usdcRepaidTotal: number | bigint;
  usdcFromSalesTotal: number | bigint;
  bump: number;
};

/** Gets the encoder for {@link PositionArgs} account data. */
export function getPositionEncoder(): FixedSizeEncoder<PositionArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["owner", getAddressEncoder()],
      ["collateralMint", getAddressEncoder()],
      ["destinationMint", getAddressEncoder()],
      ["borrowMint", getAddressEncoder()],
      ["market", getAddressEncoder()],
      ["borrowReserve", getAddressEncoder()],
      ["obligation", getAddressEncoder()],
      ["collateralTokenAccount", getAddressEncoder()],
      ["usdcTokenAccount", getAddressEncoder()],
      ["destinationTokenAccount", getAddressEncoder()],
      ["strategy", getStrategyEncoder()],
      ["feeBpsAtOpen", getU16Encoder()],
      ["state", getPositionStateEncoder()],
      ["openedAt", getI64Encoder()],
      ["lastProtectAt", getI64Encoder()],
      ["lastGrowAt", getI64Encoder()],
      ["protectCount", getU32Encoder()],
      ["growCount", getU32Encoder()],
      ["usdcBorrowedTotal", getU64Encoder()],
      ["usdcRepaidTotal", getU64Encoder()],
      ["usdcFromSalesTotal", getU64Encoder()],
      ["bump", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: POSITION_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link Position} account data. */
export function getPositionDecoder(): FixedSizeDecoder<Position> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["owner", getAddressDecoder()],
    ["collateralMint", getAddressDecoder()],
    ["destinationMint", getAddressDecoder()],
    ["borrowMint", getAddressDecoder()],
    ["market", getAddressDecoder()],
    ["borrowReserve", getAddressDecoder()],
    ["obligation", getAddressDecoder()],
    ["collateralTokenAccount", getAddressDecoder()],
    ["usdcTokenAccount", getAddressDecoder()],
    ["destinationTokenAccount", getAddressDecoder()],
    ["strategy", getStrategyDecoder()],
    ["feeBpsAtOpen", getU16Decoder()],
    ["state", getPositionStateDecoder()],
    ["openedAt", getI64Decoder()],
    ["lastProtectAt", getI64Decoder()],
    ["lastGrowAt", getI64Decoder()],
    ["protectCount", getU32Decoder()],
    ["growCount", getU32Decoder()],
    ["usdcBorrowedTotal", getU64Decoder()],
    ["usdcRepaidTotal", getU64Decoder()],
    ["usdcFromSalesTotal", getU64Decoder()],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link Position} account data. */
export function getPositionCodec(): FixedSizeCodec<PositionArgs, Position> {
  return combineCodec(getPositionEncoder(), getPositionDecoder());
}

export function decodePosition<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<Position, TAddress>;
export function decodePosition<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<Position, TAddress>;
export function decodePosition<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<Position, TAddress> | MaybeAccount<Position, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getPositionDecoder(),
  );
}

export async function fetchPosition<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<Position, TAddress>> {
  const maybeAccount = await fetchMaybePosition(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybePosition<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<Position, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodePosition(maybeAccount);
}

export async function fetchAllPosition(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<Position>[]> {
  const maybeAccounts = await fetchAllMaybePosition(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybePosition(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<Position>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodePosition(maybeAccount));
}

export function getPositionSize(): number {
  return 396;
}
