/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  getAddressEncoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  type Address,
  type ProgramDerivedAddress,
} from "@solana/kit";

export type PositionSeeds = {
  owner: Address;
  collateralMint: Address;
  destinationMint: Address;
};

export async function findPositionPda(
  seeds: PositionSeeds,
  config: { programAddress?: Address | undefined } = {},
): Promise<ProgramDerivedAddress> {
  const {
    programAddress = "6KUwCyECUrvjppwAe92FxTqHLvw2LKGmfkV7j37r6gBb" as Address<"6KUwCyECUrvjppwAe92FxTqHLvw2LKGmfkV7j37r6gBb">,
  } = config;
  return await getProgramDerivedAddress({
    programAddress,
    seeds: [
      getBytesEncoder().encode(
        new Uint8Array([112, 111, 115, 105, 116, 105, 111, 110]),
      ),
      getAddressEncoder().encode(seeds.owner),
      getAddressEncoder().encode(seeds.collateralMint),
      getAddressEncoder().encode(seeds.destinationMint),
    ],
  });
}
