/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type CollateralEntry = {
  mint: Address;
  reserve: Address;
  tokenProgram: Address;
  scopePriceAccount: Address;
  scopeFeedIndex: number;
  enabled: boolean;
};

export type CollateralEntryArgs = CollateralEntry;

export function getCollateralEntryEncoder(): FixedSizeEncoder<CollateralEntryArgs> {
  return getStructEncoder([
    ["mint", getAddressEncoder()],
    ["reserve", getAddressEncoder()],
    ["tokenProgram", getAddressEncoder()],
    ["scopePriceAccount", getAddressEncoder()],
    ["scopeFeedIndex", getU16Encoder()],
    ["enabled", getBooleanEncoder()],
  ]);
}

export function getCollateralEntryDecoder(): FixedSizeDecoder<CollateralEntry> {
  return getStructDecoder([
    ["mint", getAddressDecoder()],
    ["reserve", getAddressDecoder()],
    ["tokenProgram", getAddressDecoder()],
    ["scopePriceAccount", getAddressDecoder()],
    ["scopeFeedIndex", getU16Decoder()],
    ["enabled", getBooleanDecoder()],
  ]);
}

export function getCollateralEntryCodec(): FixedSizeCodec<
  CollateralEntryArgs,
  CollateralEntry
> {
  return combineCodec(getCollateralEntryEncoder(), getCollateralEntryDecoder());
}
