/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type ConfigLimits = {
  keeperBountyBps: number;
  keeperBountyCapUsdc: bigint;
  performanceFeeBps: number;
  maxSlippageBps: number;
  maxPriceAgeSlots: bigint;
  minProtectIntervalSeconds: bigint;
  minGrowIntervalSeconds: bigint;
  maxShareOfAvailableBps: number;
  minPositionUsd: bigint;
  maxPositionUsd: bigint;
};

export type ConfigLimitsArgs = {
  keeperBountyBps: number;
  keeperBountyCapUsdc: number | bigint;
  performanceFeeBps: number;
  maxSlippageBps: number;
  maxPriceAgeSlots: number | bigint;
  minProtectIntervalSeconds: number | bigint;
  minGrowIntervalSeconds: number | bigint;
  maxShareOfAvailableBps: number;
  minPositionUsd: number | bigint;
  maxPositionUsd: number | bigint;
};

export function getConfigLimitsEncoder(): FixedSizeEncoder<ConfigLimitsArgs> {
  return getStructEncoder([
    ["keeperBountyBps", getU16Encoder()],
    ["keeperBountyCapUsdc", getU64Encoder()],
    ["performanceFeeBps", getU16Encoder()],
    ["maxSlippageBps", getU16Encoder()],
    ["maxPriceAgeSlots", getU64Encoder()],
    ["minProtectIntervalSeconds", getU64Encoder()],
    ["minGrowIntervalSeconds", getU64Encoder()],
    ["maxShareOfAvailableBps", getU16Encoder()],
    ["minPositionUsd", getU64Encoder()],
    ["maxPositionUsd", getU64Encoder()],
  ]);
}

export function getConfigLimitsDecoder(): FixedSizeDecoder<ConfigLimits> {
  return getStructDecoder([
    ["keeperBountyBps", getU16Decoder()],
    ["keeperBountyCapUsdc", getU64Decoder()],
    ["performanceFeeBps", getU16Decoder()],
    ["maxSlippageBps", getU16Decoder()],
    ["maxPriceAgeSlots", getU64Decoder()],
    ["minProtectIntervalSeconds", getU64Decoder()],
    ["minGrowIntervalSeconds", getU64Decoder()],
    ["maxShareOfAvailableBps", getU16Decoder()],
    ["minPositionUsd", getU64Decoder()],
    ["maxPositionUsd", getU64Decoder()],
  ]);
}

export function getConfigLimitsCodec(): FixedSizeCodec<
  ConfigLimitsArgs,
  ConfigLimits
> {
  return combineCodec(getConfigLimitsEncoder(), getConfigLimitsDecoder());
}
