/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type DestinationEntry = {
  mint: Address;
  tokenProgram: Address;
  scopePriceAccount: Address;
  scopeFeedIndex: number;
  enabled: boolean;
};

export type DestinationEntryArgs = DestinationEntry;

export function getDestinationEntryEncoder(): FixedSizeEncoder<DestinationEntryArgs> {
  return getStructEncoder([
    ["mint", getAddressEncoder()],
    ["tokenProgram", getAddressEncoder()],
    ["scopePriceAccount", getAddressEncoder()],
    ["scopeFeedIndex", getU16Encoder()],
    ["enabled", getBooleanEncoder()],
  ]);
}

export function getDestinationEntryDecoder(): FixedSizeDecoder<DestinationEntry> {
  return getStructDecoder([
    ["mint", getAddressDecoder()],
    ["tokenProgram", getAddressDecoder()],
    ["scopePriceAccount", getAddressDecoder()],
    ["scopeFeedIndex", getU16Decoder()],
    ["enabled", getBooleanDecoder()],
  ]);
}

export function getDestinationEntryCodec(): FixedSizeCodec<
  DestinationEntryArgs,
  DestinationEntry
> {
  return combineCodec(
    getDestinationEntryEncoder(),
    getDestinationEntryDecoder(),
  );
}
