/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export enum PositionState {
  AwaitingSwap,
  Open,
  Closing,
  Closed,
}

export type PositionStateArgs = PositionState;

export function getPositionStateEncoder(): FixedSizeEncoder<PositionStateArgs> {
  return getEnumEncoder(PositionState);
}

export function getPositionStateDecoder(): FixedSizeDecoder<PositionState> {
  return getEnumDecoder(PositionState);
}

export function getPositionStateCodec(): FixedSizeCodec<
  PositionStateArgs,
  PositionState
> {
  return combineCodec(getPositionStateEncoder(), getPositionStateDecoder());
}
