/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getBooleanDecoder,
  getBooleanEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type Strategy = {
  targetLtvBps: number;
  protectLtvBps: number;
  growBelowLtvBps: number;
  growEnabled: boolean;
  exitOnFlagEnabled: boolean;
};

export type StrategyArgs = Strategy;

export function getStrategyEncoder(): FixedSizeEncoder<StrategyArgs> {
  return getStructEncoder([
    ["targetLtvBps", getU16Encoder()],
    ["protectLtvBps", getU16Encoder()],
    ["growBelowLtvBps", getU16Encoder()],
    ["growEnabled", getBooleanEncoder()],
    ["exitOnFlagEnabled", getBooleanEncoder()],
  ]);
}

export function getStrategyDecoder(): FixedSizeDecoder<Strategy> {
  return getStructDecoder([
    ["targetLtvBps", getU16Decoder()],
    ["protectLtvBps", getU16Decoder()],
    ["growBelowLtvBps", getU16Decoder()],
    ["growEnabled", getBooleanDecoder()],
    ["exitOnFlagEnabled", getBooleanDecoder()],
  ]);
}

export function getStrategyCodec(): FixedSizeCodec<StrategyArgs, Strategy> {
  return combineCodec(getStrategyEncoder(), getStrategyDecoder());
}
