/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from "@solana/kit";
import { ACCRUE_PROGRAM_ADDRESS } from "../programs/index.js";

/** MathOverflow: Arithmetic overflowed */
export const ACCRUE_ERROR__MATH_OVERFLOW = 0x1770; // 6000
/** NotAKaminoAccount: That account is not owned by the lending market program */
export const ACCRUE_ERROR__NOT_A_KAMINO_ACCOUNT = 0x1771; // 6001
/** KaminoAccountTooShort: The lending market account is shorter than its layout */
export const ACCRUE_ERROR__KAMINO_ACCOUNT_TOO_SHORT = 0x1772; // 6002
/** KaminoFieldOutOfRange: A lending market field is outside the range the program can represent */
export const ACCRUE_ERROR__KAMINO_FIELD_OUT_OF_RANGE = 0x1773; // 6003
/** ReserveHasNoScopeFeed: That reserve names no Scope price feed */
export const ACCRUE_ERROR__RESERVE_HAS_NO_SCOPE_FEED = 0x1774; // 6004
/** ReserveNamesNoFarm: That reserve names no farm, so no farm account belongs in this call */
export const ACCRUE_ERROR__RESERVE_NAMES_NO_FARM = 0x1775; // 6005
/** FarmAccountMissing: That reserve names a farm and the farm accounts were not passed */
export const ACCRUE_ERROR__FARM_ACCOUNT_MISSING = 0x1776; // 6006
/** WrongFarmAccount: That is not the farm account the reserve names */
export const ACCRUE_ERROR__WRONG_FARM_ACCOUNT = 0x1777; // 6007
/** ObligationNamesAnUnknownReserve: The obligation names a reserve this instruction was not given */
export const ACCRUE_ERROR__OBLIGATION_NAMES_AN_UNKNOWN_RESERVE = 0x1778; // 6008
/** PerformanceFeeAboveCeiling: The performance fee is above the ceiling written in the program */
export const ACCRUE_ERROR__PERFORMANCE_FEE_ABOVE_CEILING = 0x1779; // 6009
/** SlippageAboveCeiling: The slippage limit is above the ceiling written in the program */
export const ACCRUE_ERROR__SLIPPAGE_ABOVE_CEILING = 0x177a; // 6010
/** KeeperBountyAboveCeiling: The keeper bounty is above the ceiling written in the program */
export const ACCRUE_ERROR__KEEPER_BOUNTY_ABOVE_CEILING = 0x177b; // 6011
/** ShareOfAvailableAboveCeiling: The share of available liquidity is above the ceiling written in the program */
export const ACCRUE_ERROR__SHARE_OF_AVAILABLE_ABOVE_CEILING = 0x177c; // 6012
/** PriceAgeAboveCeiling: The price age is outside the range the program allows */
export const ACCRUE_ERROR__PRICE_AGE_ABOVE_CEILING = 0x177d; // 6013
/** IntervalBelowFloor: The interval is below the floor written in the program */
export const ACCRUE_ERROR__INTERVAL_BELOW_FLOOR = 0x177e; // 6014
/** PositionSizeLimitsInverted: The minimum position size is above the maximum */
export const ACCRUE_ERROR__POSITION_SIZE_LIMITS_INVERTED = 0x177f; // 6015
/** UnknownTokenProgram: That token program is neither Token nor Token 2022 */
export const ACCRUE_ERROR__UNKNOWN_TOKEN_PROGRAM = 0x1780; // 6016
/** CollateralEntryIncomplete: The collateral entry is missing a mint, a reserve or a price account */
export const ACCRUE_ERROR__COLLATERAL_ENTRY_INCOMPLETE = 0x1781; // 6017
/** DestinationEntryIncomplete: The destination entry is missing a mint or a price account */
export const ACCRUE_ERROR__DESTINATION_ENTRY_INCOMPLETE = 0x1782; // 6018
/** AllowListFull: The allow list is full */
export const ACCRUE_ERROR__ALLOW_LIST_FULL = 0x1783; // 6019
/** CollateralNotAllowed: That collateral is not enabled */
export const ACCRUE_ERROR__COLLATERAL_NOT_ALLOWED = 0x1784; // 6020
/** DestinationNotAllowed: That destination is not enabled */
export const ACCRUE_ERROR__DESTINATION_NOT_ALLOWED = 0x1785; // 6021
/** OpensArePaused: New positions are paused */
export const ACCRUE_ERROR__OPENS_ARE_PAUSED = 0x1786; // 6022
/** GrowsArePaused: Growing is paused */
export const ACCRUE_ERROR__GROWS_ARE_PAUSED = 0x1787; // 6023
/** ProgramIsRetiring: The program is retiring and will not open new positions */
export const ACCRUE_ERROR__PROGRAM_IS_RETIRING = 0x1788; // 6024
/** ReserveLeavesNoGuardRoom: This reserve leaves no room between its liquidation threshold and the guard */
export const ACCRUE_ERROR__RESERVE_LEAVES_NO_GUARD_ROOM = 0x1789; // 6025
/** ProtectLevelTooHigh: The guard level is too close to the liquidation threshold */
export const ACCRUE_ERROR__PROTECT_LEVEL_TOO_HIGH = 0x178a; // 6026
/** TargetLevelTooHigh: The borrow level is too close to the guard level or above what the market allows */
export const ACCRUE_ERROR__TARGET_LEVEL_TOO_HIGH = 0x178b; // 6027
/** TargetLevelTooLow: The borrow level must be above zero */
export const ACCRUE_ERROR__TARGET_LEVEL_TOO_LOW = 0x178c; // 6028
/** GrowLevelTooHigh: The grow level must sit below the borrow level */
export const ACCRUE_ERROR__GROW_LEVEL_TOO_HIGH = 0x178d; // 6029
/** NotThePositionOwner: Only the owner of this position may do that */
export const ACCRUE_ERROR__NOT_THE_POSITION_OWNER = 0x178e; // 6030
/** WrongPositionState: This position is not in the state that instruction needs */
export const ACCRUE_ERROR__WRONG_POSITION_STATE = 0x178f; // 6031
/** PositionSizeOutOfRange: The position size is outside the limits in the config */
export const ACCRUE_ERROR__POSITION_SIZE_OUT_OF_RANGE = 0x1790; // 6032
/** BorrowTooLargeAShareOfLiquidity: That borrow would take too large a share of the liquidity left */
export const ACCRUE_ERROR__BORROW_TOO_LARGE_A_SHARE_OF_LIQUIDITY = 0x1791; // 6033
/** LoanToValueAboveTarget: The resulting loan to value is above the target */
export const ACCRUE_ERROR__LOAN_TO_VALUE_ABOVE_TARGET = 0x1792; // 6034
/** DebtStillOutstanding: The position still owes the lending market */
export const ACCRUE_ERROR__DEBT_STILL_OUTSTANDING = 0x1793; // 6035
/** TokensStillHeld: The position still holds tokens */
export const ACCRUE_ERROR__TOKENS_STILL_HELD = 0x1794; // 6036
/** CollateralBalanceMoved: The stock token account changed during an instruction that must not move it */
export const ACCRUE_ERROR__COLLATERAL_BALANCE_MOVED = 0x1795; // 6037
/** ObligationCollateralMoved: The obligation collateral changed during a swap */
export const ACCRUE_ERROR__OBLIGATION_COLLATERAL_MOVED = 0x1796; // 6038
/** SwapSpentTooMuch: The swap spent more than it was allowed to */
export const ACCRUE_ERROR__SWAP_SPENT_TOO_MUCH = 0x1797; // 6039
/** SwapReturnedTooLittle: The swap returned less than the minimum */
export const ACCRUE_ERROR__SWAP_RETURNED_TOO_LITTLE = 0x1798; // 6040
/** TokenLeftForAForbiddenAddress: A token left the position for an address that is not allowed */
export const ACCRUE_ERROR__TOKEN_LEFT_FOR_A_FORBIDDEN_ADDRESS = 0x1799; // 6041
/** PositionLamportsTaken: Lamports were taken out of a position account */
export const ACCRUE_ERROR__POSITION_LAMPORTS_TAKEN = 0x179a; // 6042
/** PositionAccountMissing: A position account no longer exists */
export const ACCRUE_ERROR__POSITION_ACCOUNT_MISSING = 0x179b; // 6043
/** SwapRouteTouchesAForbiddenAccount: The swap route was handed an account it must never receive */
export const ACCRUE_ERROR__SWAP_ROUTE_TOUCHES_A_FORBIDDEN_ACCOUNT = 0x179c; // 6044
/** SwapRouteCallsAnUnknownProgram: The swap route called a program the constants module does not list */
export const ACCRUE_ERROR__SWAP_ROUTE_CALLS_AN_UNKNOWN_PROGRAM = 0x179d; // 6045
/** MinimumOutputTooLow: The minimum output the caller supplied is below what the oracle allows */
export const ACCRUE_ERROR__MINIMUM_OUTPUT_TOO_LOW = 0x179e; // 6046
/** NothingToSwap: The position has no USDC to swap */
export const ACCRUE_ERROR__NOTHING_TO_SWAP = 0x179f; // 6047
/** WrongTreasury: The treasury account in the config does not match the one passed */
export const ACCRUE_ERROR__WRONG_TREASURY = 0x17a0; // 6048
/** NotTheAdmin: Only the admin key may do that */
export const ACCRUE_ERROR__NOT_THE_ADMIN = 0x17a1; // 6049
/** NotTheGuardianOrAdmin: Only the guardian or the admin may do that */
export const ACCRUE_ERROR__NOT_THE_GUARDIAN_OR_ADMIN = 0x17a2; // 6050

export type AccrueError =
  | typeof ACCRUE_ERROR__ALLOW_LIST_FULL
  | typeof ACCRUE_ERROR__BORROW_TOO_LARGE_A_SHARE_OF_LIQUIDITY
  | typeof ACCRUE_ERROR__COLLATERAL_BALANCE_MOVED
  | typeof ACCRUE_ERROR__COLLATERAL_ENTRY_INCOMPLETE
  | typeof ACCRUE_ERROR__COLLATERAL_NOT_ALLOWED
  | typeof ACCRUE_ERROR__DEBT_STILL_OUTSTANDING
  | typeof ACCRUE_ERROR__DESTINATION_ENTRY_INCOMPLETE
  | typeof ACCRUE_ERROR__DESTINATION_NOT_ALLOWED
  | typeof ACCRUE_ERROR__FARM_ACCOUNT_MISSING
  | typeof ACCRUE_ERROR__GROW_LEVEL_TOO_HIGH
  | typeof ACCRUE_ERROR__GROWS_ARE_PAUSED
  | typeof ACCRUE_ERROR__INTERVAL_BELOW_FLOOR
  | typeof ACCRUE_ERROR__KAMINO_ACCOUNT_TOO_SHORT
  | typeof ACCRUE_ERROR__KAMINO_FIELD_OUT_OF_RANGE
  | typeof ACCRUE_ERROR__KEEPER_BOUNTY_ABOVE_CEILING
  | typeof ACCRUE_ERROR__LOAN_TO_VALUE_ABOVE_TARGET
  | typeof ACCRUE_ERROR__MATH_OVERFLOW
  | typeof ACCRUE_ERROR__MINIMUM_OUTPUT_TOO_LOW
  | typeof ACCRUE_ERROR__NOT_A_KAMINO_ACCOUNT
  | typeof ACCRUE_ERROR__NOTHING_TO_SWAP
  | typeof ACCRUE_ERROR__NOT_THE_ADMIN
  | typeof ACCRUE_ERROR__NOT_THE_GUARDIAN_OR_ADMIN
  | typeof ACCRUE_ERROR__NOT_THE_POSITION_OWNER
  | typeof ACCRUE_ERROR__OBLIGATION_COLLATERAL_MOVED
  | typeof ACCRUE_ERROR__OBLIGATION_NAMES_AN_UNKNOWN_RESERVE
  | typeof ACCRUE_ERROR__OPENS_ARE_PAUSED
  | typeof ACCRUE_ERROR__PERFORMANCE_FEE_ABOVE_CEILING
  | typeof ACCRUE_ERROR__POSITION_ACCOUNT_MISSING
  | typeof ACCRUE_ERROR__POSITION_LAMPORTS_TAKEN
  | typeof ACCRUE_ERROR__POSITION_SIZE_LIMITS_INVERTED
  | typeof ACCRUE_ERROR__POSITION_SIZE_OUT_OF_RANGE
  | typeof ACCRUE_ERROR__PRICE_AGE_ABOVE_CEILING
  | typeof ACCRUE_ERROR__PROGRAM_IS_RETIRING
  | typeof ACCRUE_ERROR__PROTECT_LEVEL_TOO_HIGH
  | typeof ACCRUE_ERROR__RESERVE_HAS_NO_SCOPE_FEED
  | typeof ACCRUE_ERROR__RESERVE_LEAVES_NO_GUARD_ROOM
  | typeof ACCRUE_ERROR__RESERVE_NAMES_NO_FARM
  | typeof ACCRUE_ERROR__SHARE_OF_AVAILABLE_ABOVE_CEILING
  | typeof ACCRUE_ERROR__SLIPPAGE_ABOVE_CEILING
  | typeof ACCRUE_ERROR__SWAP_RETURNED_TOO_LITTLE
  | typeof ACCRUE_ERROR__SWAP_ROUTE_CALLS_AN_UNKNOWN_PROGRAM
  | typeof ACCRUE_ERROR__SWAP_ROUTE_TOUCHES_A_FORBIDDEN_ACCOUNT
  | typeof ACCRUE_ERROR__SWAP_SPENT_TOO_MUCH
  | typeof ACCRUE_ERROR__TARGET_LEVEL_TOO_HIGH
  | typeof ACCRUE_ERROR__TARGET_LEVEL_TOO_LOW
  | typeof ACCRUE_ERROR__TOKEN_LEFT_FOR_A_FORBIDDEN_ADDRESS
  | typeof ACCRUE_ERROR__TOKENS_STILL_HELD
  | typeof ACCRUE_ERROR__UNKNOWN_TOKEN_PROGRAM
  | typeof ACCRUE_ERROR__WRONG_FARM_ACCOUNT
  | typeof ACCRUE_ERROR__WRONG_POSITION_STATE
  | typeof ACCRUE_ERROR__WRONG_TREASURY;

let accrueErrorMessages: Record<AccrueError, string> | undefined;
if (process.env['NODE_ENV'] !== "production") {
  accrueErrorMessages = {
    [ACCRUE_ERROR__ALLOW_LIST_FULL]: `The allow list is full`,
    [ACCRUE_ERROR__BORROW_TOO_LARGE_A_SHARE_OF_LIQUIDITY]: `That borrow would take too large a share of the liquidity left`,
    [ACCRUE_ERROR__COLLATERAL_BALANCE_MOVED]: `The stock token account changed during an instruction that must not move it`,
    [ACCRUE_ERROR__COLLATERAL_ENTRY_INCOMPLETE]: `The collateral entry is missing a mint, a reserve or a price account`,
    [ACCRUE_ERROR__COLLATERAL_NOT_ALLOWED]: `That collateral is not enabled`,
    [ACCRUE_ERROR__DEBT_STILL_OUTSTANDING]: `The position still owes the lending market`,
    [ACCRUE_ERROR__DESTINATION_ENTRY_INCOMPLETE]: `The destination entry is missing a mint or a price account`,
    [ACCRUE_ERROR__DESTINATION_NOT_ALLOWED]: `That destination is not enabled`,
    [ACCRUE_ERROR__FARM_ACCOUNT_MISSING]: `That reserve names a farm and the farm accounts were not passed`,
    [ACCRUE_ERROR__GROW_LEVEL_TOO_HIGH]: `The grow level must sit below the borrow level`,
    [ACCRUE_ERROR__GROWS_ARE_PAUSED]: `Growing is paused`,
    [ACCRUE_ERROR__INTERVAL_BELOW_FLOOR]: `The interval is below the floor written in the program`,
    [ACCRUE_ERROR__KAMINO_ACCOUNT_TOO_SHORT]: `The lending market account is shorter than its layout`,
    [ACCRUE_ERROR__KAMINO_FIELD_OUT_OF_RANGE]: `A lending market field is outside the range the program can represent`,
    [ACCRUE_ERROR__KEEPER_BOUNTY_ABOVE_CEILING]: `The keeper bounty is above the ceiling written in the program`,
    [ACCRUE_ERROR__LOAN_TO_VALUE_ABOVE_TARGET]: `The resulting loan to value is above the target`,
    [ACCRUE_ERROR__MATH_OVERFLOW]: `Arithmetic overflowed`,
    [ACCRUE_ERROR__MINIMUM_OUTPUT_TOO_LOW]: `The minimum output the caller supplied is below what the oracle allows`,
    [ACCRUE_ERROR__NOT_A_KAMINO_ACCOUNT]: `That account is not owned by the lending market program`,
    [ACCRUE_ERROR__NOTHING_TO_SWAP]: `The position has no USDC to swap`,
    [ACCRUE_ERROR__NOT_THE_ADMIN]: `Only the admin key may do that`,
    [ACCRUE_ERROR__NOT_THE_GUARDIAN_OR_ADMIN]: `Only the guardian or the admin may do that`,
    [ACCRUE_ERROR__NOT_THE_POSITION_OWNER]: `Only the owner of this position may do that`,
    [ACCRUE_ERROR__OBLIGATION_COLLATERAL_MOVED]: `The obligation collateral changed during a swap`,
    [ACCRUE_ERROR__OBLIGATION_NAMES_AN_UNKNOWN_RESERVE]: `The obligation names a reserve this instruction was not given`,
    [ACCRUE_ERROR__OPENS_ARE_PAUSED]: `New positions are paused`,
    [ACCRUE_ERROR__PERFORMANCE_FEE_ABOVE_CEILING]: `The performance fee is above the ceiling written in the program`,
    [ACCRUE_ERROR__POSITION_ACCOUNT_MISSING]: `A position account no longer exists`,
    [ACCRUE_ERROR__POSITION_LAMPORTS_TAKEN]: `Lamports were taken out of a position account`,
    [ACCRUE_ERROR__POSITION_SIZE_LIMITS_INVERTED]: `The minimum position size is above the maximum`,
    [ACCRUE_ERROR__POSITION_SIZE_OUT_OF_RANGE]: `The position size is outside the limits in the config`,
    [ACCRUE_ERROR__PRICE_AGE_ABOVE_CEILING]: `The price age is outside the range the program allows`,
    [ACCRUE_ERROR__PROGRAM_IS_RETIRING]: `The program is retiring and will not open new positions`,
    [ACCRUE_ERROR__PROTECT_LEVEL_TOO_HIGH]: `The guard level is too close to the liquidation threshold`,
    [ACCRUE_ERROR__RESERVE_HAS_NO_SCOPE_FEED]: `That reserve names no Scope price feed`,
    [ACCRUE_ERROR__RESERVE_LEAVES_NO_GUARD_ROOM]: `This reserve leaves no room between its liquidation threshold and the guard`,
    [ACCRUE_ERROR__RESERVE_NAMES_NO_FARM]: `That reserve names no farm, so no farm account belongs in this call`,
    [ACCRUE_ERROR__SHARE_OF_AVAILABLE_ABOVE_CEILING]: `The share of available liquidity is above the ceiling written in the program`,
    [ACCRUE_ERROR__SLIPPAGE_ABOVE_CEILING]: `The slippage limit is above the ceiling written in the program`,
    [ACCRUE_ERROR__SWAP_RETURNED_TOO_LITTLE]: `The swap returned less than the minimum`,
    [ACCRUE_ERROR__SWAP_ROUTE_CALLS_AN_UNKNOWN_PROGRAM]: `The swap route called a program the constants module does not list`,
    [ACCRUE_ERROR__SWAP_ROUTE_TOUCHES_A_FORBIDDEN_ACCOUNT]: `The swap route was handed an account it must never receive`,
    [ACCRUE_ERROR__SWAP_SPENT_TOO_MUCH]: `The swap spent more than it was allowed to`,
    [ACCRUE_ERROR__TARGET_LEVEL_TOO_HIGH]: `The borrow level is too close to the guard level or above what the market allows`,
    [ACCRUE_ERROR__TARGET_LEVEL_TOO_LOW]: `The borrow level must be above zero`,
    [ACCRUE_ERROR__TOKEN_LEFT_FOR_A_FORBIDDEN_ADDRESS]: `A token left the position for an address that is not allowed`,
    [ACCRUE_ERROR__TOKENS_STILL_HELD]: `The position still holds tokens`,
    [ACCRUE_ERROR__UNKNOWN_TOKEN_PROGRAM]: `That token program is neither Token nor Token 2022`,
    [ACCRUE_ERROR__WRONG_FARM_ACCOUNT]: `That is not the farm account the reserve names`,
    [ACCRUE_ERROR__WRONG_POSITION_STATE]: `This position is not in the state that instruction needs`,
    [ACCRUE_ERROR__WRONG_TREASURY]: `The treasury account in the config does not match the one passed`,
  };
}

export function getAccrueErrorMessage(code: AccrueError): string {
  if (process.env['NODE_ENV'] !== "production") {
    return (accrueErrorMessages as Record<AccrueError, string>)[code];
  }

  return "Error message not available in production bundles.";
}

export function isAccrueError<TProgramErrorCode extends AccrueError>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode,
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    ACCRUE_PROGRAM_ADDRESS,
    code,
  );
}
