export const LANDING_COPY = {
  wordmark: 'accrue',
  openApp: 'Open app',
  about: 'About',
  xLabel: 'X',
  xHref: 'https://x.com/accruexyz',
  hero: {
    headline: 'Keep your stocks. Earn on them anyway.',
    body: 'Deposit tokenized stocks like NVDAx, borrow USDC against them, and put that USDC into a yield token. The code guards the loan and repays it before the market can liquidate you. Your stock never leaves an account only you can empty.',
    seeHowItWorks: 'See how it works',
  },
  howItWorks: {
    eyebrow: 'How it works',
    title: 'Five steps, one signature each way',
    next: 'Next',
    startOver: 'Start over',
    previousLabel: 'Previous step',
    stepLabel: (step: string): string => `Step ${step}`,
    counter: (step: string, total: string): string => `${step} / ${total}`,
    steps: [
      'You deposit NVDAx. It goes into an account that only you can empty.',
      'The account borrows USDC against it, less than half of what the stock is worth.',
      'The USDC becomes a yield token like ONyc, which pays yield. The yield is yours.',
      'If the stock falls, the guard sells a little yield token and repays a little loan before the market can liquidate you. It runs by itself.',
      'When you want out, one signature sells the yield token, repays the loan and returns your stock with what it earned.',
    ],
    diagram: {
      wallet: 'Wallet',
      yourPosition: 'YOUR POSITION',
      borrowed: 'borrowed',
      loan: 'LOAN',
      guard: 'guard',
      liquidation: 'liquidation',
      yieldSoFar: 'yield so far',
      profit: '+$3.12',
      stock: 'NVDAx',
      coin: 'USDC',
      startingGauge: '40%',
      startingCounter: '$0.00',
    },
  },
  tryTheGuard: {
    eyebrow: 'Try the guard',
    title: 'Drag the price down',
    setup: '2 NVDAx at $170, $136 borrowed. Guard at 45%, liquidation at 65%.',
    priceLabel: 'NVDAx price',
    startingPrice: '$170.00',
    lowest: '$90',
    highest: '$250',
    startingLiquidation: 'liquidation $104.62',
    loanToValue: 'Loan to value',
    startingLoanToValue: '40.0%',
    liquidationAt: (price: string): string => `liquidation ${price}`,
    repaid: (amount: string, from: string, to: string): string =>
      `Guard repaid ${amount} · liquidation price ${from} → ${to}`,
    idleBefore: 'Nothing to do yet. The guard watches at ',
    idleAfter: '.',
    startingGuardPrice: '$151.11',
  },
  whatItEarns: {
    eyebrow: 'What it earns today',
    title: 'On $1,000 of stock',
    stockColumn: 'Stock',
    earnsColumn: 'Earns a year',
    yieldColumn: 'Yield',
    loanColumn: 'Loan',
    formula: 'earns = borrow share × (yield rate − loan rate)',
    rows: [
      { symbol: 'NVDAx', earns: '+$25.96', yieldRate: '11.54%', loanRate: '5.05%' },
      { symbol: 'SPYx', earns: '+$35.70', yieldRate: '11.54%', loanRate: '5.05%' },
    ],
  },
  whatYouKeep: {
    eyebrow: 'What you keep',
    cards: [
      {
        title: 'Your stock stays yours',
        body: 'It sits in an account only you can empty, with all of its upside.',
      },
      {
        title: 'One signature in, one out',
        body: 'Deposit with one signature. Leave with one, and everything returns to your wallet.',
      },
      {
        title: 'A guard that runs without you',
        body: 'If the stock falls, it repays part of the loan before liquidation. No one has to be awake.',
      },
    ],
  },
  builtOn: {
    eyebrow: 'Built on',
    parts: [
      { name: 'Solana', what: 'The network everything settles on.' },
      {
        name: 'Kamino',
        what: 'The lending market that holds your stock and lends the USDC.',
      },
      {
        name: 'Jupiter',
        what: 'The router that swaps USDC into the yield token and back.',
      },
      {
        name: 'xStocks',
        what: 'The tokenized stocks you deposit, one for one with the shares.',
      },
      { name: 'Yield tokens', what: 'Where the USDC goes to earn.' },
    ],
  },
} as const;
