export const PORTFOLIO_VALUE_COPY = {
  earnedSoFar: 'Earned so far',
  afterTheLoan: 'after the loan',
  inAccrue: 'In Accrue',
  owedToTheMarket: 'Owed',
  whatYourPositionsAreWorth: 'what your positions are worth',
  holdingTitle: 'What is earning for you',
  holdingLine: (amount: string, symbol: string): string => `${amount} ${symbol}`,
  holdingPrice: (price: string): string => `at ${price}`,
  nothingEarningYet: 'Nothing is earning yet. Your first deposit starts it.',
  everythingYouHold: 'everything you hold',
  inYourPositions: 'in your positions',
  seeBreakdown: 'See breakdown',
  breakdownTitle: 'What that adds up to',
  stockInTheMarket: 'Stock in the market',
  yieldTokens: 'Yield tokens',
  owed: 'Owed to the market',
  positionEquity: 'Your positions are worth',
  stockInYourWallet: 'Stock in your wallet',
  usdcInYourWallet: 'USDC in your wallet',
  everything: 'Everything you hold',
  since: (howLongAgo: string): string => `since ${howLongAgo}`,
  nothingYet: 'Nothing yet. Your first deposit starts the line.',
} as const;

export const PORTFOLIO_COPY = {
  title: 'Portfolio',
  guarded: 'Guarded',
  noLongerOpen: 'No longer open',
  inWhat: 'In',
  priceAndDistance: (price: string, away: string): string => `${price}, ${away} away`,
  balanceAndValue: (balance: string, value: string): string => `${balance} · ${value}`,
  inAccrue: 'In Accrue',
  owed: 'Owed',
  earned: 'Earned so far',
  openPositions: 'Open positions',
  noPositions: 'You have no positions yet.',
  stocksInWallet: 'Stocks in your wallet',
  putToWork: 'Put to work',
  health: 'Health',
  guard: 'Guard',
  worth: 'Stock in the market',
  holding: 'Holding',
  netRate: 'Earning, after the loan',
  liquidatedAt: 'Liquidated at',
  loanToValue: 'Loan to value',
  aYear: (rate: string): string => `${rate} / yr`,
  ofTarget: (now: string, target: string): string => `${now} of ${target}`,
} as const;
