export const PORTFOLIO_COPY = {
  title: 'Portfolio',
  inAccrue: 'In Accrue',
  owed: 'Owed',
  earned: 'Earned so far',
  openPositions: 'Open positions',
  noPositions: 'You have no positions yet.',
  stocksInWallet: 'Stocks in your wallet',
  putToWork: 'Put to work',
  health: 'Health',
  guard: 'Guard',
  worth: 'Stock in the market',
  holding: 'Holding',
  netRate: 'Earning, after the loan',
  liquidatedAt: 'Liquidated at',
  loanToValue: 'Loan to value',
  aYear: (rate: string): string => `${rate} / yr`,
  ofTarget: (now: string, target: string): string => `${now} of ${target}`,
} as const;
