/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { type Address } from "@solana/kit";

export const ACCRUE_PROGRAM_ADDRESS =
  "6KUwCyECUrvjppwAe92FxTqHLvw2LKGmfkV7j37r6gBb" as Address<"6KUwCyECUrvjppwAe92FxTqHLvw2LKGmfkV7j37r6gBb">;
